### ISSUE TITLE
ChangeLog properties interpolation in sql file not working

### ISSUE THREAD

**Issue by bashiransari** [liquibase/liquibase#1065]
Hi,

I have 2 levels of hierarchy in my changelogs as shown below and I need to define a property in the second level to be used in the included SQL files. 

**Expectation :**
When I define the property in two changelog files at the second level the SQL files included in each changelog gets the value from the changelog

**Actual behavior:**
The variables are getting replaced in the sql file 

I tried to define the property as local (global: false) but this didn't work as well.

**Directory structure:**

* schema.yml
* scripts 
  * feat1
    * changelog.yml
    * change1.sql
  * feat2
    * changelog.yml
    * change2-1.sql

**schema.yml:**

```
databaseChangeLog:
  - include:
      file: scripts/feat1/changelog.yml
  - include:
      file: scripts/feat2/changelog.yml   
```

**scripts/feat1/changelog.yml:**

```
databaseChangeLog:
  - property:
      name: MyProp
      value: feat1

  - include:
      file: change1.sql
      relativeToChangelogFile: true
```

**scripts/feat2/changelog.yml:**

```
databaseChangeLog:
  - property:
      name: MyProp
      value: feat2

  - include:
      file: change2-1.sql
      relativeToChangelogFile: true
```

**scripts/feat1/change1.sql:**

```
--liquibase formatted sql

--changeset bash:test-4512 splitStatements:true endDelimiter:\nGO
UPDATE User
SET FirstName='${MyProp}'
```

**scripts/feat2/change2-1.sql:**

```
--liquibase formatted sql

--changeset bash:test-4512 splitStatements:true endDelimiter:\nGO
UPDATE User
SET FirstName='${MyProp}'
```

Can you please help.

Thanks
Bash
