### ISSUE TITLE
yaml files: table columns definition - subkeys column vs columns does not result in an error

### ISSUE THREAD

**Issue by pvanek** [liquibase/liquibase#1109]
**Database Vendor & Version**:
MySQL/H2

## Description

Snippet of the changelog file:

```
databaseChangeLog:
  - changeSet:
      id: a
      author: spongebob
      changes:
...
        - createTable:
            tableName: storyteller_task
            columns:
... many correct column definitions ...
              - columns:          <---- see the trailing s
                  constraints:
                    nullable: false
                  name: reported_to_oms
                  type: boolean
                  defaultValue: false
...
```

It results into correct run, the column is not created at all though
