### ISSUE TITLE
under changeset remarks: is not working correctly for a column primary auto increment column

### ISSUE THREAD

**Issue by ad040758** [liquibase/liquibase#1214]
## Environment Windows 10, liquibase 5.8.5, MySQL 5.7.19, mysql-connector-java-5.1.48
**Liquibase Version**: 5.8.5

**Database Vendor & Version**:MySQL 5.7.19

**Operating System Type & Version**:Windows 10

## Description
I am going to create a new table with below code 

```
databaseChangeLog:
- changeSet:
    id: 1591945991286-1
    author: AD040758 (generated)
    changes:
    - createTable:
        columns:
        - column:
            autoIncrement: true
            constraints:
              nullable: false
              primaryKey: true
            name: ObjId
            remarks: |-
              longName: ObjectIdentifier
              description: Unique identifier for each row in a table.
            type: BIGINT
        - column:
            constraints:
              nullable: false
            name: FileId
            remarks: |-
              longName: FileIdentifier
              description: File identifier for each row in a table.
            type: VARCHAR(255)
```

After table creation I am not able to find the comments ( remarks in liquibase ) for the column Objid but I am able to find the comments for column FileId at database level.

A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
I find the issue occur only for Primary key column
* Ensure private information is redacted.

## Steps To Reproduce
Already given above.

List the steps to reproduce the behavior.

* Please be precise and ensure private information is redacted
* Include things like
  * Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  * Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

## Actual Behavior
A clear and concise description of what happens in the software **before** this pull request.

* Include console output if relevant
* Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** this pull request.
