### ISSUE TITLE
Undocumented breaking change in v3.10.2 re. global vs. local properties

### ISSUE THREAD

**Issue by devopsix** [liquibase/liquibase#1293]
## Environment
**Liquibase Version**: 3.10.2 vs. 3.10.1

**Liquibase Integration & Version**: Liquibase Docker

**Database Vendor & Version**: PostgreSQL 11

**Operating System Type & Version**: n/a

## Description
An undocumented breaking change seems to exist in how global vs. local properties are applied between 3.10.1 and 3.10.2.

Given a master changelog that includes two other changelogs.

```yaml
databaseChangeLog:
  - include:
      file: migration-1.yml
  - include:
      file: migration-2.yml
```

The first included changelog defines a property “value_a”. It does not have the `global` attribute set for the `property` element.

```yaml
databaseChangeLog:
  - property:
      name: value_a
      value: FOO
```

The seconds included changelog redefines poperty “value_a” with the `global` attribute set to `false`. The property value is then used in a change.

```yaml
databaseChangeLog:
  - property:
      name: value_a
      global: false
      value: BAR
  - changeSet:
      id: 1
      author: bob
      changes:
        - sql: SELECT '${value_a}';
```

With Liquibase 3.10.1 repeated application of this change log succeeds.

Given 3.10.1 was used to apply this changelog before, application of this change log with Liquibase 3.10.2 fails. Liquibase 3.10.2 detects a change in the second included changelog's checksum which 3.10.1 did not detect.

### Known Workarounds
1. Add `global: false` to the first definition of the property if possible.
1. Add [`validCheckSum`](https://docs.liquibase.com/concepts/basic/changeset.html) to the change set making use of the property.

## Steps To Reproduce
Attached ZIP file contains a runnable example based on Docker images.

1. Extract [attached ZIP file](https://github.com/liquibase/liquibase/files/5006824/example.zip).
1. `docker-compose up -d database`
1. `docker-compose run liquibase-3.10.1`
1. `docker-compose run liquibase-3.10.2`

_Expected result:_ Migrating the database with Liquibase 3.10.2 succeeds if the database has previously been migrated using Liquibase 3.10.1.

_Actual result:_ Migrating the database with Liquibase 3.10.2 fails after the database has previously been migrated using Liquibase 3.10.1.
