### ISSUE TITLE
Auto rollback doesn't work for change type "addNotNullConstraint" with named constraints [Oracle 19]

### ISSUE THREAD

**Issue by highload-russia** [liquibase/liquibase#1492]
## Environment

**Liquibase Version**: Liquibase Community 3.8.6

**Liquibase Integration & Version**: CLI

**Database Vendor & Version**: Oracle 19c

**Operating System Type & Version**: RHEL7

## Description

Auto rollback doesn't work in case of "addNotNullConstraint" (https://docs.liquibase.com/change-types/community/add-not-null-constraint.html) used with "constraintName" attribute.
In that case rollback causes error:
`ORA-01451: column to be modified to NULL cannot be modified to NULL`

## Steps To Reproduce

1. Declare constraint creation:
```
- changeSet:
    id: myid
    author: me
    changes:
    - addNotNullConstraint:
        columnDataType: NUMBER
        columnName: MY_COLUMN
        constraintName: MY_COLUMN_NOT_NULL # <<< the further problem is here
        tableName: MY_TABLE
        validate: true
```

2. Do some error in changesets below to force rollback

## Actual Behavior
```
...
"Unexpected error running Liquibase: ORA-01451: column to be modified to NULL cannot be modified to NULL",
 " [Failed SQL: (1451) ALTER TABLE MY_SCHEMA.MY_TABLE MODIFY MY_COLUMN NULL]"
...
```

## Expected/Desired Behavior
Rolled back successfully

## Additional Context
I guess that generated rollback sql (and `dropNotNullConstraint` change type behaviour as well) is not applicable to drop named constraints.
ORA-01451 error description say that:

> "Cause
> You tried to execute a ALTER TABLE MODIFY attempting to change a column to allow NULL values,  
> but the column either already allows NULL values **or the column is used** in a primary key **or check constraint** and can not accept NULL values."

Named NotNullConstraint is explicit check constraint in fact and it looks like:
```
    MY_COLUMN NUMBER
        constraint MY_COLUMN_NOT_NULL
        check ("MY_COLUMN" IS NOT NULL)
```

To remove named NotNullConstraint in Oracle must be used this clause:
```
alter table MY_TABLE drop constraint MY_COLUMN_NOT_NULL;
```
