### ISSUE TITLE
Adding a non-nullable column to existing table fails. The "value" attribute is ignored.

### ISSUE THREAD

**Issue by anton-erofeev** [liquibase/liquibase#1695]
## Environment
**Liquibase Version**: 4.2.2

**Liquibase Integration & Version**: spring boot

**Database Vendor & Version**: PostgreSQL: 42.2.16

## Description
Adding a non-nullable column to existing table fails. The "value" attribute is ignored. I expect the value from "value" will apply to all existing records in the table

## Steps To Reproduce
```
- changeSet:
  changes:
    -  addColumn
       tableName: sometabel
       columns:
         -  column:
            constraints:
              nullable: false
           name: somecolumn
           type: varchar(30)
           value: SOMEDEFAULTVALUE
```

## Actual Behavior
ERROR: column somecolumn contains null values

## Expected/Desired Behavior
A successful column creation and insertion of default value into existing records (SOMEDEFAULTVALUE)

**My workaround**

```
- changeSet:
  changes:
    -  addColumn
       tableName: sometabel
       columns:
         -  column:
           name: somecolumn
           type: varchar(30)
           value: SOMEDEFAULTVALUE
   -  addNotNullConstraint:
        columnName: somecolumn
        tableName: sometable

```
