### ISSUE TITLE
TableExistsPrecondition can't find table

### ISSUE THREAD

**Issue by stefanchiriac** [liquibase/liquibase#1712]
## Environment
**Liquibase Version**:
3.10.3
**Liquibase Integration & Version**: 
spring boot 2.3.8.RELEASE
**Liquibase Extension(s) & Version**: 
/
**Database Vendor & Version**:
Postgres 12
**Operating System Type & Version**:
Windows 10

## Description
When creating a condition for tableExists, It always returns that can't find the table even the table exists.
I traced the problem on `TableExistsPrecondition` on following if :

```
if (!SnapshotGeneratorFactory.getInstance().has(new Table().setName(correctedTableName).setSchema(new Schema(getCatalogName(), getSchemaName())), database)) {
    throw new PreconditionFailedException("Table "+database.escapeTableName(getCatalogName(), getSchemaName(), getTableName())+" does not exist", changeLog, this);
}
```

It always returns false and throws PreconditionFailedException no matter if the table exists or not

## Steps To Reproduce
List the steps to reproduce the behavior.

* add changeset with precondition

```
databaseChangeLog:
- changeSet:
    id: 1613057211002-1
    preConditions:
      not:
        tableExists:
          tableName: test
    changes:
    - createTable:
        columns:
          - column:
              constraints:
                nullable: false
                primaryKey: true
                primaryKeyName: testPK
              name: uuid
              type: UUID
        tableName: test
```

**Comment by molivasdat** [comment]
Hi @stefanchiriac Thanks for writing up this issue and thanks for tracking it down to the line of code that is causing the problem.  That always helps.  If you feel inclined to write a PR that fixes this, that would be great.

**Comment by crizzis** [comment]
Unable to reproduce. Integration test added in https://github.com/liquibase/liquibase/pull/2538

**Comment by XDelphiGrl** [comment]
I am able to reproduce this bug on 4.8.0. Here is my changelog:

```
databaseChangeLog:
- changeSet:
    id: GH1712-1
    author: liquibase
    preConditions:
      not:
        tableExists:
          tableName: gh1712_tbl
    changes:
    - createTable:
        columns:
          - column:
              constraints:
                nullable: false
                primaryKey: true
                primaryKeyName: gh1712_pk
              name: uuid
              type: UUID
        tableName: gh1712_tbl
        
- changeSet:
    id: GH1712-2
    author: liquibase
    preConditions:
      not:
        tableExists:
          tableName: gh1712a_tbl
    changes:
    - createTable:
        columns:
          - column:
              constraints:
                nullable: false
                primaryKey: true
                primaryKeyName: gh1712a_pk
              name: uuid
              type: UUID
        tableName: gh1712a_tbl
        
- changeSet:
    id: GH1712-3
    author: liquibase
    preConditions:
      onFail: WARN
      not:
        tableExists:
          tableName: gh1712a_tbl
    changes:
    - createTable:
        columns:
          - column:
              constraints:
                nullable: false
                primaryKey: true
                primaryKeyName: gh1712b_pk
              name: uuid
              type: UUID
        tableName: gh1712b_tbl
```

At the beginning of my test, my postgres instance has none of these tables. When I run update, I expect the preconditions to pass and the tables created. Instead, I see a failure for the precondition for changeset `GH1712-3`.  

**Error Message from update Command**
```
Liquibase Version: 4.8.0
Liquibase Pro 4.8.0 by Liquibase licensed to customersuccess until Sun Jun 26 23:59:59 CDT 2022
Running Changeset: GH1712-changelog.yaml::GH1712-1::liquibase
Running Changeset: GH1712-changelog.yaml::GH1712-2::liquibase
Running Changeset: GH1712-changelog.yaml::GH1712-3::liquibase
WARNING: Executing GH1712-changelog.yaml::GH1712-3::liquibase despite precondition failure due to onFail='WARN':
      1 preconditions failed
     GH1712-changelog.yaml : Not precondition failed

Liquibase command 'update' was executed successfully.
```
Given that `gh1712a_tbl` exists at the time changeset `GH1712-3::liquibase` runs, the precondition should pass.

I'm going to try the same test on the branch where the new uniqueConstraintExists precondition is added; perhaps I get a different result there. 

CC @nvoxland @crizzis
