### ISSUE TITLE
Sequence create/alter does not set CacheSize for mssql

### ISSUE THREAD

**Issue by uwe42** [liquibase/liquibase#1775]
## Environment

**Liquibase Integration & Version**: spring boot 2.4.2

**Database Vendor & Version**: mssql

**Operating System Type & Version**: all

## Description

Sequence create/alter should set the `CacheSize` for all databases not only for oracle or Postgres (as described in the documentation).

https://docs.liquibase.com/change-types/community/alter-sequence.html

https://github.com/liquibase/liquibase/blob/43ed0e54adedc5f12c7933b998550e777d9b683d/liquibase-core/src/main/java/liquibase/sqlgenerator/core/AlterSequenceGenerator.java#L75

https://github.com/liquibase/liquibase/blob/43ed0e54adedc5f12c7933b998550e777d9b683d/liquibase-core/src/main/java/liquibase/sqlgenerator/core/CreateSequenceGenerator.java#L85

## Steps To Reproduce

List the steps to reproduce the behavior.
- Create a sequence with cacheSize for mssql. the sequence cacheSize will be ignored

```yaml
- changeSet:
    id: 53
    author: me
    changes:
    - createSequence:
        cacheSize: 1
        cycle: false
        incrementBy: 1
        maxValue: 9223372036854775807
        minValue: 1000
        sequenceName: test_sequence
        startValue: 1000

- changeSet:
    id: 54
    author: me
    changes:
      - alterSequence:
          cacheSize: 2
          sequenceName: test_sequence
```
