### ISSUE TITLE
PostgresDatabase should ignroe addPrimeryKey clustered false

### ISSUE THREAD

**Issue by uwe42** [liquibase/liquibase#1779]
## Environment
**Liquibase Integration & Version**: spring boot 2.4.2

**Database Vendor & Version**: postgresql

**Operating System Type & Version**: all

## Description
The [documentation ](https://docs.liquibase.com/change-types/community/add-primary-key.html) states that clustered is supported by all dbms. 

Not all databases support clustered primary keys, but Postgresql is one that does. The code to set the primary key as clustered exists in addPrimaryKey, but the validation check blocks it from being run. The validation also fails if clustered is set to "false".

## Steps To Reproduce
```yaml
- changeSet:
    id: 1-pkey
    author: me
    changes:
    - addPrimaryKey:
        tableName: testTable
        columnNames: id
        constraintName: testTable_pkey
        clustered: false
```

## Actual Behavior
```
liquibase.exception.ValidationFailedException: Validation Failed:
     1 changes have validation failures
          clustered is not allowed on postgresql [...]
```

## Expected/Desired Behavior
* Running 'liquibase update' should run without failure and create the primary key as clustered or not depending on the clustered argument
