### ISSUE TITLE
Liquibase Datbase Change Log Identity is bad and should be changed.

### ISSUE THREAD

**Issue by cbegin** [liquibase/liquibase#1787]
## Environment

**Liquibase Version**: ALL
**Liquibase Integration & Version**: ALL
**Liquibase Extension(s) & Version**: ALL
**Database Vendor & Version**: ALL
**Operating System Type & Version**: ALL

## Description

I've been an avid supporter and user of Liquibase for well over a decade. And to date, its means of identifying change log entries makes no sense, and is detrimental to the product. 

* Using ID, Author and Filename is borderline wrong on many levels (described below)
* Having no primary key on the databasechangelog table is bad practice and breaks some databases (Galera cluster)

The changes should be identified by the ID alone, and it should be a primary key on the databasechangelog table. 

This issue has most recently become higher priority for us, since we're trying to change some standards. As it stands, we need to "migrate our migrations" because of the rigidity of Liquibase's change log identity. 

## Rationale

* Currently it's possible to have duplicate IDs, which makes no sense, especially in a collaborative environment. Two developers could choose the same ID (high chance if semantic version practices are in use), but be different authors and/or filenames. It's just confusing and bad.

* Using author as an partial identifier is inflexible, as sometimes peoples' names change (marriage etc), or email addresses change if a company chooses to use that instead of just an arbitrary string (e.g. sometimes when contractors become full-time employees, etc). Or some companies may choose to use a team email as the author, which could change with a reorg. 

* Using the filename as an identifier is probably the worst of all, considering that one may want to change the company standard. While there is an attribute I can set to override this, it's entirely tedious and makes no sense. The filename should have no bearing on the identity of the migration, and quite frankly, that column isn't even necessary in the table at all. The content is what matters, and the ID should be the only identifier. 

* Even more ludicrous is that the filename isn't consistently relative to the changelog index. Instead, it is based on how the initially run file is passed to Liquibase. That is absolutely insane from a maintenance perspective. Dealing with 10 year old repositories and trying to change standards becomes very difficult.

We have hundreds of production databases using Liquibase, and hundreds of Liquibase changelog files. Liquibase's current approach does not scale, and it does not age well. We've gone as far as to write a preprocessor just to "correct" filename columns and keep them consistent, and in the past we've even added a primary key to the ID column just to protect against accidental duplication (or to make the table compatible with Galera clusters).

## Actual Behavior

Liquibase incorrectly identifies migrations as unique simply based on how the root changelog file was passed to liquibase. It will then erroneously try to rerun all migrations. 

## Expected/Desired Behavior

Because this would affect backward compatibility, I don't expect you to change this default behavior. So, I propose the following:

* Add a system property that will enable this new behavior for anyone cases where Liquibase's current behavior is inappropriate. 
* When enabled:
  * Liquibase will add a primary key to the databasechangelog ID column,
  * Liquibase will only identify migrations by the ID column exclusively, and will ignore the author and filename columns, tracked only for auditing purposes only,
  * Liquibase will set the filename column as a path and filename relative to the changelog index itself (i.e. based on the relative locations of the files in the changelog index,
  * As a bonus, all changelog index file references should be relative by default, so that we don't have to set the relative attribute on every single element, every single time. 
  
  Doing this will make Liquibase better, and I hope you seriously consider it.

**Comment by mariochampion** [comment]
hey @cbegin -- thanks for the thoughts. That is a pretty big change, and not without good reasons, for sure. But yea, pretty bold plan worth digging into. 

You have a lot of info, which I love, and maybe we can chat directly so I can get a clearer picture of use cases, biggest problems/solutions, etc. If you re up for that, please check https://calendly.com/liquibase/product-feedback and schedule some time. It is a good way to get a jump-start on such a big idea.

(If not, no worries, we can work thru ideas here, too)
thanks! 
Mario
(product manager)

**Comment by cbegin** [comment]
Thanks  @mariochampion, I'd love to walk you through the chaos this caused for us. When dealing with databases, I feel that data safety has to be at the very top of the priority list. Booked you in for Monday

**Comment by felixdesouza** [comment]
Any update on this? I ran liquibase separately via the cli with a different file name and was surprised to see that the same content along with ids would not be marked as applied (when run via spring) based on the fact that the path is different. It makes importing to liquibase a bit tricky.

**Comment by runkelstein** [comment]
I gotta say using the filename as an identity can lead to strange issues during production use.

Just to give you an example, I just ran into an issue because I was executing"mvn liquibase:update" on the command line and then later I did run liquibase:update by spring.

Because when running update , liquibase compares the filenames of the changesets,
and somehow recognizes that "classpath:changelogs/ChangeLog.xml" and "changelogs/ChangeLog.xml" mean the same thing (so it ignores classpath)
but does not recognize "src/main/resources/changelogs/ChangeLog.xml" and "changelogs/ChangeLog.xml" or "classpath:changelogs/ChangeLog.xml".

I had to debug liquibase to find that issue.
So in order to have reliable and comparable results when running liquibase from the command line
or while booting up the server, its better to always reference the relative path

This is the culprit code which handles the comparison in RanChangeSet.java:
`    public boolean isSameAs(ChangeSet changeSet) {
        return this.getChangeLog().replace('\\', '/').replaceFirst("^classpath:", "").equalsIgnoreCase(changeSet.getFilePath().replace('\\', '/').replaceFirst("^classpath:", ""))
                && this.getId().equalsIgnoreCase(changeSet.getId())
                && this.getAuthor().equalsIgnoreCase(changeSet.getAuthor());
    }`
    
 As you can see it only eliminates the issue with "classpath".
I dont know if this warrants creating a new issue or if this is the right place here to address it.

**Comment by djechelon** [comment]
I ran into this issue when switching from Ansible to Azure Pipelines.

It's not Ansible's fault, but our old Ansible script used to

```
  - name: Copy liquibase db-dati folder
    copy:
      src: "liquibase/db-dati"
      dest: "/opt/liquibase/tracking"
      owner: "{{ t_user }}"
      group: "{{ t_user }}"
      mode: 0660
    become: yes

  - name: Copy liquibase-metadati.properties
    template:
      src: liquibase-metadati.properties.j2
      dest: "/opt/liquibase/tracking/liquibase-metadati.properties"
      mode: 0660
      owner: "{{ t_user }}"
      group: "{{ t_user }}"
    become: yes

  - name: Copy liquibase-dati.properties
    template:
      src: liquibase-dati.properties.j2
      dest: "/opt/liquibase/tracking/liquibase-dati.properties"
      mode: 0660
      owner: "{{ t_user }}"
      group: "{{ t_user }}"
    become: yes

  - name: liquibase update db metadati
    shell: cd /opt/liquibase/tracking && /opt/liquibase/liquibase --defaultsFile=/opt/liquibase/tracking/liquibase-metadati.properties --changeLogFile=/opt/liquibase/tracking/db-metadati/changelog-master.xml update
    become: yes

  - name: liquibase update db dati
    shell: cd /opt/liquibase/tracking && /opt/liquibase/liquibase --defaultsFile=/opt/liquibase/tracking/liquibase-dati.properties --changeLogFile=/opt/liquibase/tracking/db-dati/changelog-master.xml update
    become: yes
```

Basically, it copied files under `/opt/liquibase` and ran Liquibase.

I created a pipeline from scratch with new tools, and on a blank machine. I had no reason to copy files to system folders, so I ran Liuibase from the pipeline workspace. And, by the way, Liquibase is now installed under `/usr/local/liquibase`

I found that Liquibase tries to run again old migration scripts. According to the command line I either found
- /opt/liquibase/tracking/db-metadati/versions/master.xml
- versions/master.xml

It means that Liquibase uses the (absolute) path of the changelog instead of a file-location-agnostic identifier.
