### ISSUE TITLE
Table and column names are not quoted in REFERENCES statements when `constraints` are defined using `references`

### ISSUE THREAD

**Issue by bogdanb** [liquibase/liquibase#1810]
## Environment
**Liquibase Version**: 4.3.4 (also happens with 3.10.3)

**Liquibase Integration & Version**: Spring Boot 2.4.2 (but I don’t think it matters)

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: Amazon Aurora in MySQL mode (but it would probably happen with any MySQL)

**Operating System Type & Version**: Ubuntu 20.10

## Description
If you define a table which contains a foreign key, and you define the constraint using the `references` attribute, neither the table nor the column names are ever quoted when Liquibase generates SQL statements. The `references` string is taken as-is, and only prefaced with the database name.

For example, if you have the following YAML definition:

```yaml
- createTable:
  tableName: test_table
  columns:
    - column:
      name: foreign_key
      type: varchar(255)
      constraints:
        foreignKeyName: fk_target_key
        references: target_table(key)
```

Then Liquibase will generate an SQL statement as follows:

```sql
    CREATE TABLE db_name.test_table (
    	`key` VARCHAR(255) NOT NULL,
    	CONSTRAINT fk_target_key
    		FOREIGN KEY (`key`) 
    		REFERENCES db_name.target_table(key))
```

Note that `key` is not quoted on the last line, even though that word _is_ quoted in the other places (because it is a reserved word).

However, if the definition were instead:

```yaml
- createTable:
  tableName: test_table
  columns:
    - column:
      name: foreign_key
      type: varchar(255)
      constraints:
        foreignKeyName: fk_target_key
        referencedTableName: target_table
        referencedColumnNames: key
```

Then the correct SQL will be generated; the last line will become:

```sql
    		REFERENCES db_name.target_table(`key`))
```

Note that `objectQuotingStrategy: QUOTE_ALL_OBJECTS` does not affect this behavior. When `references` is used, the exact string used as a value is returned, leaving both the table and the column name(s) unquoted (even though everything else is quoted), while if `referencedTableName` / `referencedColumnNames` are used, then they _are_ quoted.

(This issue description was changed radically when I realized it was the `references` attribute that caused the issue. Not sure if the Jira bug will be updated appropriately.)
