### ISSUE TITLE
Label expression using AND/OR does not work with inherited labels

### ISSUE THREAD

**Issue by dwhite996** [liquibase/liquibase#1813]
When a label expression is provided that uses AND or OR, the label filter does not correctly handle inherited labels.

Example:

* master.xml:
`<include labels="a" file="include.xml"/>`
* include.xml:
    `<changeSet labels="b" ... />`
* label expression from CLI:
    `--labels="a and b"`

Line 45 of LabelChangeSetFilter.java treats inherited and normal labels as entirely separate and for the above example executes the following check which will never be true:
    `((a and b) matches b) and ((a and b) matches a)`

From the documentation I think that it should be combining both normal and inherited labels into a single collection and matching the label expression against that collection.

https://github.com/liquibase/liquibase/blob/256675bca43a089e32c940e10ed8ed7a5f9d66f6/liquibase-core/src/main/java/liquibase/changelog/filter/LabelChangeSetFilter.java#L45

**Comment by molivasdat** [comment]
Hi @dwhite996 Thanks for writing up this issue.  We will add it to the list of issues that we are processing.

**Comment by juriad** [comment]
I am also hitting issue. I have change log for integration tests:
```
databaseChangeLog:
  - include:
      file: db.changelog-master.yaml
      relativeToChangelogFile: true
      labels: risk
  - include:
      file: db.changelog-integration-um.yaml
      relativeToChangelogFile: true
      labels: integration,um
  - include:
      file: db.changelog-integration-trading.yaml
      relativeToChangelogFile: true
      labels: integration,trading
  - include:
      file: db.changelog-integration-risk.yaml
      relativeToChangelogFile: true
      labels: integration,risk
```
Each of the included changelogs has changesets labeled either `data` or `schema`.
My label filter is: `schema OR ( data AND integration )`, which currently matches nothing.

In accordance with documentation (https://docs.liquibase.com/concepts/changelogs/attributes/labels.html):
> You can specify the labels attribute in [include](https://docs.liquibase.com/change-types/include.html) and [includeAll](https://docs.liquibase.com/change-types/includeall.html) tags. If specified, the given label is added to all changesets in the included file(s).

The `LabelChangeSetFilter` must not consider the inherited labels independently but all at once.

Since there is this MR (https://github.com/liquibase/liquibase/pull/5477) with refactoring, it could be a good time to fix this too.
