### ISSUE TITLE
Liquibase needs to double quote table names when generating foreign key references for Postgresql

### ISSUE THREAD

**Issue by kenyee** [liquibase/liquibase#1838]
## Environment
Spring Boot

**Liquibase Version**:
 3.10.3

**Liquibase Integration & Version**:
 Maven

**Liquibase Extension(s) & Version**: 
None

**Database Vendor & Version**:
Postgres 13.2

**Operating System Type & Version**:
can repro in OSX Big Sur...server environment is CloudSQL w/ Postgres via JDBC driver

## Description
A clear and concise description of the issue being addressed.

* Describe the actual problematic behavior.
* Ensure private information is redacted.

## Steps To Reproduce
Use the following YAML config:

```
databaseChangeLog:
  - changeSet:
      id: create-initial-tables
      author: kyee
      preConditions:
        - onFail: MARK_RAN
          not:
            tableExists:
              tableName: Admin
      changes:
        - createTable:
            tableName: Admin
            columns:
              - column:
                  name: email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: admin_pkey
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: super_admin
                  type: BOOLEAN
                  constraints:
                    nullable: false
        - createIndex:
            tableName: Admin
            columns:
              - column:
                  name: email
              - column:
                  name: super_admin
            indexName: index_super_admin
        - createTable:
            tableName: Repo
            columns:
              - column:
                  name: name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: repo_pkey
              - column:
                  name: description
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: git_base_url
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: config_data
                  type: JSONB
        - createTable:
            tableName: Admin_Repo
            columns:
              - column:
                  name: admin_email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    foreignKeyName: fk_adminrepo_admin
                    references: Admin(email)
                    onDelete: CASCADE
              - column:
                  name: repo_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    foreignKeyName: fk_adminrepo_repo
                    references: Repo(name)
                    onDelete: CASCADE
        - createIndex:
            tableName: Admin_Repo
            columns:
              - column:
                  name: admin_email
              - column:
                  name: repo_name
            indexName: index_admin_repo
        - createTable:
            tableName: AccessKey
            columns:
              - column:
                  name: id
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: accesskey_pkey
              - column:
                  name: repo_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: description
                  type: VARCHAR(255)
              - column:
                  name: hashed_key
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
              - column:
                  name: permissions
                  type: VARCHAR
                  constraints:
                    nullable: false
        - createIndex:
            tableName: AccessKey
            columns:
              - column:
                  name: repo_name
              - column:
                  name: hashed_key
            indexName: index_accesskey
      rollback:
        - dropTable:
            tableName: Admin_Repo
        - dropTable:
            tableName: Admin
        - dropTable:
            tableName: Repo
        - dropTable:
            tableName: AccessKey
```

## Actual Behavior
Fails executing the join table because it's missing quotes:

```
2021-05-11 16:35:56.054 ERROR 47760 --- [           main] liquibase.changelog.ChangeSet            : Change Set db/changelog/create-initial-tables-changelog-1.yaml::create-initial-tables::kyee failed.  Error: ERROR: relation "public.repo" does not exist [Failed SQL: (0) CREATE TABLE public."Admin_Repo" (admin_email VARCHAR(255) NOT NULL, repo_name VARCHAR(255) NOT NULL, CONSTRAINT fk_adminrepo_repo FOREIGN KEY (repo_name) REFERENCES public.Repo(name), CONSTRAINT fk_adminrepo_admin FOREIGN KEY (admin_email) REFERENCES public.Admin(email))]
```

## Expected/Desired Behavior
Should include quotes for all table names emitted for Postgres driver.
Apparently Postgres wants table names to be quoted all the time if you use a schema.

**Comment by molivasdat** [comment]
I think the issue may be in the way you are creating the foreign keys
Try this instead of using references Admin(email)
and Repo(name)
```
              - column:
                  name: admin_email
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    foreignKeyName: fk_adminrepo_admin
                    referencedColumnNames: email
                    referencedTableName: Admin
                    onDelete: CASCADE
              - column:
                  name: repo_name
                  type: VARCHAR(255)
                  constraints:
                    nullable: false
                    foreignKeyName: fk_adminrepo_repo
                    referencedColumnNames: name
                    referencedTableName: Repo
                    onDelete: CASCADE
```
**referencedColumnNames: email
referencedTableName: Admin**

**referencedColumnNames: name
   referencedTableName: Repo**
   
   This worked for me when I update your yaml file.
   
   
   AND if you need to quote all objects, you can use this too.
   ```
   databaseChangeLog:
  - objectQuotingStrategy: QUOTE_ALL_OBJECTS
  - changeSet:
  ```
