### ISSUE TITLE
Snapshots should include duplicate constraints that are named differently.

### ISSUE THREAD

**Issue by felixdesouza** [liquibase/liquibase#1998]
## Environment

**Liquibase Version**: 4.4.0

**Liquibase Integration & Version**: any

**Liquibase Extension(s) & Version**: N/A

**Database Vendor & Version**: Postgres

**Operating System Type & Version**: any

## Description

A clear and concise description of the issue being addressed.
- Describe the actual problematic behavior.
- Ensure private information is redacted.

For reasons that are before my time, the database I'm trying to normalise/clean sometimes has duplicate constraints that are named slightly differently. I think related to Spring boot/hibernate jpa upgrades. I tried to do the following workflow:
1. snapshot a clean desired state
2. calculate diff from the above offline snapshot
3. apply diff to normalise

However it would fail because there were still references. When I dug in, it turned out that some constraints were left behind and not detected. Digging in to the code, when we diff the database to a snapshot, we snapshot the database first. However, snapshots treat the effect of the constraint as equality as opposed to the name. Which means that when I apply the diff, I'm only taking away one constraint as opposed to all. That aside, semantically, it means the snapshot is not a snapshot as it doesn't list all the objects in the database.

I've only picked up on `Foreign Key` and `UniqueKey`, but their `equals` methods do not consider them different if their name is different. Perhaps a fix would be to have two methods:
* `equals` - true definition of equality
* `isEquivalent` - which is the current definition of equality
When generating a changelog, I imagine you'd want to use the equivalence. When generating a `diffChangelog`, you'd want to use the `.equals`.

## Steps To Reproduce
1. Seed the database like so:
```sql
CREATE TABLE example (
  id BIGINT,
  CONSTRAINT pkey PRIMARY KEY (id)
);
CREATE TABLE example_ref (
  id BIGINT, 
  fk BIGINT,
  CONSTRAINT ref_pk PRIMARY KEY (id),
  CONSTRAINT fk_example FOREIGN KEY(fk) references example(id),
  CONSTRAINT fk_example_duplicated FOREIGN KEY(fk) references example(id)
);
```
2. `liquibase <...> snapshot`

<details>
<summary>Generated Snapshot file</summary>

```yaml

snapshot:
  created: 2021-07-22T14:22:32.074
  database:
    productVersion: 9.6.22
    shortName: postgresql
    majorVersion: '9'
    minorVersion: '6'
    user: test
    productName: PostgreSQL
    url: jdbc:postgresql://localhost:5432/test
  objects:
    liquibase.structure.core.Catalog:
    - catalog:
        default: true
        name: test
        snapshotId: 2aa7100
    liquibase.structure.core.Column:
    - column:
        name: fk
        nullable: true
        order: 2!{java.lang.Integer}
        relation: liquibase.structure.core.Table#2aa7102
        snapshotId: 2aa7105
        type:
          characterOctetLength: 19!{java.lang.Integer}
          columnSizeUnit: BYTE!{liquibase.structure.core.DataType$ColumnSizeUnit}
          dataTypeId: -5!{java.lang.Integer}
          radix: 10!{java.lang.Integer}
          typeName: int8
    - column:
        name: id
        nullable: false
        order: 1!{java.lang.Integer}
        relation: liquibase.structure.core.Table#2aa7108
        snapshotId: 2aa7107
        type:
          characterOctetLength: 19!{java.lang.Integer}
          columnSizeUnit: BYTE!{liquibase.structure.core.DataType$ColumnSizeUnit}
          dataTypeId: -5!{java.lang.Integer}
          radix: 10!{java.lang.Integer}
          typeName: int8
    - column:
        name: id
        nullable: false
        order: 1!{java.lang.Integer}
        relation: liquibase.structure.core.Table#2aa7102
        snapshotId: 2aa7104
        type:
          characterOctetLength: 19!{java.lang.Integer}
          columnSizeUnit: BYTE!{liquibase.structure.core.DataType$ColumnSizeUnit}
          dataTypeId: -5!{java.lang.Integer}
          radix: 10!{java.lang.Integer}
          typeName: int8
    liquibase.structure.core.ForeignKey:
    - foreignKey:
        deferrable: false
        deleteRule: importedKeyNoAction!{liquibase.structure.core.ForeignKeyConstraintType}
        foreignKeyColumns:
        - liquibase.structure.core.Column#2aa7105
        foreignKeyTable: liquibase.structure.core.Table#2aa7102
        initiallyDeferred: false
        name: fk_example
        primaryKeyColumns:
        - liquibase.structure.core.Column#2aa7107
        primaryKeyTable: liquibase.structure.core.Table#2aa7108
        snapshotId: 2aa7106
        updateRule: importedKeyNoAction!{liquibase.structure.core.ForeignKeyConstraintType}
    liquibase.structure.core.Index:
    - index:
        columns:
        - liquibase.structure.core.Column#2aa7107
        name: pkey
        snapshotId: 2aa7109
        table: liquibase.structure.core.Table#2aa7108
        unique: true
    - index:
        columns:
        - liquibase.structure.core.Column#2aa7104
        name: ref_pk
        snapshotId: 2aa7103
        table: liquibase.structure.core.Table#2aa7102
        unique: true
    liquibase.structure.core.PrimaryKey:
    - primaryKey:
        backingIndex: liquibase.structure.core.Index#2aa7109
        columns:
        - liquibase.structure.core.Column#2aa7107
        name: pkey
        snapshotId: 2aa7110
        table: liquibase.structure.core.Table#2aa7108
    - primaryKey:
        backingIndex: liquibase.structure.core.Index#2aa7103
        columns:
        - liquibase.structure.core.Column#2aa7104
        name: ref_pk
        snapshotId: 2aa7111
        table: liquibase.structure.core.Table#2aa7102
    liquibase.structure.core.Schema:
    - schema:
        catalog: liquibase.structure.core.Catalog#2aa7100
        default: true
        name: public
        snapshotId: 2aa7101
    liquibase.structure.core.Table:
    - table:
        columns:
        - liquibase.structure.core.Column#2aa7107
        default_tablespace: false
        indexes:
        - liquibase.structure.core.Index#2aa7109
        name: example
        primaryKey: liquibase.structure.core.PrimaryKey#2aa7110
        schema: liquibase.structure.core.Schema#2aa7101
        snapshotId: 2aa7108
    - table:
        columns:
        - liquibase.structure.core.Column#2aa7104
        - liquibase.structure.core.Column#2aa7105
        default_tablespace: false
        indexes:
        - liquibase.structure.core.Index#2aa7103
        name: example_ref
        outgoingForeignKeys:
        - liquibase.structure.core.ForeignKey#2aa7106
        primaryKey: liquibase.structure.core.PrimaryKey#2aa7111
        schema: liquibase.structure.core.Schema#2aa7101
        snapshotId: 2aa7102
  snapshotControl:
    snapshotControl:
      includedType:
      - liquibase.structure.core.Catalog
      - liquibase.structure.core.Column
      - liquibase.structure.core.ForeignKey
      - liquibase.structure.core.Index
      - liquibase.structure.core.PrimaryKey
      - liquibase.structure.core.Schema
      - liquibase.structure.core.Sequence
      - liquibase.structure.core.Table
      - liquibase.structure.core.UniqueConstraint
      - liquibase.structure.core.View
```

</details>

As you can see, there is no entry for `fk_example_duplicated`.

Whilst debugging I thought maybe postgres was filtering it out when we call `Connection#getMetaData`, but upon inspection, all the foreign keys were present, and then I found the equals implementation.

## Actual Behavior
If there are multiple constraints that are equivalent except in name, then only the first constraint is shown in the snapshot.

## Expected/Desired Behavior
All foreign keys/constraints should exist in the snapshot, not just the first alias.
