### ISSUE TITLE
JSON operator '?' is incorrectly handled by liquibase in recent version

### ISSUE THREAD

**Issue by nowak-mariusz** [liquibase/liquibase#2032]
## Environment

**Liquibase Version**:
3.4.3

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
spring-boot

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
postgresql 10.12

**Operating System Type & Version**:

## Description
Just upgraded liquibase to 4.4.3 from 3.10.3. The migrations are failing because one of postgres' JSON operators is incorrectly parsed by liquibase.

## Steps To Reproduce
The migration query is similar to the following:

```
UPDATE table
SET json_column = some_other_json_value
WHERE json_column IS NOT NULL AND json_column::jsonb ? 'updateUserName'
```
Notice the '?' operator (question mark - valid JSON operator for postgres)
where the database claims it has received slightly different query (checked postgres logs using "log_statement=all" runtime option - notice the changed operator '?' into '$1')
```
UPDATE table
SET json_column = some_other_json_value
WHERE json_column IS NOT NULL AND json_column::jsonb $1 'updateUserName'
```

## Actual Behavior
The migration fails with an error:
```
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [com/lmig/forge/liquibase/CustomLiquibaseAutoConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for change set <redacted>:
     Reason: liquibase.exception.DatabaseException: ERROR: syntax error at or near "$1"
```

## Expected/Desired Behavior
This was a perfectly valid migration in 3.10.3, I expect it to be fixed.

## Additional Context
The changeset is defined using sqlFile in the yml configuration:
```
  - changeSet:
      id: <redacted>
      author: <redacted>
      context: prod
      changes:
        - sqlFile:
            path: <redacted>
            relativeToChangelogFile: true
            splitStatements: false
```

For me it seems like the operator is accidentally treated as a prepared statement parameter, isn't it?
