### ISSUE TITLE
Can't drop mixed case primary key constraint in postgres with liquibase 4.4.0+

### ISSUE THREAD

**Issue by cdolin** [liquibase/liquibase#2062]
## Environment
**Liquibase Version**: 4.4.0+

**Liquibase Integration & Version**: gradle

**Liquibase Extension(s) & Version**:  none

**Database Vendor & Version**: Postgres 13

**Operating System Type & Version**:  Ubuntu 20.04

## Description
Liquibase creates a mixed case primary key constraint name when the column name is capitalized. However it does not use quotes in a subsequent drop primary key command and the new changelog cannot be applied.

## Steps To Reproduce
Here is an example changelog yaml file

```
  - changeSet:
      id: 1
      author: me
      changes:
        - createTable:
            tableName: MY_TABLE
            columns:
              - column:
                  name: MY_PK_FIELD
                  type: varchar(100)
                  constraints:
                    nullable: false
                    primaryKey: true
  - changeSet:
      id: 2
      author: me
      changes:
        - dropPrimaryKey:
            tableName: MY_TABLE
            dropIndex: true
```

Try to seed a postgres db with this changelog using a `new Liquibase(String changeLogFile, ResourceAccessor resourceAccessor, Database database)`

## Actual Behavior
This changelog will generate a constraint name MY_PK_FIELD_pkey which can be verified by querying the INFORMATION_SCHEMA.TABLE_CONSTRAINTS table. However the 2nd changeset fails to run with the following error

```
 ERROR: constraint "my_pk_field_pkey" of relation "my_table" does not exist
 Where: SQL statement "alter table public.my_table drop constraint MY_PK_FIELD_pkey"
```

 In previous versions of liquibase (4.3.5), the generated pk constraint name was a lowercased my_pk_field_pkey (according to the INFORMATION_SCHEMA.TABLE_CONSTRAINTS table) and the primary key could be dropped via dropPrimaryKey.

I believe this [PR](https://github.com/liquibase/liquibase/pull/1514/files#diff-251a26e86b87566e522b403e6719fcd0b16e1408ff91029c37ad37eabcfc80d0) changed the behavior for generating the constraint name  because the tableName is no longer uppercased for consistent casing. If the command to create a primary key constraint cares about case, then I think the command to drop a primary key constraint should also care about case-- for example with quotes around the constraint name like `alter table public.my_table drop constraint "MY_PK_FIELD_pkey"`. I ran this command manually in a test environment and it successfully modified the table.

## Expected/Desired Behavior
The above changelog should be applied successfully which would allow projects with similar changelogs to safely upgrade their liquibase dependencies and allow clients to drop primary key constraints from postgres databases.

## Additional Context

┆Issue is synchronized with this [Jira Story](https://datical.atlassian.net/browse/LB-2127) by [Unito](https://www.unito.io)
