### ISSUE TITLE
YamlChangelogSerializer produces wrongly formed changelog if changeset contains rollback changes (Yaml and JSON)

### ISSUE THREAD

**Issue by georg2902** [liquibase/liquibase#2084]
## Environment

**Liquibase Version**: 4.4.3

**Liquibase Integration & Version**: liquibase-core lib 4.4.3

**Database Vendor & Version**: MySQL 8.0

**Operating System Type & Version**: Ubuntu 20.04

## Description

The `YamlChangelogSerializer` produces  a wrongly formed changelog file if a changeset contains `RollbackChanges`. 

## Steps To Reproduce
Running the following Java Code:
```Java
        DatabaseChangeLog changeLog = new DatabaseChangeLog();
        ChangeSet changeSet = new ChangeSet(UUID.randomUUID().toString(), "author", false, false, "", "test", "mysql", changeLog);
        changeSet.addRollbackChange(new EmptyChange());
        changeLog.addChangeSet(changeSet);

        YamlChangeLogSerializer serializer = new YamlChangeLogSerializer();
        OutputStream outputStream = new FileOutputStream("changelog-with-rollback.yaml");
        serializer.write(changeLog.getChangeSets(), outputStream);
        outputStream.close();
```
## Actual Behavior
Produces a changelog file with the following content:
```yaml
databaseChangeLog:
- changeSet:
    id: 96ad97c9-7981-4011-9a41-a9bba86f9c27
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      rollback:
        changes:
        - empty: {}
```
## Expected/Desired Behavior
Looking closely to the rollback section I don't expect the `rollback` statement twice and neither the `changes` statement inside. So in my opinion a well formed changelog should look like this:
```yaml
databaseChangeLog:
- changeSet:
    id: 96ad97c9-7981-4011-9a41-a9bba86f9c27
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      - empty: {}
```
## Additional Context
in a more complex example I created multiple changelogs and include them together in one changelog file. One of the child changelogs looks like this:
```yaml
databaseChangeLog:
- changeSet:
    id: 5e70305c-17da-481b-b247-1aab3ec338ce
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      rollback:
        changes:
        - dropColumn:
            columnName: paymentMethod
            tableName: customers
    changes:
    - addColumn:
        columns:
        - column:
            name: paymentMethod
            type: varchar(50)
        tableName: customers
```
After parsing it and serializing it again I ended up with this changelog:
```yaml
databaseChangeLog:
- changeSet:
    id: 5e70305c-17da-481b-b247-1aab3ec338ce
    author: author
    context: test
    dbms: mysql
    objectQuotingStrategy: LEGACY
    rollback:
      rollback:
        changes:
        - empty: {}
    changes:
    - addColumn:
        columns:
        - column:
            name: paymentMethod
            type: varchar(50)
        tableName: customers
```
where you can see, that the rollback section is completely wrong, because it parsed the already wrongly serialized rollback section as an empty change.
