### ISSUE TITLE
`catalogName` does nothing for PostgreSQL

### ISSUE THREAD

**Issue by huuff** [liquibase/liquibase#2253]
## Environment

**Liquibase Version**:  4.4.3

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: PostgreSQL

**Operating System Type & Version**: Linux 5.10

## Description
Using `catalogName` in `createTable` and other change types does not affect the output 

## Steps To Reproduce
With the following `liquibase.properties`:

```
driver=org.postgresql.Driver
url=offline:postgresql
changeLogFile=./databasechangelog.yaml
liquibase.hub.mode=off
```

And the following `databasechangelog.yaml`
```yaml
databaseChangeLog:
  - changeSet:
      id: 1
      author: unknown
      changes:
        - createTable:
            catalogName: catalog
            schemaName: public
            tableName: test_table
            columns:
              - column:
                  name: test_column
                  type: integer
```

## Actual Behavior
When running `liquibase updateSQL` it produces:
```sql
-- Changeset ./databasechangelog.yaml::1::unknown
CREATE TABLE public.test_table (test_column INTEGER);
```

## Expected/Desired Behavior
It should produce
```sql
-- Changeset ./databasechangelog.yaml::1::unknown
CREATE TABLE catalog.public.test_table (test_column INTEGER);
```
