### ISSUE TITLE
SkipMissingChangelogsSpringLiquibase

### ISSUE THREAD

**Issue by mhewedy** [liquibase/liquibase#2256]
We have a big multi-module maven project, that each module is independent in terms of everything starting from Liquibase files to the database schema to entity, service, controller layers ... etc.  But at end of the day, we have one main module that includes all such files as :

```
### db.changelog-master.yaml
databaseChangeLog:
  - include:
      file: classpath:db/changelog/module1.xml
  - include:
      file: classpath:db/changelog/module2.xml
.......
.......
```
The point is, in development-time, the developer doesn't need to load all modules (each module is a maven profile, so one can exclude modules easily by just enabling/disabling profiles belonging to his own module)

Everything goes fine until we started the app, and Liquibase starts to complain about missing Liquibase configuration files. 😢 

So to fix the issue we have to add our own [SkipMissingChangelogsSpringLiquibase.java](https://gist.github.com/mhewedy/39094729975d9d73d11afad82af55788) and use it to configure spring Liquibase bean.

We wished that time such a tolerated mechanism exists as part of Liquibase in order not to "hack" it. 

_So My question here is can we have this [Code ](https://gist.github.com/mhewedy/39094729975d9d73d11afad82af55788)part of Liquibase so as to minimize the customization we (and maybe others) doing?_  (I can submit the PR 😉 )
