### ISSUE TITLE
MySQL: Snapshot does not capture char/varcahr character set

### ISSUE THREAD

**Issue by nvoxland** [liquibase/liquibase#2338]
## Description

If a table has been created like:

```
create table test_table
(
    test_char    char(50) charset utf8mb4,
    test_varchar varchar(50) charset utf8mb4
);
```
then running `liquibase snapshot` returns only 
```
        test_table
            columns: 
                test_char
                    nullable: true
                    order: 1
                    type: CHAR(50 BYTE)
                test_varchar
                    nullable: true
                    order: 3
                    type: VARCHAR(50 BYTE)
```
with no mention of the charset.
