### ISSUE TITLE
latest liquibase blocks validation blocks running update on mysql

### ISSUE THREAD

**Issue by kmoore-regence** [liquibase/liquibase#2368]
## Environment

**Liquibase Version**: 4.7.0

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:

**Operating System Type & Version**:

## Description

A clear and concise description of the issue being addressed.
liquibase validator throws exception when running update to create clustered index on primary key using mysql db

## Steps To Reproduce
create changeset log setting clustered:true for primary key (like this)
        - addPrimaryKey:
            tableName: valueset
            clustered: true
            columnNames: code, set_name
            constraintName: pk_valueset
            validate: true

List the steps to reproduce the behavior.
using latest liquibase/liquibase image start container using changeset log similar to above
## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.
chp-liquibase_1  | ####################################################
chp-liquibase_1  | ##   _     _             _ _                      ##
chp-liquibase_1  | ##  | |   (_)           (_) |                     ##
chp-liquibase_1  | ##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
chp-liquibase_1  | ##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
chp-liquibase_1  | ##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
chp-liquibase_1  | ##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
chp-liquibase_1  | ##              | |                               ##
chp-liquibase_1  | ##              |_|                               ##
chp-liquibase_1  | ##                                                ##
chp-liquibase_1  | ##  Get documentation at docs.liquibase.com       ##
chp-liquibase_1  | ##  Get certified courses at learn.liquibase.com  ##
chp-liquibase_1  | ##  Free schema change activity reports at        ##
chp-liquibase_1  | ##      https://hub.liquibase.com                 ##
chp-liquibase_1  | ##                                                ##
chp-liquibase_1  | ####################################################
chp-liquibase_1  | Starting Liquibase at 20:32:12 (version 4.7.0 #1140 built at 2022-01-07 19:26+0000)
chp-liquibase_1  | Liquibase Version: 4.7.0
chp-liquibase_1  | Liquibase Community 4.7.0 by Liquibase
chp-liquibase_1  |
chp-liquibase_1  | Unexpected error running Liquibase: Validation Failed:
chp-liquibase_1  |      1 changes have validation failures
chp-liquibase_1  |           Cannot specify clustered=true on mysql, 
## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.

**Comment by kataggart** [comment]
Thanks for submitting this. @kmoore-regence can you confirm for me if you had previously been able to do this using another version? The title of your issue seems to indicate that you had been. Thanks.

**Comment by kmoore-regence** [comment]
using 4.4.3 of liquibase allowed the update to complete so its most likely a bug in the validation logic

**Comment by kmoore-regence** [comment]
i'm assuming whatever version that was previous to 4.7.0 also worked as this exception just started throwing in the last few days

**Comment by wfzelle** [comment]
We have the same issue on 4.5.0. An older changelog suddenly stopped working. The setting appears to be unnecessary though, so we are removing it to solve our issue that way.

**Comment by MalloD12** [comment]
I cannot reproduce this issue:

```
Liquibase Version: 4.15.0

Liquibase Integration & Version: CLI

Liquibase Extension(s) & Version:

Database Vendor & Version: MySQL 8.0.26

Operating System Type & Version: Mac OS 12.1
```
I have executed update command with below changelog: 

```
databaseChangeLog:
  - changeSet:
      id: 1
      author: dmallorga
      changes:
        - createTable:
            tableName: person
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
                    clustered: true
              - column:
                  name: firstname
                  type: varchar(50)
              - column:
                  name: lastname
                  type: varchar(50)
                  constraints:
                    nullable: false
              - column:
                  name: state
                  type: char(2)
```

and it was executed successfully:
<img width="565" alt="Screen Shot 2022-08-17 at 4 25 45 PM" src="https://user-images.githubusercontent.com/75833793/185225830-33268fd4-62cd-4276-968a-75ca32407754.png">
<img width="1400" alt="Screen Shot 2022-08-17 at 4 28 02 PM" src="https://user-images.githubusercontent.com/75833793/185226090-d5e1feaf-201a-4a26-8ac9-8122d7d7ad8c.png">
