### ISSUE TITLE
Invalid update SQL generated for HSQL database with different onlyUpdate values in InsertOrUpdateGeneratorHsql.java 

### ISSUE THREAD

**Issue by devorgpl** [liquibase/liquibase#2375]
## Environment
Liquibase: 4.4.3+, verified on 4.5.0
Database Vendor: HSQL

## Description
Introduced in PR #1563 
Invalid SQL generated for HSQL database in InsertOrUpdateGeneratorHsql.java
when onlyUpdate is "false"
Note: Found when trying to use:

```
  - changeSet:
      id: load-hex-field-data
      author: cyprian
      changes:
        - loadUpdateData:
            encoding: "UTF-8"
            file: "db/data/hex_fields.csv"
            onlyUpdate: "false"
            primaryKey: "id"
            quotchar: "'"
            separator: ","
            tableName: "hex_field"
```

* no need for table name in update part
* no where needed clause in update script

## Steps To Reproduce
changeset file:
```
  - changeSet:
      id: 1
      author: example
      changes:
        - createTable:
            tableName: "hex_field"
            columns:
              - column:
                  name: id
                  type: int
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: location_x
                  type: int
              - column:
                  name: location_y
                  type: int
              - column:
                  name: type
                  type: varchar(20)
  - changeSet:
      id: load-hex-field-data
      author: cyprian
      changes:
        - loadUpdateData:
            encoding: "UTF-8"
            file: "db/data/hex_fields.csv"
            onlyUpdate: "false"
            primaryKey: "id"
            quotchar: "'"
            separator: ","
            tableName: "hex_field"
```
CSV file (db/data/hex_fields.csv)
```
id,location_x,location_y,type
1, 1000, 1000,EMPTY
```

## Actual Behavior && Desired Behavior
when onlyUpdate: "false"
```
MERGE INTO hex_field USING (VALUES (1)) ON id = 1 WHEN NOT MATCHED THEN INSERT (id,location_x,location_y,type) VALUES (1, 1000, 1000,' ''EMPTY') WHEN MATCHED THEN UPDATE hex_field SET id = 1,location_x =  1000,location_y =  1000,type = ''EMPTY' WHERE id = 1]
```
should be
```
MERGE INTO hex_field USING (VALUES (1)) ON id = 1 WHEN NOT MATCHED THEN INSERT (id,location_x,location_y,type) VALUES (1, 1000, 1000,' ''EMPTY') WHEN MATCHED THEN UPDATE SET id = 1,location_x =  1000,location_y =  1000,type = 'EMPTY' ]
```
When onlyUpdate: "true" it works as expected and should be
```
UPDATE hex_field SET id = 1,location_x =  1000, location_y =  1000, type = 'EMPTY' WHERE id = '1'
```
