### ISSUE TITLE
Liquibase should ignore "clustered" on addPrimaryKey for h2

### ISSUE THREAD

**Issue by dhait** [liquibase/liquibase#2376]
**Liquibase Version**:
4.5.0

**Liquibase Integration & Version**: 
liquibase-core library

**Database Vendor & Version**:
h2

**Operating System Type & Version**:
All

## Description

When "clustered" is used in the addPrimaryKey change type, and the database is h2, Liquibase fails validation:

    Cannot specify clustered=true on h2

## Steps To Reproduce

```
databaseChangeLog:
  - changeSet:
      id: changeSet1
      author: david
      changes:
        -  addPrimaryKey:
             clustered:  true
             columnNames:  column1
             constraintName:  pk_column1
             tableName:  mytable
```

## Actual Behavior
    Cannot specify clustered=true on h2

## Expected/Desired Behavior
   Ignore the "clustered" tag like in postgres (https://github.com/liquibase/liquibase/pull/1880)
