### ISSUE TITLE
Liquibase 4.7.0 upgrade causing issue with table name

### ISSUE THREAD

**Issue by marceloverdijk** [liquibase/liquibase#2385]
I have a hobby project running on Spring Boot 2.7 snapshot which today upgraded from Liquibase 4.6.2 to 4.7.0.

With Liquibase 4.6.2 and H2 datasource the following changelog

```
databaseChangeLog:
  - changeSet:
      id: 1
      author: me
      changes:
        - createTable:
            tableName: user
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                    primaryKeyName: user_pk
              - ..
```

will create UPPERCASE tables in H2:

![image](https://user-images.githubusercontent.com/197004/150146687-13c81f5a-ef47-4191-bc26-c7ce1a8325fc.png)

In fact I never really paid attention to the uppercase/lowercase table/column name in the H2 console despite having them lowercase in the changelog.

Also a changelog like this (lowercase names) works:

```
        - insert:
            tableName: user_role
            columns:
              - column:
                  name: user_id
                  valueComputed: select id from user where username = 'foo_bar'
              - column:
                  name: role_name
                  value: ROLE_USER
```

Doing some manual queries in the H2 console work for these:

- `SELECT * FROM USER`
- `SELECT * FROM user`
- `SELECT * FROM "USER"`

but not for `SELECT * FROM "user"`

Now with upgrade to Liquibase 4.7.0 I see other behaviour with above setup.

The application won't start as the changelog with the `insert` fails now:

```
Reason: liquibase.exception.DatabaseException: Table "USER" not found; SQL statement:
INSERT INTO PUBLIC.user_role (user_id, role_name) VALUES (select id from user where username = 'foo_bar', 'ROLE_USER') [42102-200] [Failed SQL: (42102) INSERT INTO PUBLIC.user_role (user_id, role_name) VALUES (select id from user where username = 'foo_bar, 'ROLE_USER')]
```

Although "USER" (uppercase) is not used like that in the insert it still fails.

Now I probably should have not used the table name `user` as `USER` is a reserved word, so I can only blame myself ;-) but this might impact others as well...

In the Liquibase 4.7.0 [release notes](https://docs.liquibase.com/release-notes/home.html) I don't see anything noteworthy that changed that could explain this behaviour.

Is this unexpected and a bug or expected behaviour?
