### ISSUE TITLE
bug: LoadData - MariaDB - does not work with BLOB column type

### ISSUE THREAD

**Issue by edee111** [liquibase/liquibase#2519]
## Environment

**Liquibase Version**: 4.7.0

**Liquibase Integration & Version**: spring boot 2.7.0-M1, but is reproducible by cli

**Liquibase Extension(s) & Version**:

**Database Vendor & Version**: 10.5.11-MariaDB

**Operating System Type & Version**: does not matter

## Description
When we use `loadData` and there exists a BLOB column, then no data are populated in the DB at all. Even no exception is thrown, but in `databasechangelog` table the changeset is set as run.

## Steps To Reproduce

lets have `test.changelog.yaml`:
```
databaseChangeLog:
  - changeSet:
      id: "create-table"
      author: test
      changes:
        - createTable:
            tableName: person
            columns:
              - column:
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
                  name: sys_pk
                  type: INT
              - column:
                  constraints:
                    nullable: false
                    unique: true
                  name: sys_id
                  type: BINARY(16)
              - column:
                  name: email
                  type: VARCHAR(320)
  - changeSet:
      id: "populate-data"
      author: test
      changes:
        - loadData:
            #            usePreparedStatements: false # cannot use this, because BLOB has needsPreparedStatement = true (see LoadDataChange::generateStatements)
            commentLineStartsWith: '#'
            encoding: UTF-8
            file: test.csv
            quotchar: '"'
            separator: ','
            tableName: person
            relativeToChangelogFile: true
            columns:
              - column:
                  header: sys_id
                  name: sys_id
                  type: BLOB
              - column:
                  header: email
                  name: email
                  type: STRING
```
and `test.csv` file:
```
sys_id,email
GlZze9T4EeurnDxSgk2x5A==,user01@example.com
GlZ0idT4EeurnDxSgk2x5A==,BRazo@example.com
GlZ16dT4EeurnDxSgk2x5A==,FBronson@example.com
GlZ3NdT4EeurnDxSgk2x5A==,RQuirk@example.com
GlZ4qNT4EeurnDxSgk2x5A==,WTownes@example.com
```

Values of sys_id contain BASE64 encoded binary UUIDs.

## Actual Behavior
- changeset `populate data` is marked as successful in `databasechangelog` table
- no data are pupulated in database
- no exception or warning can be found in log

## Expected/Desired Behavior
- changeset `populate data` is marked as successful in `databasechangelog` table
- data are pupulated in database

## Additional Context
- in https://github.com/liquibase/liquibase/issues/1551 there is suggestion to use `usePreparedStatements: false` but this does not help because BLOB type sets needsPreparedStatement = true (see `LoadDataChange::generateStatements`)
- this issue is probably caused by https://github.com/liquibase/liquibase/pull/2215 - a50e90b4c526521b516e548250c0fdeb415c3d92
- the logic in `LoadDataChange::generateStatements` collects data in `preparedStatements` list, but in the end the logic returns value based on variable `statements` (which is empty list), so all the prepared statemenets are "ignored" and nothing gets executed later.

```
            if (anyPreparedStatements) {
                // If we have only prepared statements and the database supports batching, let's roll
                if (databaseSupportsBatchUpdates && statements.isEmpty() && (!preparedStatements.isEmpty())) {
                    if (database instanceof PostgresDatabase) {
                        // we don't do batch updates for Postgres but we still send as a prepared statement, see LB-744
                        return preparedStatements.toArray(new SqlStatement[preparedStatements.size()]);
                    } else {
                        return new SqlStatement[]{
                                new BatchDmlExecutablePreparedStatement(
                                        database, getCatalogName(), getSchemaName(),
                                        getTableName(), columns,
                                        getChangeSet(), Scope.getCurrentScope().getResourceAccessor(),
                                        preparedStatements)
                        };
                    }
                } else {
                    return statements.toArray(new SqlStatement[statements.size()]); //##### all the statements are in variable "preparedStatements" but here variable "statements is used"
                }
            } else {
             ...
```

**Comment by MichaelCkr** [comment]
Probably it may be sufficient, to extend the if (database instanceof PostgresDatabase) by the excluded MySQLDatabase from above.

**Comment by edee111** [comment]
The problem still occurs in 4.9.1 on MariaDB. Statements collected to the variable `preparedStatements` but in the end the logic returns result from variable `statements`.

![image](https://user-images.githubusercontent.com/4160602/201944374-4f6a56c2-8bbb-41b8-b97a-d5a132add1cc.png)

```
databaseChangeLog:
  - changeSet:
      id: "1"
      author: usu
      changes:
        - createTable:
            tableName: test
            columns:
              - column:
                  constraints:
                    nullable: false
                    primaryKey: true
                  name: sys_pk
                  type: INT
              - column:
                  constraints:
                    nullable: false
                  name: sys_when_created
                  type: DATETIME(6)
              - column:
                  constraints:
                    nullable: false
                    unique: true
                  name: sys_id
                  type: BINARY(16)
  - changeSet:
      id: "2"
      author: usu
      changes:
        - loadData:
            commentLineStartsWith: '#'
            encoding: UTF-8
            file: 0013.csv
            quotchar: '"'
            separator: ','
            tableName: test
            relativeToChangelogFile: true
            columns:
              - column:
                  header: sys_pk
                  name: sys_pk
                  type: NUMERIC
              - column:
                  header: sys_when_created
                  name: sys_when_created
                  type: DATETIME
              - column:
                  header: sys_id
                  name: sys_id
                  type: BLOB
```

and 0013.csv:

```
sys_pk,sys_when_created,sys_id
1,NOW,bIgBzXJhdUOy1Y6dSD/RyQ==
2,NOW,Zt4QmCBWNUmIOSW6yw5/1A==
```
