### ISSUE TITLE
After upgrading 4.6.1->4.6.2+ <constraints nullable="false"/> doesn't create NOT NULL column on MariaDB

### ISSUE THREAD

**Issue by AntonLem** [liquibase/liquibase#2523]
## Environment

**Liquibase Version**: 4.6.2, 4.7.0, 4.7.1

**Liquibase Integration & Version**: CLI  liquibase-4.7.1.zip, Spring Boot 2.6.3 + liquibase  4.6.2, 4.7.0, 4.7.1

**Liquibase Extension(s) & Version**:  N/A

**Database Vendor & Version**: MariaDB 10.7.1.20211119 (reproducable on several MariaDB 10.x), mariadb-java-client-2.7.0.jar, mariadb-java-client-2.7.4.jar, mariadb-java-client-2.7.5.jar

**Operating System Type & Version**: Windows 10Pro, Ubuntu, JRE 16 & 17

## Description

Liquibase 4.6.1 correctly creates `NOT NULL` column for  `<column><constraints nullable="false"/></column>` on MariaDB and MySQL. After upgrading to the any newer version  4.6.2, 4.7.0, 4.7.1 **all not nullable columns** became `DEFAULT NULL` and entire DB schema is broken.

## Steps To Reproduce

1. Launch MariaDB 10.x locally with `root` password `123456`
2. Create the new empty DB `test`
```sql
CREATE DATABASE `test` /*!40100 COLLATE 'utf8mb4_unicode_ci' */
```
3. Save this change log into the file `test.xml`
```xml
<?xml version="1.1" encoding="UTF-8" standalone="no"?>
<databaseChangeLog xmlns="http://www.liquibase.org/xml/ns/dbchangelog" xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext" xmlns:pro="http://www.liquibase.org/xml/ns/pro" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-4.6.xsd http://www.liquibase.org/xml/ns/dbchangelog http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-4.6.xsd">
    <changeSet author="Administrator (generated)" id="1644697651686-1">
        <createTable remarks="Security account" tableName="base_account">
            <column name="uid" remarks="Unique ID" type="BIGINT UNSIGNED">
                <constraints nullable="false" primaryKey="true"/>
            </column>
            <column defaultValueNumeric="0" name="version" remarks="Object version" type="SMALLINT UNSIGNED">
                <constraints nullable="false"/>
            </column>
        </createTable>
    </changeSet>
</databaseChangeLog>	
```
4. Apply Liquibase's changeLog with CLI command (was checked with liquibase-4.7.1.zip)
```shell
liquibase --username=root --password=123456 --url=jdbc:mariadb://localhost:3306/test --changelog-file=test.xml --driver=org.mariadb.jdbc.Driver update
```

## Actual Behavior
On the newer versions  4.6.2, 4.7.0, 4.7.1, Liquibase creates an incorrect table with this definition
```sql
CREATE TABLE `base_account` (
  `uid` bigint(20) unsigned NOT NULL COMMENT 'Unique ID',
  `version` smallint(5) unsigned DEFAULT NULL COMMENT 'Object version',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Security account';
```
**unsigned DEFAULT NULL** 

## Expected/Desired Behavior
Liquibase 4.6.1 creates a correct table
```sql
CREATE TABLE `base_account` (
  `uid` bigint(20) unsigned NOT NULL COMMENT 'Unique ID',
  `version` smallint(5) unsigned NOT NULL DEFAULT 0 COMMENT 'Object version',
  PRIMARY KEY (`uid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='Security account';
```
**unsigned NOT NULL DEFAULT 0**

**Comment by FBurguer** [comment]
Using the changelog listed and the command `liqubase updateSQL` i got the next output:
```
CREATE TABLE lbcat.base_account (
    uid BIGINT UNSIGNED NOT NULL COMMENT 'Unique ID', 
    version SMALLINT UNSIGNED DEFAULT 0 NOT NULL COMMENT 'Object version', 
    CONSTRAINT PK_BASE_ACCOUNT PRIMARY KEY (uid)) 
    COMMENT='Security account';
```
```
`liquibase snapshot` output:
        base_account
            columns:
                uid
                    nullable: false
                    order: 1
                    remarks: Unique ID
                    type: BIGINT(20) UNSIGNED
                version
                    defaultValue: 0
                    nullable: false
                    order: 2
                    remarks: Object version
                    type: SMALLINT(5) UNSIGNED
            default_tablespace: false
```
Looks like it got fixed at least on `4.11.0`

Testing Environment:
OS: Windows 10
Java 11
mariadb:10.2
