### ISSUE TITLE
IndexGeneratorSnapshot ignores column names if a filter condition is present

### ISSUE THREAD

**Issue by eicki** [liquibase/liquibase#2546]
## Environment
**Liquibase Version**: 4.7.1
**Liquibase Integration & Version**: Spring
**Liquibase Extension(s) & Version**:
**Database Vendor & Version**: Microsoft SQL Server 2016

## Description
If a filtered index is created in SQL Server, e.g.

CREATE UNIQUE INDEX IDX_CD ON MYTABLE(c, d, g) WHERE c IS NOT NULL AND d IS NOT NULL

by some custom change set, the IndexSnapshotGenerator returns an Index object containing three columns whose name is "([c] IS NOT NULL AND [d] IS NOT NULL)". This means the information is lost that the index spans the three columns c,d,g.

## Expected/Desired Behavior
The column name generated by IndexSnapshotGenerator should always be the column name if that is defined. Additionally it might be helpful if the Index object itself gets an attribute "filterCondition".

The issue is in https://github.com/liquibase/liquibase/blob/c77f374245a60dc9e12be0dfb4b50f3d9bbc6806/liquibase-core/src/main/java/liquibase/snapshot/jvm/IndexSnapshotGenerator.java#L296

**Comment by FBurguer** [comment]
Hi!  Now that you pointed where the issue is, if you have time, we would really appreciate if you submit a PR with the fix, it would greatly increase the fix speed. Thanks for submiting the issue and being part of the community!

**Comment by FBurguer** [comment]
Looks like it is still an issue for liquibase `4.16.1` , `liquibase snapshot` output:          
```
 indexes:
                IDX_CD
                    allowPageLocks: true
                    allowRowLocks: true
                    clustered: false
                    columns:
                        ([b] IS NOT NULL AND [a] IS NOT NULL)
                    fillFactor: 0
                    ignoreDuplicateKeys: false
                    incrementalStatistics: false
                    padIndex: false
                    recomputeStatistics: true
                    unique: true

```
