### ISSUE TITLE
postgresql diffChangelog dropping sequences erroneously

### ISSUE THREAD

**Issue by reddragond** [liquibase/liquibase#2555]
## Environment

**Liquibase Version**: 4.7.1

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: postgresql 11.12

**Operating System Type & Version**:  macOS 12.2

## Description

When using diffChangelog between postgresql sequences where the owner varies, liquibase generates a DROP statement instead of just ALTER SEQUENCE OWNED BY.

## Steps To Reproduce

Using docker

`#Download sample database
wget https://raw.githubusercontent.com/morenoh149/postgresDBSamples/master/worldDB-1.0/world.sql

docker run -d -p 5433:5432 --name test1 -e POSTGRES_HOST_AUTH_METHOD=trust postgres:11.12
docker run -d -p 5434:5432 --name test2 -e POSTGRES_HOST_AUTH_METHOD=trust postgres:11.12

sleep 5

psql -h localhost -p 5433 -U postgres -d postgres -f world.sql
psql -h localhost -p 5434 -U postgres -d postgres -f world.sql

psql -h localhost -p 5433 -U postgres -d postgres -c 'CREATE SEQUENCE public.city_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;'

psql -h localhost -p 5434 -U postgres -d postgres -c 'CREATE SEQUENCE public.city_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.city_id_seq OWNED BY public.city.id;'

#acquire postgresql-42.3.1.jar and store in the same directory
liquibase diffChangeLog --referenceUrl jdbc:postgresql://localhost:5434/postgres --referenceUsername postgres \
--url jdbc:postgresql://localhost:5433/postgres --username postgres \
--classpath postgresql-42.3.1.jar --changeLogFile test.postgresql.sql
`

## Actual Behavior
test.postgresql.sql will contain

`-- liquibase formatted sql

DROP SEQUENCE "public"."city_id_seq" CASCADE;`

## Expected/Desired Behavior
test.postgresql.sql should contain 

`ALTER SEQUENCE public.city_id_seq OWNED BY public.city.id;`

**Comment by nvoxland** [comment]
I simplified the setup a bit. After running your `docker run` commands, I just ran `docker exec -it {NAME} psql -U postgres` against both names, and ran:

```
create table city (id int);
CREATE SEQUENCE public.city_id_seq
AS integer
START WITH 1
INCREMENT BY 1
NO MINVALUE
NO MAXVALUE
CACHE 1;
```
against both, and ` ALTER SEQUENCE public.city_id_seq OWNED BY public.city.id;` against just `test2`.

**But, the fix for this is going to have to be part of a larger project around postgresql and squences/auto-increment logic.**

If you run `liquibase snapshot` against the two databases, you get 

```
Catalog & Schema: postgres / public
    liquibase.structure.core.Sequence:
        city_id_seq
            cacheSize: 1
            dataType: integer
            incrementBy: 1
            maxValue: 2147483647
            minValue: 1
            startValue: 1
            willCycle: false
        
    liquibase.structure.core.Table:
        city
            columns: 
                id
                    nullable: true
                    order: 1
                    type: int4
            default_tablespace: false
```
for test1, but only

```
Catalog & Schema: postgres / public
    liquibase.structure.core.Table:
        city
            columns: 
                id
                    nullable: true
                    order: 1
                    type: int4
            default_tablespace: false
```        
for test2.

The sequence isn't included in the snapshot for test2 because the "owned by a column" is part of what we use to determine that it's not a "real" sequence but just an implementation detail of an auto-increment column.

But, in this case even though it's owned by the column, we've not set the column up to be auto-increment and so it just gets lost.

At some point we need to take a good look at how we handle "internal" objects like sequences that back sequences, but at this point I don't know of a solution to this issue that's not going to send us down that road before we're ready. 

So for now, it's another example of "Generated snapshots are not always right. They are there as a convenience when possible, but can't handle everything so expect that you may have to fix them up before you try to apply them".
