### ISSUE TITLE
Different checksums are being calculated in different environments when changeSet has `valueDate` attribute

### ISSUE THREAD

**Issue by gabrielgmusskopf** [liquibase/liquibase#2624]
## Environment

**Liquibase Version**: 4.5.0

**Liquibase Integration & Version**: Spring Boot 2.6.3

**Liquibase Extension(s) & Version**:  -

**Database Vendor & Version**: Oracle 12c

**Operating System Type & Version**: Windows 10 and Ubuntu 14.04.3 LTS

## Description

I have a docker container with a Oracle 12c image that is used for integration tests. When the application is started, changeSets are added to a Oracle 12 database, that runs in a Docker container. The problems is that when this command is executed on my local machine, with Windows environment, a checksum is calculated, and when the command is executed from a different environment, with Ubuntu, a different checksum value is calculated. Both environments are using the same docker container mentioned before.
So, when the application start in different environment, e checksum error appears, as if an old changeset had been changed.

```
Caused by: liquibase.exception.ValidationFailedException: Validation Failed:
     1 change sets check sum
          liquibase/changelogs/version-0000/usuario/<script>.yml::insert-user-data::<author> was: 8:7d6101d97e41b69b07a89398bd54545f but is now: 8:f417f32c496c2bd1ad551ed95503c141
```

After some debugging, I found out that the source of the problem is a `valueDate` attribute. I'm using `yaml` format to write the scripts. 

## Steps To Reproduce

1. Build a Docker container with Oracle 12 image
2. In Spring Boot application, include those dependencies

```xml
<dependency>
    <groupId>org.liquibase</groupId>
    <artifactId>liquibase-core</artifactId>
</dependency>

<plugin>
    <groupId>org.liquibase</groupId>
    <artifactId>liquibase-maven-plugin</artifactId>
</plugin>
```
3. Add those configurations at application.yaml

```yaml
spring:

  datasource:
    driver-class-name: oracle.jdbc.OracleDriver
    url: //your oracle database url
    username: //oracle username
    password: //oracle password

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: false
    
    hibernate:
      ddl-auto: none

  liquibase:
    change-log: //your classpath
    enabled: true
```

4. Create a table with a `timestamp` column 
5. At Windows environment, insert some data in this column

```
databaseChangeLog:
- changeSet:
    context: local, integration
    changes:
      - insert: 
        ...
        columns:
        ...
        - column:
                  valueDate: 2021-01-01T12:00:00
```

6. At Ubuntu environment, start the application

OBS:
- The values must be inserted in any of the two environments, and the application must be started in the other one
- Both environments must point to the same database
- Remember to use `yaml` format oi changesets

## Actual Behavior
The environment is influencing checksum calculation when the changeset has `valueDate` attribute. This error **only** occurs when changeSet has `valueDate` attribute.

Any relevant logs have been described earlier.

## Expected/Desired Behavior
The checksum must be the same independent of the environment and attributes
