### ISSUE TITLE
MySQL/MariaDB column remark in `createTable` drops column `NOT NULL` and default value

### ISSUE THREAD

**Issue by camsaul** [liquibase/liquibase#2634]
This seems to be a regression in 4.8.0; it was previously working for us on 3.6.3.

We have a changeSet like this:

```yaml
  - changeSet:
      id: 47
      author: camsaul
      validCheckSum: ANY
      changes:
        - createTable:
            tableName: collection
            remarks: 'Collections are an optional way to organize Cards and handle permissions for them.'
            columns:
              - column:
                  name: id
                  type: int
                  autoIncrement: true
                  constraints:
                    primaryKey: true
                    nullable: false
              ...
              - column:
                  name: archived
                  type: boolean
                  remarks: 'Whether this Collection has been archived and should be hidden from users.'
                  defaultValueBoolean: false
                  constraints:
                    nullable: false
```

The generated SQL looks like this::

```sql
CREATE TABLE `metabase_test`.`collection` (
  `id` INT AUTO_INCREMENT NOT NULL, 
  ...
  `archived` BIT(1) DEFAULT 0 NOT NULL COMMENT 'Whether this Collection has been archived and should be hidden from users.', 
  CONSTRAINT `PK_COLLECTION` PRIMARY KEY (`id`), 
  UNIQUE (`slug`)
) COMMENT = 'Collections are an optional way to organize Cards and handle permissions for them.';

ALTER TABLE `metabase_test`.`collection` 
MODIFY COLUMN `archived` BIT(1) 
COMMENT 'Whether this Collection has been archived and should be hidden from users.';
```

After the first statement `DESCRIBE collection;` shows

```
MariaDB [metabase_test]> describe collection;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
...
| archived    | bit(1)       | NO   |     | b'0'    |                |
+-------------+--------------+------+-----+---------+----------------+
```

but after the second statement it is now

```
MariaDB [metabase_test]> describe collection;
+-------------+--------------+------+-----+---------+----------------+
| Field       | Type         | Null | Key | Default | Extra          |
+-------------+--------------+------+-----+---------+----------------+
| id          | int(11)      | NO   | PRI | NULL    | auto_increment |
...
| archived    | bit(1)       | YES  |     | NULL    |                |
+-------------+--------------+------+-----+---------+----------------+
```

I'm not sure why the second statement is needed at all, since the `CREATE TABLE` statement itself contains the column `COMMENT`.

Probably related: #2301
