### ISSUE TITLE
Postgresql diffChangeLog not quoting json default

### ISSUE THREAD

**Issue by reddragond** [liquibase/liquibase#2864]
## Environment
MacOS and Docker
**Liquibase Version**:
4.10
**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>
CLI
**Database Vendor & Version**:
postgres 11.13
**Operating System Type & Version**:

## Example
Create a table in one DB
`CREATE TABLE test (test jsonb not null default '{}');`

Run Liquibase diffChangeLog against the above DB and a blank one and it will output the below
`CREATE TABLE "public"."test" ("test" JSONB DEFAULT {} NOT NULL);`

This will fail to execute because the {} are not enclosed in single quotes.

## Expected/Desired Behavior
The following should be outputted
`CREATE TABLE "public"."test" ("test" JSONB DEFAULT '{}' NOT NULL);`

**Comment by FBurguer** [comment]
Still a bug on liquibase `4.14`

**Comment by bcicc** [comment]
Having this same issue in 4.28.0

**Comment by yamilovs** [comment]
same issue at `4.31.0` version

**Comment by omgirok** [comment]
it looks like you will need to do 
```
        - column:
            constraints:
              nullable: false
            defaultValueComputed: "'{}'::jsonb"
```
instead of 
```
        - column:
            constraints:
              nullable: false
            defaultValueComputed: '{}'
```
to get around this
