### ISSUE TITLE
Liquibase cannot determine constraint exists with given name

### ISSUE THREAD

**Issue by waroir20** [liquibase/liquibase#3032]
## Environment

**Liquibase Version**: 4.7.0 (I verified functionality works in 4.6.2 and fails beyond 4.7.0 up to 4.10.0, I did not check beyond that)

**Liquibase Integration & Version**: spring boot

**Liquibase Extension(s) & Version**: using liquibase-maven-plugin 4.5.0

**Database Vendor & Version**: (COMMAND used 'SELECT version()')
 - Happens for AWS RDS (PostgreSQL 12.8 on aarch64-unknown-linux-gnu, compiled by aarch64-unknown-linux-gnu-gcc (GCC) 7.4.0, 64-bit)
 - Happens in docker locally using (PostgreSQL 14.2 (Debian 14.2-1.pgdg110+1) on aarch64-unknown-linux-gnu, compiled by gcc (Debian 10.2.1-6) 10.2.1 20210110, 64-bit)

**Operating System Type & Version**: Unsure for the OS in AWS RDS, but docker locally on MacOS 12.4 on the M1 silicon chip

**Infrastructure Type/Provider**: Both AWS for deployed, and docker 4.8.2 locally

## Description

Liquibase used to create table with FK to another table where constraint is named specifically. Later changeset to drop the FK with added precondition to ensure that the FK is present. 

Expected behavior: the FK is dropped
Actual behavior: the precondition fails to find the named FK and thus the changeset is not applied

note: Tested locally by wiping out DB and having all changes reapplied using various versions of liquibase from 4.3.5 to 4.10.0, determined desired state achieved 4.3.5 -> 4.6.2 and not achieved from 4.7.0-> 4.10.0

## Steps To Reproduce

Use yaml based changeset files to create parent table, then create child table with FK to parent using parent's PK, then check existence of FK with precondition and drop FK if exists.

Using Maven - 
org.springframework.boot  spring-boot-starter-parent 2.6.7
org.springframework.boot  spring-boot-starter-data-jpa 2.6.7
org.postgresql    postgresql  42.3.5 (scope: runtime)
org.liquibase   liquibase-core 4.7.0

file: src/main/resources/liquibase.migration/db.changelog-master.yaml
```
databaseChangeLog:
  - includeAll:
      path: "changesets/"
      relativeToChangelogFile: true
```

file: src/main/resources/liquibase.migration/changesets/v0001.yaml
```
databaseChangeLog:
- changeSet:
      id: create_sequence_lock
      preConditions:
        - onFail: MARK_RAN
        - onFailMessage: 'Precondition failed - lock PK sequence exists'
          not:
            sequenceExists:
              sequenceName: lock_lock_id_seq
      changes:
        - tagDatabase:
            tag: version_1.0
        -  createSequence:
             sequenceName: lock_lock_id_seq
             cycle: true
             dataType: BIGINT
             incrementBy: 1
             startValue: 1
  - changeSet:
      id: create_table_lock
      preConditions:
        - onFail: MARK_RAN
        - onFailMessage: 'Precondition failed - lock table exists'
          not:
            tableExists:
              tableName: lock
      changes:
        - tagDatabase:
            tag: version_1.0
        - createTable:
            tableName: lock
            columns:
              - column:
                  name: lock_id
                  type: BIGINT
                  defaultValueComputed: nextval('lock_lock_id_seq')
                  constraints:
                    primaryKey: true
              - column:
                  name: state
                  type: boolean
                  constraints:
                    nullable: false
              - column:
                  name: location_id
                  type: varchar(10)
                  constraints:
                    nullable: false
              - column:
                  name: product_code
                  type: varchar(100)
                  constraints:
                    nullable: true
              - column:
                  name: created_at
                  type: java.sql.Types.TIMESTAMP_WITH_TIMEZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
- changeSet:
      id: create_table_channel_response
      preConditions:
        - onFail: MARK_RAN
        - onFailMessage: 'Precondition failed - channel_response table exists'
          not:
            tableExists:
              tableName: channel_response
      changes:
        - tagDatabase:
            tag: version_1.0
        - createTable:
            tableName: channel_response
            columns:
              - column:
                  name: lock_resp_id
                  type: VARCHAR(50)
                  constraints:
                    primaryKey: true
              - column:
                  name: lock_id
                  type: BIGINT
                  constraints:
                    nullable: false
                    references: lock(lock_id)
                    foreignKeyName: FK_Lock_1
              - column:
                  name: response
                  type: INTEGER
                  constraints:
                    nullable: false
              - column:
                  name: sent_at
                  type: java.sql.Types.TIMESTAMP_WITH_TIMEZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: java.sql.Types.TIMESTAMP_WITH_TIMEZONE
                  defaultValueComputed: CURRENT_TIMESTAMP
                  constraints:
                    nullable: false
```

file: src/main/resources/liquibase.migration/changesets/v0016.yaml
```
databaseChangeLog:
  - changeSet:
      id: drop_fk_channel_response_column_lock_id
      preConditions:
        - onFail: MARK_RAN
        - onFailMessage: 'Precondition failed - FK_Lock_1 does not exist'
          foreignKeyConstraintExists:
            foreignKeyName: FK_Lock_1
      changes:
        - tagDatabase:
            tag: version_12.0
        - dropForeignKeyConstraint:
            baseTableName: channel_response
            constraintName: FK_Lock_1
```

file: src/main/resources/application.yaml
```
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  liquibase:
    contexts: ${SPRING_LIQUIBASE_CONTEXTS}
    liquibase-schema: lockmanager
    default-schema: lockmanager
    change-log: classpath:/liquibase/migration/db.changelog-master.yaml
```

Environment properties (locally):
```
SPRING_DATASOURCE_URL=jdbc:postgresql://localhost:5432/postgres?currentSchema=lockmanager
SPRING_DATASOURCE_USERNAME=postgres
SPRING_DATASOURCE_PASSWORD=postgres
SPRING_LIQUIBASE_CONTEXTS=LOCAL,TEST
```
Environment properties (AWS):
```
SPRING_DATASOURCE_URL=jdbc:postgresql://<db-name>.cluster-<clusterID>.us-east-1.rds.amazonaws.com:5432/<DB name>?currentSchema=lockmanager&targetServerType=primary
SPRING_DATASOURCE_USERNAME=<your username here>
SPRING_DATASOURCE_PASSWORD=<your password here>
SPRING_LIQUIBASE_CONTEXTS=DEV
```

file: src/main/java/com.example.Application.java
```
package com.example;

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class FulfillmentLockManagerApplication {

    public static void main(String[] args) {
        SpringApplication.run(FulfillmentLockManagerApplication.class, args);
    }

}

```

file: pom.xml
```
<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.6.7</version>
    </parent>

    <groupId>com.example</groupId>
    <artifactId>liquibase-app</artifactId>
    <version>0.0.1-SNAPSHOT</version>
    <name>Liquibase example</name>


    <properties>
        <java.version>11</java.version>
        <spring-boot-starter-parent.version>2.6.7</spring-boot-starter-parent.version>
        <spring-cloud.version>2021.0.2</spring-cloud.version>
        <spring-cloud-context.version>3.1.2</spring-cloud-context.version>
        <tomcat-embed-core.version>9.0.63</tomcat-embed-core.version>
        <postgres.version>42.3.5</postgres.version>
        <maven-compiler-plugin.version>3.10.1</maven-compiler-plugin.version>
        <spring-core.version>5.3.20</spring-core.version>
        <liquibase-core.version>4.10.0</liquibase-core.version>
        <spring-web.version>5.3.16</spring-web.version>
        <spring-beans.version>5.3.19</spring-beans.version>
    </properties>

	<dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring-cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
	</dependencyManagement>
	 <dependencies>
            <dependency>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-core</artifactId>
                <version>${liquibase-core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.tomcat.embed</groupId>
                <artifactId>tomcat-embed-core</artifactId>
                <version>${tomcat-embed-core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.postgresql</groupId>
                <artifactId>postgresql</artifactId>
                <version>${postgres.version}</version>
                <scope>runtime</scope>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-core</artifactId>
                <version>${spring-core.version}</version>
            </dependency>
            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-beans</artifactId>
                <version>${spring-beans.version}</version>
            </dependency>

            <dependency>
                <groupId>org.springframework</groupId>
                <artifactId>spring-web</artifactId>
                <version>${spring-web.version}</version>
            </dependency>
        </dependencies>

    <build>
        <plugins>
            <plugin>
                <groupId>org.liquibase</groupId>
                <artifactId>liquibase-maven-plugin</artifactId>
                <version>${liquibase-core.version}</version>
            </plugin>
			<plugin>
				<groupId>org.springframework.boot</groupId>
				<artifactId>spring-boot-maven-plugin</artifactId>
				<version>${spring-boot-starter-parent.version}</version>
			</plugin>
			 <plugin>
                    <groupId>org.apache.maven.plugins</groupId>
                    <artifactId>maven-compiler-plugin</artifactId>
                    <version>${maven-dependency-plugin.version}</version>
                    <configuration>
                        <source>${java.version}</source>
                        <target>${java.version}</target>
                    </configuration>
                </plugin>
		</plugins>
    </build>

</project>
```

Run springboot application normally, or in dockerized container using alpine linux as base image

## Actual Behavior
The precondition fails to find the FK named 'FK_Lock_1' and thus the changeset is not applied

Note: Seen with liquibase-core 4.7.0 -> 4.10.0
11:21:49.788 [main] INFO  liquibase.changelog - Reading resource: liquibase/migration/changesets/v0016.yaml trace_id= span_id= 
11:21:49.798 [main] INFO  liquibase.changelog - Reading resource: liquibase/migration/changesets/v0017.yaml trace_id= span_id= 
11:21:49.975 [main] INFO  liquibase.changelog - Reading from lockmanager.databasechangelog trace_id= span_id= 
11:21:50.486 [main] INFO  liquibase.changelog - Marking ChangeSet: liquibase/migration/changesets/v0016.yaml::drop_fk_channel_response_column_lock_id::me ran despite precondition failure due to onFail='MARK_RAN': 
          classpath:/liquibase/migration/db.changelog-master.yaml : Precondition failed - FK_Lock_1 does not exist
 trace_id= span_id= 
11:21:50.508 [main] INFO  liquibase.lockservice - Successfully released change log lock trace_id= span_id= 

Note: databasechangelog record
"id"	"author"	"filename"	"dateexecuted"	"orderexecuted"	"exectype"	"md5sum"	"description"	"comments"	"tag"	"liquibase"	"contexts"	"labels"	"deployment_id"
"drop_fk_channel_response_column_lock_id"	"me"	"liquibase/migration/changesets/v0016.yaml"	"2022-07-01 11:31:16.120151"	106	"MARK_RAN"	"8:fa72e5aec5416d449019e00eb91495f2"	"tagDatabase; dropForeignKeyConstraint baseTableName=channel_response, constraintName=FK_Lock_1"		"version_12.0"	"4.7.0"			"6693075716"

## Expected/Desired Behavior
The FK 'FK_Lock_1' is dropped.

Note: Seen with liquibase-core 4.3.5 -> 4.6.2
11:26:13.668 [main] INFO  liquibase.changelog - Reading resource: liquibase/migration/changesets/v0016.yaml trace_id= span_id= 
11:26:13.677 [main] INFO  liquibase.changelog - Reading resource: liquibase/migration/changesets/v0017.yaml trace_id= span_id= 
11:26:13.833 [main] INFO  liquibase.changelog - Reading from lockmanager.databasechangelog trace_id= span_id= 
11:26:14.333 [main] INFO  liquibase.changelog - Tag 'version_12.0' applied to database trace_id= span_id= 
11:26:14.347 [main] INFO  liquibase.changelog - Foreign key FK_Lock_1 dropped trace_id= span_id= 
11:26:14.348 [main] INFO  liquibase.changelog - ChangeSet liquibase/migration/changesets/v0016.yaml::drop_fk_channel_response_column_lock_id::me ran successfully in 231ms trace_id= span_id= 
11:26:14.359 [main] INFO  liquibase.lockservice - Successfully released change log lock trace_id= span_id= 

Note: databasechangelog record
"id"	"author"	"filename"	"dateexecuted"	"orderexecuted"	"exectype"	"md5sum"	"description"	"comments"	"tag"	"liquibase"	"contexts"	"labels"	"deployment_id"
"drop_fk_channel_response_column_lock_id"	"me"	"liquibase/migration/changesets/v0016.yaml"	"2022-07-01 11:26:14.350614"	106	"EXECUTED"	"8:fa72e5aec5416d449019e00eb91495f2"	"tagDatabase; dropForeignKeyConstraint baseTableName=channel_response, constraintName=FK_Lock_1"		"version_12.0"	"4.6.2"			"6692773929"

## Additional Context
Reach out if more information is needed... Thank you.
