### ISSUE TITLE
reserved key words are not quoted in yaml format for where clause 

### ISSUE THREAD

**Issue by elvisnap** [liquibase/liquibase#3051]
## Environment

**Liquibase Version**: 4.5.0

**Database Vendor & Version**: mysql 8.0.22

## Description

Reserved key words are not quoted in yaml format for where clause 

## Steps To Reproduce

```
databaseChangeLog:
  - objectQuotingStrategy: QUOTE_ALL_OBJECTS
  - changeSet:
      id: 1
      author: xxxx
      changes:
        - delete:
            catalogName: my_db
            tableName: user_derived_data
            where: key = somestring

```
## Actual Behavior
it will generate: 
``DELETE FROM `my_db`.`user_derived_data` WHERE key = somestring``

## Expected/Desired Behavior
``DELETE FROM `my_db`.`user_derived_data` WHERE `key` = somestring``
