### ISSUE TITLE
Snapshot & Diff between file and db from url | Postgresql : btree index created on multiple columns with basic WHERE condition is treated as a difference (incorrectly snapshotted)

### ISSUE THREAD

**Issue by Wincioor11** [liquibase/liquibase#3053]
## Environment

**Liquibase Version**: 4.11.0

**Database Vendor & Version**: PostgreSQL 12.9 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44), 64-bit

**Infrastructure Type/Provider**: VM

## Description

- postgresql btree index created on two columns with basic WHERE condition is treated as a difference between schema snapshotted to json/yaml file and the actual db schema retrieved using liquibase diff command with url parameter that points to the db
- It is the same when using json and yaml files

## Steps To Reproduce

List the steps to reproduce the behavior.
- Create an index on postgresql database table like this:
`CREATE INDEX index_name ON table_name USING btree (column_a, column_b) WHERE ((column_a)::text = 'some-value'::text)`
- run the liquibase snapshot command:
`liquibase --url="jdbc:postgresql://IP_ADDRESS/DB_NAME" --username=username --password=pwd --driver=org.postgresql.Driver --defaultSchemaName=public --outputFile=schema_file.yaml snapshot --snapshotFormat=yaml
`
- run the liquibase diff command that will compare schema from file with db from url schema:
 `liquibase --url="jdbc:postgresql://IP_ADDRESS/DB_NAME" --username=username --password=pwd --driver=org.postgresql.Driver --referenceUrl="offline:postgresql?snapshot=schema_file.yaml" diff`

## Actual Behavior
```
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 14:50:50 (version 4.11.0 #2708 built at 2022-05-23 15:17+0000)
Liquibase Version: 4.11.0
Liquibase Community 4.11.0 by Liquibase

Diff Results:
Reference Database: postgres @ offline:postgresql?snapshot=schema_file.yaml (Default Schema: public)
Comparison Database: postgres @ jdbc:postgresql://IP_ADDRESS/DB_NAME (Default Schema: public)
Compared Schemas: public
Product Name:
     Reference:   'PostgreSQL'
     Target: 'Offline postgresql'
Product Version: EQUAL
Missing Catalog(s): NONE
Unexpected Catalog(s): NONE
Changed Catalog(s): NONE
Missing Column(s): NONE
Unexpected Column(s):
     ((column_a)::text = 'some-value'::text)
Changed Column(s): NONE
Missing Foreign Key(s): NONE
Unexpected Foreign Key(s): NONE
Changed Foreign Key(s): NONE
Missing Index(s): NONE
Unexpected Index(s): NONE
Changed Index(s):
     index_name ON public.table_name(((column_a)::text = 'some-value'::text), ((column_a)::text = 'some-value'::text)
          columns changed from '[public.table_name.((column_a)::text = 'some-value'::text), public.table_name.((column_a)::text = 'some-value'::text)]' to '[null]'
Missing Primary Key(s): NONE
Unexpected Primary Key(s): NONE
Changed Primary Key(s): NONE
Missing Schema(s): NONE
Unexpected Schema(s): NONE
Changed Schema(s): NONE
Missing Sequence(s): NONE
Unexpected Sequence(s): NONE
Changed Sequence(s): NONE
Missing Table(s): NONE
Unexpected Table(s): NONE
Changed Table(s): NONE
Missing Unique Constraint(s): NONE
Unexpected Unique Constraint(s): NONE
Changed Unique Constraint(s): NONE
Missing View(s): NONE
Unexpected View(s): NONE
Changed View(s): NONE
Liquibase command 'diff' was executed successfully.
```

## Expected/Desired Behavior
Should print the diff output Without any differences found as those are exact same schemas (same DB):
```
Product Name: EQUAL
Product Version: EQUAL
Missing Catalog(s): NONE
Unexpected Catalog(s): NONE
Changed Catalog(s): NONE
Missing Column(s): NONE
Unexpected Column(s): NONE
Changed Column(s): NONE
Missing Foreign Key(s): NONE
Unexpected Foreign Key(s): NONE
Changed Foreign Key(s): NONE
Missing Index(s): NONE
Unexpected Index(s): NONE
Changed Index(s): NONE
Missing Primary Key(s): NONE
Unexpected Primary Key(s): NONE
Changed Primary Key(s): NONE
Missing Schema(s): NONE
Unexpected Schema(s): NONE
Changed Schema(s): NONE
Missing Sequence(s): NONE
Unexpected Sequence(s): NONE
Changed Sequence(s): NONE
Missing Table(s): NONE
Unexpected Table(s): NONE
Changed Table(s): NONE
Missing Unique Constraint(s): NONE
Unexpected Unique Constraint(s): NONE
Changed Unique Constraint(s): NONE
Missing View(s): NONE
Unexpected View(s): NONE
Changed View(s): NONE
```

## Additional Context
when running liquibase diff command between same db url there is no differences as expected, so there is something wrong in diff or snapshot command and it makes them incompatible...

Good to mention is that I investigated how the yaml file looks like and I saw that the index has been saved uncorrectly:
```
- index:
        columns:
        - column:
            computed: true
            name: ((column_a)::text = 'some-value'::text)
            snapshotId: '9039221'
        - column:
            computed: true
            name: ((column_a)::text = 'some-value'::text)
            snapshotId: '9039221'
        name: index_name
        snapshotId: '9039220'
        table: liquibase.structure.core.Table#9039214
        unique: false
```
and in columns:
```
liquibase.structure.core.Column:
    - column:
        computed: true
        name: ((property_type)::text = 'batchExecutionId'::text)
        snapshotId: '9039221'
```

only the information about the column_a has been saved (twice?), the information about using column_b is missing

for example another index with two columns but without the WHERE condition is being saved like that:
```
- index:
        columns:
        - liquibase.structure.core.Column#9039218
        - liquibase.structure.core.Column#9039219
        name: another_index_name
        snapshotId: '9039217'
        table: liquibase.structure.core.Table#9039214
        unique: false
```

I see it as a bug.
