### ISSUE TITLE
Problem inserting valueBlobFile into bytea column postgres

### ISSUE THREAD

**Issue by jnclmns** [liquibase/liquibase#3165]
## Environment

**Liquibase Version**:
Liquibase 4.14

**Liquibase Integration & Version**: 
CLI 

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
PostgreSQL 14.4

Via docker:
version: '3.8'

services:
  postgres:
    image: postgres:14.4
    ports:
      - 5432:5432
    volumes:
      - /d/postgres/exampledb:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=4321
      - POSTGRES_DB=exampledb
      - PGDATA=/var/lib/postgresql/data/pgdata 

**Operating System Type & Version**:
Windows 10 

**Infrastructure Type/Provider**:
CLI

## Description
Following Changelog runs without problems with liquibase 4.11:

<?xml version="1.0" encoding="UTF-8"?>
<databaseChangeLog
	xmlns="http://www.liquibase.org/xml/ns/dbchangelog"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xmlns:ext="http://www.liquibase.org/xml/ns/dbchangelog-ext"
	xmlns:pro="http://www.liquibase.org/xml/ns/pro"
	xsi:schemaLocation="http://www.liquibase.org/xml/ns/dbchangelog
		http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-latest.xsd
		http://www.liquibase.org/xml/ns/dbchangelog-ext http://www.liquibase.org/xml/ns/dbchangelog/dbchangelog-ext.xsd
		http://www.liquibase.org/xml/ns/pro http://www.liquibase.org/xml/ns/pro/liquibase-pro-latest.xsd">

	<changeSet id="di-1" author="someauthor">
		<createTable tableName="blobtest">
			<column name="id" type="int8">
				<constraints nullable="false" />
			</column>
			<column name="content" type="bytea" />
		</createTable>

		<addPrimaryKey columnNames="id"
			constraintName="blobtest_pk" tableName="blobtest" />

		<createSequence sequenceName="blobtest_sequence"
			incrementBy="50" startValue="100" />
	</changeSet>

	<changeSet id="di-2" author="someauthor">
		<insert tableName="blobtest">
			<column name="id" valueNumeric="1" />
			<column name="content" valueBlobFile="foo.txt" />
		</insert>
	</changeSet>

</databaseChangeLog>

foo.txt is textfile UTF-8 endoded content: foo

With 4.14 i get an Exception:
Caused by: org.postgresql.util.PSQLException: ERROR: column "content" is of type bytea but expression is of type bigint
  Hinweis: You will need to rewrite or cast the expression.

## Steps To Reproduce
Use the CLI with the changelog above against an postgres db.

## Actual Behavior
An exception in thrown with the cause stated above.

## Expected/Desired Behavior
A changelog with bytea as type and valueBlobFile creates a table with a column of type bytea and the

**Comment by kataggart** [comment]
@jnclmns my newbie guess is that it is related to https://github.com/liquibase/liquibase/pull/605. I could very well be wrong. We will take a look as a team at this as soon as we are able, but wanted to point you towards that PR in the meantime just in case it helps out. Thanks!

**Comment by pkernevez** [comment]
I have the same bug when trying to updaload data in my table.
The pb has been introduce by the 4.12.0 (and is still present with more recent version), it works fine with 4.11.0 as [jnclmns](https://github.com/jnclmns).


My context SpringBoot 2.7.3
Liquibase 4.12.0
DB posgresql

My table:
```
  - changeSet:
      id: 1 - translation
      changes:
        - createTable:
            tableName: TRANSLATION
            columns:
              - column:
                  name: ID
                  type: bigint
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: UID
                  type: varchar(40)
              - column:
                  name: PDF_TMP
                  type: bytea
                  
  - changeSet:
      id: 2 - Add Translation data
      context: sample_data
      changes:
        - loadData:
            encoding: UTF-8
            file: db/changelog/data/sample_data/2_translation.csv
            separator: ","
            tableName: TRANSLATION
            usePreparedStatements: true
            columns:
              - column:
                  name: PDF_TMP
                  type: BLOB
```

With this csv file: `2_translation.csv`
```
ID,PDF_TMP,UID
-10001,data/sample_data/100_de.pdf,AAAAAAAAAAA
-10002,data/sample_data/100_en.pdf,BBBBBBBBBBB
-10003,data/sample_data/100_fr.pdf,CCCCCCCCCCC
```

And I have the same error :
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "pdf_tmp" is of type bytea but expression is of type bigint
  Hint: You will need to rewrite or cast the expression.
  Position: 139
```
