### ISSUE TITLE
modifyDataType is not respecting the autoincrement attribute

### ISSUE THREAD

**Issue by tabbyf00** [liquibase/liquibase#3180]
## Environment

**Database Vendor & Version**: Oracle and probably others

## Description

When using mocifyDataType and specifying autoincrement="true" or "false" the autoincrement is not changed from whatever the previous state was. It was noticed on Oracle but probably applies to other databases as well. 

Fix may be as much validation errors as it is changes to generated SQL depending on underlying database support. 

## Steps To Reproduce

```
databaseChangeLog:
  - changeSet:
      ...
      changes:   
        -  modifyDataType:   
            columnName: MYCOLUNM  
            newDataType: number(9)
            autoIncrement: false 
            tableName: MYTABLE
```

## Actual Behavior
Data type changes but autoincrement is not removed. 

## Expected/Desired Behavior
On Oracle, include SQL similar to `alter table MYTABLE modify MYCOLUNM drop identity;`
