### ISSUE TITLE
sqlFile throws IOException when relativeToChangelogFile is used (from an included databaseChangeLog file)

### ISSUE THREAD

**Issue by sergiupantiru** [liquibase/liquibase#3200]
## Environment

**Liquibase Version**: 4.5.0

**Liquibase Integration & Version**: spring boot (**webflux**)

**Liquibase Extension(s) & Version**: no

**Database Vendor & Version**: postgres 14.4

**Operating System Type & Version**: MacOs (M1)

**Infrastructure Type/Provider**: local

## Description

When using `relativeToChangelogFile=true` for `sqlFile` liquibase throws IOException. 
This is because the `getPhysicalFilePath` contains also the changelog filename. ( `/db/changelog/./install/main.yaml` )

Workaround: start the path from parent directory 
```diff
  sqlFile:
-   path: sql/sql-file.sql
+   path: ../sql/sql-file.sql
    relativeToChangelogFile: true
    splitStatements: false
```

## Steps To Reproduce

`resources/db/changelog/db.changelog-master.yaml`
```yaml
databaseChangeLog:
  - include:
      file: ./install/main.yaml
      relativeToChangelogFile: true
```
`resources/db/changelog/install/main.yaml`
```yaml
databaseChangeLog:
  - changeSet:
      id: create-schema
      changes:
        - sqlFile:
            path: sql/sql-file.sql
            relativeToChangelogFile: true
            splitStatements: false
```

## Actual Behavior
Exception is thrown 
```
Caused by: java.io.IOException: The file sql/sql-file.sql was not found in
    - Spring resources
```

## Expected/Desired Behavior
File is found and executed

## Additional Context
Maybe in [liquibase.change.core.SQLFileChange](https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/change/core/SQLFileChange.java#L120)  `FilenameUtil.getDirectory` should be used (to remove the filename):

```diff
        try {
            String relativeTo = null;
            if (ObjectUtil.defaultIfNull(isRelativeToChangelogFile(), false)) {
                relativeTo = getChangeSet().getChangeLog().getPhysicalFilePath();
            }
-            inputStream = Scope.getCurrentScope().getResourceAccessor().openStream(relativeTo, path);
+            inputStream = Scope.getCurrentScope().getResourceAccessor().openStream(FilenameUtil.getDirectory(relativeTo), path);
        } catch (IOException e) {
            throw new IOException("Unable to read file '" + path + "'", e);
        }
```
