### ISSUE TITLE
referencedTableSchemaName is ignored

### ISSUE THREAD

**Issue by PotcFdk** [liquibase/liquibase#3313]
## Environment

**Liquibase Version**: 4.16.1

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**: Postgres 14.5-1

**Operating System Type & Version**: official docker image

**Infrastructure Type/Provider**: VM

## Description

In an `addColumn` change, `referencedTableSchemaName` for foreign key constraints is ignored.
This used to work in version 4.9.1 if I remember correctly, but does not work in 4.16.1. I am not yet sure when it stopped working.

## Steps To Reproduce

```yaml
databaseChangeLog:
- changeSet:
[...]
    changes:
    - addColumn:
        schemaName: example
        tableName: ex_table
        columns:
        - column:
            name: object_id
            type: UUID
            constraints:
                foreignKeyName: ex_table_object_fk
                referencedTableName: objects
                referencedTableSchemaName: example
                referencedColumnNames: id
```

## Actual Behavior

```sql
ALTER TABLE example.ex_table ADD CONSTRAINT ex_table_object_fk FOREIGN KEY (object_id) REFERENCES objects (id);
```

## Expected/Desired Behavior

```sql
ALTER TABLE example.ex_table ADD CONSTRAINT ex_table_object_fk FOREIGN KEY (object_id) REFERENCES example.objects (id);
```

**Comment by PotcFdk** [comment]
**Update**: The working case I was referring to was in `createTable`, this one is in `addColumn`, I guess this is the difference that actually matters. I hope this helps with finding the bug.

**Comment by FBurguer** [comment]
Thanks for submitting this issue! I could reproduce it in my environment. We will add it to the list of bugs to fix

**Comment by BearsPunch** [comment]
after two years no fix yet?

**Comment by Xstoudi** [comment]
I confirm it's still a problem.

**Comment by MalloD12** [comment]
Hi @Xstoudi,

Could you please help me to reproduce this issue? I cannot reproduce this issue without your fix. I guess I might be not following the right steps. See, I'm using the below changelog:

```xml
databaseChangeLog:
  - changeSet:
      id: add_column_change
      author: mallod
      changes:
        - addForeignKeyConstraint:
            baseColumnNames: person_id
            baseTableCatalogName: cat
            baseTableName: address
            baseTableSchemaName: public
            constraintName: fk_address_person
            referencedColumnNames: id
            referencedTableName: person
            referencedTableSchemaName: test
```

Running an `update-sql` this is the output I'm getting:

```console
ALTER TABLE cat.[public].address ADD CONSTRAINT fk_address_person FOREIGN KEY (person_id) REFERENCES test.person (id);
GO
```

That's what I can see from `master` branch. Can you have a look and please let me know whether I'm failing in one of the above steps? Looking at the code changes made, they look good to me but trying to reproduce this manually I'm not able to. This attempt was from `MSSQL` (but I'm seeing the same for `Posgtres `and `H2` as well).

Thanks,
Daniel.

**Comment by Xstoudi** [comment]
Hi @MalloD12,

Using `referencedTableSchemaName` on `addForeignKeyConstraint` works perfectly fine.

What does not work is using `referencedTableSchemaName` on `constraint` tag inside `addColumn` -> `column` tags to define the foreign constraint. I'm not familiar with YML definition, but I that the issue original message shows it off.

```
databaseChangeLog:
- changeSet:
    id: add_column_change
    author: mallod
    changes:
    - addColumn:
        schemaName: example
        tableName: ex_table
        columns:
        - column:
            name: object_id
            type: UUID
            constraints:
                foreignKeyName: ex_table_object_fk
                referencedTableName: objects
                referencedTableSchemaName: example
                referencedColumnNames: id
```

In this case, the `referencesTableSchemaName` is completely ignored without my fix and output this:
```
ALTER TABLE example.ex_table ADD CONSTRAINT ex_table_object_fk FOREIGN KEY (object_id) REFERENCES objects (id);
```

instead of this:
```
ALTER TABLE example.ex_table ADD CONSTRAINT ex_table_object_fk FOREIGN KEY (object_id) REFERENCES example.objects (id);
```

Is it better?
