### ISSUE TITLE
Liquibase doesnt snapshot precision of INT types on MariaDB

### ISSUE THREAD

**Issue by LonwoLonwo** [liquibase/liquibase#3429]
## Environment

**Liquibase Version**: Latest

**Database Vendor & Version**: MySQL 8.0/ MariaDB 10.1

## Description

Tables with INT types (INT, BIGINT, etc.) loses types precisions during the diffChangeLog command execution.

As an example table with the DDL:

```sql
CREATE TABLE `test_int` (
  `Column1` int(5) NOT NULL,
  `Column2` bigint(7) DEFAULT NULL
);
```

turns to

```sql
CREATE TABLE `test_int` (
  `Column1` INT NOT NULL,
  `Column2` BIGINT DEFAULT NULL
);
```

https://github.com/liquibase/liquibase/blob/master/liquibase-core/src/main/java/liquibase/datatype/core/BigIntType.java#L51
I see that BIGINT can contain parameters but does not keep them. 
And I see that seven years ago - INT types did have parameters.
So what changed?
Maybe the new MySQL version will not have INT precisions also, but what about backward compatibility?

![2022-10-31 12_52_26-AnyDesk](https://user-images.githubusercontent.com/45152336/198994539-1c220504-8d13-4ef0-bf08-bb04df4da9ec.png)

**Comment by FBurguer** [comment]
For this issue I checked on MariaDB, and as you mention, the precision is no being snapshoted, this problem is not exclusive to diff-changelog or diff commands. 
 ```
   <changeSet author="FBurguer" id="1">
        <createTable tableName="test">
            <column name="Column1" type="INT">
                <constraints nullable="false"/>
            </column>
            <column defaultValueComputed="NULL" name="Column2" type="BIGINT"/>
        </createTable>
    </changeSet>
```
![image](https://user-images.githubusercontent.com/90205432/199271269-c41a42c2-8504-4d29-b501-586651948b85.png)
We will have a look into this. Thanks for submitting this issue!

**Comment by FBurguer** [comment]
I changed the title to MariaDB, beacause MySQL doesnt support precision so we are not able to capture that.

**Comment by LonwoLonwo** [comment]
Thanks for the investigation @FBurguer

**Comment by kevin-atx** [comment]
@tati-qalified - could you please retest this issue with the Liquibase master branch build to see if it has been fixed?

**Comment by tati-qalified** [comment]
I've tested this issue with master branch version (as of 20/7/2023) and have found that it is still not working, plus I discovered another bug (that wasn't happening before).

**Steps to reproduce**
Table creation:
![image (3)](https://github.com/liquibase/liquibase/assets/135264316/b45944a9-24a4-48c2-941e-65a658627fc1)
![image (4)](https://github.com/liquibase/liquibase/assets/135264316/50ecb368-051e-4e83-aabf-cb203f300524)

Database snapshot:
```
Catalog: intuser_db
    liquibase.structure.core.Table:
        test_int
            columns: 
                Column1
                    nullable: false
                    order: 1
                    type: INT
                Column2
                    defaultValue: NULL
                    nullable: true
                    order: 2
                    type: BIGINT
            default_tablespace: false
```

----Note that there's no precision specified.

Diff-changelog:
![image (6)](https://github.com/liquibase/liquibase/assets/135264316/763d1378-3f5b-4141-85dd-47d72c1741a7)

----There's no precision, plus the column defined as "null" generates the incorrect syntax "null null"

This issue will need to be reviewed.
