### ISSUE TITLE
addColumn ignores deleteCascade=true

### ISSUE THREAD

**Issue by Mahoney** [liquibase/liquibase#3516]
## Environment

**Liquibase Version**: 4.17.2

**Liquibase Integration & Version**: Library call

**Liquibase Extension(s) & Version**:  N/A

**Database Vendor & Version**: Postgresql 11

**Operating System Type & Version**:

**Infrastructure Type/Provider**: AWS

## Description

The following YAML:
```yaml
databaseChangeLog:

  - changeSet:
      id: an_id
      author: an_author
      changes:

        - addColumn:
            tableName: INVITATIONS
            columns:
              - column:
                  name: ORGANISATION_ID
                  type: BIGINT
                  constraints:
                    foreignKeyName: FK_INVITATION_ORGANISATION
                    referencedTableName: ORGANISATIONS
                    referencedColumnNames: ORGANISATION_ID
                    deleteCascade: true
```

does not generate the expected `ON DELETE CASCADE` in the foreign key creation.

It should. The documentation for [addColumn](https://docs.liquibase.com/change-types/add-column.html) references the documentation for [column](https://docs.liquibase.com/concepts/changelogs/attributes/column.html) which documents the [Constraints sub-tag](https://docs.liquibase.com/concepts/changelogs/attributes/column.html#Constraints%20sub-tag:~:text=Constraint%20definitions-,Constraints%20sub%2Dtag,-The%20%3Cconstraints%3E) as containing `deleteCascade`.
