### ISSUE TITLE
liquibase validate problem

### ISSUE THREAD

**Issue by ramarro123** [liquibase/liquibase#3519]
hello, using liquibase latest version (Liquibase 4.17.2)
the commant liquibase validate return SUCCESS even if i expect a failure due to missing author (required param) in changelog file.

offending block

```
databaseChangeLog:
  - changeSet:
      id:  tag_0.1.232
      changes:
        - tagDatabase:
           tag: tag_0.1.232
```

that should be marked as invalid
