### ISSUE TITLE
Can't loadData into Postgres's JSON column 

### ISSUE THREAD

**Issue by emeraldhieu** [liquibase/liquibase#3532]
## Environment

**Liquibase Version**:

4.17.2

**Database Vendor & Version**:

PostgreSQL 42.5.1

## Description

Can't loadData from CSV into JSON column.

## Steps To Reproduce

db.changelog-v1.yml
```yml
  - changeSet:
      id: initialOrders
      author: emeraldhieu
      changes:
        - loadData:
            tableName: orders
            columns:
              - column:
                  header:  User ID
                  name:  user_id
                  type:  numeric
              - column:
                  header:  Products
                  name:  products
                  type:  clob
              - column:
                  header:  Created by
                  name:  created_by
                  type:  bigint
              - column:
                  header:  Created at
                  name:  created_at
                  type:  timestamp
              - column:
                  header:  Updated by
                  name:  updated_by
                  type:  bigint
              - column:
                  header:  Updated at
                  name:  updated_at
                  type:  timestamp
            encoding:  UTF-8
            file:  liquibase/data/order.csv
            usePreparedStatements:  true
```

order.csv
```csv
User ID,Products,Created by,Created at,Updated by,Updated at
1,"[""pizza"", ""burger"", ""pasta""]",1,2022-11-23,2,2022-11-24
```

## Actual Behavior

```
Caused by: java.net.URISyntaxException: Illegal character in opaque part at index 39: resourceaccessor:liquibase/changelogs/["pizza",%20"burger",%20"pasta"]
```

## Expected/Desired Behavior

JSON data should be inserted into JSON column

---
When I use type "other",

```yml
              - column:
                  header:  Products
                  name:  products
                  type:  other
```

it shows
```
Caused by: org.postgresql.util.PSQLException: ERROR: column "created_by" is of type bigint but expression is of type character varying
  Hint: You will need to rewrite or cast the expression.
```

When I remove the `usePreparedStatements:  true`, it works.

```yaml
              - column:
                  header:  Products
                  name:  products
                  type:  other
          usePreparedStatements:  true
```

Why is that? What is the correct way of loading data for JSON column?
