### ISSUE TITLE
Error "Incorrect syntax near ‘GO’" on SQL Server when having two backslashes in one line

### ISSUE THREAD

**Issue by KlugerSteffen** [liquibase/liquibase#3687]
## Environment

**Liquibase Version**:
Liquibase Version: 4.18.0
Liquibase Community 4.18.0 by Liquibase

**Liquibase Integration & Version**: <Pick one: CLI, maven, gradle, spring boot, servlet, etc.>

**Liquibase Extension(s) & Version**: 

**Database Vendor & Version**:
Microsoft SQL Server 2017 (RTM-CU28) (KB5008084) - 14.0.3430.2 (X64)   Dec 17 2021 14:30:27   Copyright (C) 2017 Microsoft Corporation  Developer Edition (64-bit) 
**Operating System Type & Version**:
Windows Server 2019 Datacenter 10.0 <X64> (Build 17763: ) (Hypervisor) 

**Infrastructure Type/Provider**: <AWC, GCS, Azure, VM, etc>
Azure, reproduces on On-Prem vmWare

## Description
Valid Sql (if run with SSMS) returns error: Incorrect syntax near ‘GO’ 
Stored Procedure with 250 lines failed to deploy.

Narrowed down to line: 
`IF (SELECT TOP 1 ISNULL(CHARINDEX( p.shortcut + '\', l.content +'\', 0), -1) FROM @LoeschpaketTable l LEFT JOIN meta..Pub4Live p ON p.pubId = l.pubid) <> 1`
Removing this line or splitting into multiple lines solved the error.
Further narrowed down to `SELECT '\','\'` as long as at least two `GO` separators left in file

## Steps To Reproduce
try to run the following changeset to reproduce
```
--liquibase formatted sql
--changeset demo:1 endDelimiter:GO stripComments:false
SET LANGUAGE english		
CREATE OR ALTER PROCEDURE [dbo].[demo_GO_syntax_error]
AS
BEGIN
	SELECT '\','\'
END
GO
PRINT 'OK'
GO
```

Separating the backlashes in separate lines will workaround the issue:
```
--liquibase formatted sql
--changeset demo:2 endDelimiter:GO stripComments:false
SET LANGUAGE english		
CREATE OR ALTER PROCEDURE [dbo].[demo_GO_syntax_error]
AS
BEGIN
	SELECT '\'
	,'\'
END
GO
PRINT 'OK'
GO
```

List the steps to reproduce the behavior.
- Please be precise and ensure private information is redacted
- Include things like
  - Files used - sql scripts, changelog file(s), property file(s), config files, POM Files
  - Exact commands used - CLI, maven, gradle, spring boot, servlet, etc.

AzurePipeline.yaml
```
steps:
- task: DockerInstaller@0
  inputs:
    dockerVersion: '17.09.0-ce'
- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      docker run --rm -v $(Build.Repository.LocalPath)/.liquibase:/liquibase/changelog liquibase/liquibase --username=$(SQLUSERNAME) --password=$SQLPASSWORD --url=$(dbconnection) --defaultsFile=/liquibase/changelog/liquibase.properties update
  env:
    SQLPASSWORD: $(sqlpassword)
```
    
liquibase.properties:
```
classpath=/liquibase/changelog
changeLogFile=dbchangelog.yaml
logging.level.liquibase=INFO
liquibase.hub.mode=OFF
liquibase.defaultCatalogName=import
liquibase.liquibaseCatalogName=import
liquibase.liquibaseSchemaName=liquibase
liquibase.databaseChangeLogTableName=DATABASECHANGELOG
liquibase.databaseChangeLogLockTableName=DATABASECHANGELOGLOCK
```
dbchangelog.yaml:
```
databaseChangeLog:

- includeAll:
    path: /sql
    errorIfMissingOrEmpty: true
```

## Actual Behavior
A clear and concise description of what happens in the software with the **version used**.
- Include console output if relevant
- Include log files if available.

## Expected/Desired Behavior
A clear and concise description of what happens in the software **after** a fix is created and merged.
