### ISSUE TITLE
Extra index on primary key column is not found

### ISSUE THREAD

**Issue by thehpi** [liquibase/liquibase#3700]
## Environment

**Liquibase Version**: 4.18.0

**Liquibase Integration & Version**: CLI

**Liquibase Extension(s) & Version**: none

**Database Vendor & Version**: PostgreSQL 13.5

**Operating System Type & Version**: MacOS Ventura 13.0.1

**Infrastructure Type/Provider**: Postgres in Docker, liquibase installed using brew on local machine

## Description

When a table has a primary key on a column A and another index (unique or not) on the same column then this is not recognized by liquibase. It simply skips the extra indices.

## Steps To Reproduce

Example:

Put this in docker-compose.yml

```
version: '3.9'
services:
  db:
    image: postgres:13.5-alpine
    environment:
      - POSTGRES_PASSWORD=db
      - POSTGRES_USER=db
      - POSTGRES_DB=db
    ports:
      - "15432:5432"
    command: postgres -c max_prepared_transactions=250 -c max_connections=200
```

Start the database using

```
docker-compose up -d
```

Use e.g. psql to run the following:

```
create table table1
(
    id char(32) not null,
    primary key (id)
);

create unique index idx_id1 on table1 (id);
create index idx_id2 on table1 (id);
```

Get the postgresql driver:

```
wget https://jdbc.postgresql.org/download/postgresql-42.5.1.jar
```

Now produce a changelog file using liquibase:

```
liquibase --classPath="postgresql-42.5.1.jar" --driver="org.postgresql.Driver" --username="db" --password="db" --url="jdbc:postgresql://localhost:15432/db" --changeLogFile=changelog.yaml generate-changelog
```

## Actual Behavior
I would expect that the changelog file would contain the indexes idx_id1 and idx_id2.

## Expected/Desired Behavior
This is the contents of the changelog.yaml file

```
databaseChangeLog:
- changeSet:
    id: 1673952176641-1
    author: hpi (generated)
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: table1_pkey
            name: id
            type: CHAR(32)
        tableName: table1
```

The indices are missing

## Additional Context
I think this is some 'smart' function of liquibase where it knows that the indices are useless because there is already a primary key. But I can't find anything about it in the docs. I also think it is inappropriate to do this.
