### ISSUE TITLE
Precondition fails on check for "public.databasechangeloglock" exists

### ISSUE THREAD

**Issue by pscherer-rmbs** [liquibase/liquibase#3896]
### Search first

- [X] I searched and no similar issues were found

### Description

It appears that the latest version 4.19.1 may have introduced a regression with a precondition check failure. This occurs when the liquibase related tables have not been created on first changelog execution and there is a precondition that does a select count on the "databasechangeloglock" table:

```text
liquibase update --changelog-file changelog.yaml --url jdbc:postgresql://localhost:5432/postgres
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 13:04:43 (version 4.19.1 #7641 built at 2023-02-28 18:08+0000)
Liquibase Version: 4.19.1
Liquibase Open Source 4.19.1 by Liquibase
Validation Error:
     1 preconditions generated an error
          changelog.yaml : liquibase.precondition.core.SqlPrecondition@1416cf9f : ERROR: relation "public.databasechangeloglock" does not exist
  Position: 22

Unexpected error running Liquibase: Validation Failed:
     1 preconditions generated an error
     changelog.yaml : liquibase.precondition.core.SqlPrecondition@1416cf9f : ERROR: relation "public.databasechangeloglock" does not exist
  Position: 22
```

The changelog file referenced works with the previous version 4.19.0.

### Steps To Reproduce

`liquibase update --changelog-file changelog.yaml --url jdbc:postgresql://localhost:5432/postgres`

changelog.yaml

```yaml
databaseChangeLog:
  - preConditions:
      - onFail: HALT
      - sqlCheck:
          expectedResult: 1
          sql: select count(*) from public.databasechangeloglock
  - changeSet:
      id: 1
      author: pscherer
      changes:
        - sql:
            endDelimiter: ;
            sql: CREATE SCHEMA test
```

### Actual Behavior

Precondition failure occurs and halts the execution of applying the changelog.

### Expected/Desired Behavior

Changelog file is applied successfully.

### Liquibase Version

4.19.1

### Database Vendor & Version

Postgresql 15.2_3

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

MacOS 13.2.1

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
