### ISSUE TITLE
MSSQL: Column of type `timestamp with time zone` should be created as `datetimeoffset` instead of `datetime2`

### ISSUE THREAD

**Issue by phjardas** [liquibase/liquibase#4091]
### Search first

- [X] I searched and no similar issues were found

### Description

When creating a column with datatype `timestamp with time zone` in a MS SQL database, it is created with the native type `datetime2`. However, [this datatype](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetime2-transact-sql) is just a local date/time that does not include any timezone information. Instead, the correct data type would be `datetimeoffset`, which [does include timezone](https://learn.microsoft.com/en-us/sql/t-sql/data-types/datetimeoffset-transact-sql).

I'd be happy to provide a PR to fix the [type generation](https://github.com/liquibase/liquibase/blob/214ec0509fc0815b3744a13609fec03e7fe00553/liquibase-core/src/main/java/liquibase/datatype/core/TimestampType.java#L68-L85).

### Steps To Reproduce

Create a changelog for a MS SQL database:

```yaml
databaseChangeLog:
  - changeSet:
      id: test
      author: test
      changes:
        - createTable:
            tableName: test
            columns:
              - column:
                  name: timestamp
                  type: timestamp with time zone
```

The column will be created as `datetime2`.

### Expected/Desired Behavior

The column should instead be created as `datetimeoffset`.

### Liquibase Version

4.17.2

### Database Vendor & Version

MS SQL

### Liquibase Integration

any

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

irrelevant

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)
