### ISSUE TITLE
Feature Request: relativeToChangelogFile on changelog level

### ISSUE THREAD

**Issue by rlconst** [liquibase/liquibase#4385]
### Search first

- [X] I searched and no similar issues were found

### Description

Currently yaml has a lot of copypaste:
```
databaseChangeLog:
  - include:
      file: a.yml
      relativeToChangelogFile: true
  - ...
  - include:
      file: z.yml
      relativeToChangelogFile: true
```
I propose to have more compact version to replicate include properties on changelog level. of course you should be able to override if you want
```
databaseChangeLog:
  relativeToChangelogFile: true
  include-files:
      - a.yml
      - ...
      - z.yml
```
or more similar to what exists now
```
databaseChangeLog:
  relativeToChangelogFile: true
  include:
     files:
         - a.yml
         - ...
         - z.yml
```

### Steps To Reproduce

Not applicable

### Expected/Desired Behavior

Not applicable

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)
