### ISSUE TITLE
Using 4.23.0, my app fails to start because of invalid checksums

### ISSUE THREAD

**Issue by jbisotti** [liquibase/liquibase#4457]
### Search first

- [X] I searched and no similar issues were found

### Description

Our application (Java/Spring/MySQL) is currently using 4.20.0 and works fine. When I upgrade to 4.23.0, it fails to start due to Liquibase failing due to invalid checksums.

```
	Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.ValidationFailedException: Validation Failed:
     1 changesets check sum
          org/foo/db/phase5/foo-bar-2017-09-14.xml::DECREASE_FP_FIELD_FOR_PDP::jdoe was: 8:83871094f06fbeba7a3755bb6e7980c0 but is now: 8:7afe9a1d89ce253fbca2d513dcdc2834
```

### Steps To Reproduce

The offending changeset (names changed to protect the innocent):

```xml
    <changeSet author="jdoe" id="DECREASE_FP_FIELD_FOR_PDP" context="bootstrap,demo,unit">
        <comment>Words words words. Please review if your institution would like this change. See JIRA-123 for details.</comment>

        <sql dbms="mysql">
            update FP_DV_PAYEE_DTL_T A join FP_DV_PAYEE_DTL_T B ON A.FDOC_NBR = B.FDOC_NBR set A.DV_RMT_PRSN_NM = SUBSTR(B.DV_RMT_PRSN_NM,1,75);
        </sql>

        <sql dbms="oracle">
            update FP_DV_PAYEE_DTL_T A set DV_RMT_PRSN_NM = (select SUBSTR(DV_RMT_PRSN_NM,1,75) from FP_DV_PAYEE_DTL_T B where A.FDOC_NBR = B.FDOC_NBR);
        </sql>

        <modifyDataType columnName="DV_RMT_PRSN_NM" newDataType="VARCHAR(75)" tableName="FP_DV_PAYEE_DTL_T"/>
    </changeSet>
```

### Expected/Desired Behavior

My app would startup like it does with 4.20.0.

### Liquibase Version

4.23.0

### Database Vendor & Version

MySQL 5.7

### Liquibase Integration

Spring (not Boot)

### OS and/or Infrastructure Type/Provider

macOS

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by kevin-atx** [comment]
@filipelautert  - passing this along to you since it's likely related to the 4.23.0 checksum change

**Comment by filipelautert** [comment]
Hello @jbisotti - I saw you're using 2 dbms tags within the same changeset so your problem is related to the 4.23.0 bug that will be fixed by PR https://github.com/liquibase/liquibase/pull/4453 .
Meanwhile there are 3 workarounds to upgrade:

1. add tag` <validCheckSum>1:any</validCheckSum> `to your changeset, upgrade to 4.23.0 then remove it.
2. run `clearChecksums ` command and then upgrade.
3. Update db changelog table using the new checksum: `update databasechangelog set md5sum = '8:7afe9a1d89ce253fbca2d513dcdc2834' where md5sum = '8:83871094f06fbeba7a3755bb6e7980c0' .`

**Comment by filipelautert** [comment]
@jbisotti I took a better look at PR https://github.com/liquibase/liquibase/pull/4453 and it wo'nt fix your checksum problem - it only fixes a bug with your setup in 4.23.0.  So I would suggest for you to just upgrade after that PR is merged as if you use changesets in the same way you set up your example one (2 different dbms on the same changeset) they may not be executed.

**Comment by jacokok** [comment]
We have same problem but it gets new md5sum every time we run update-testing-rollback.

It only happens on changesets where we are using parameters in liquibase.properties file.

Will this be resolved by same fix or should I create new issue?

**Comment by filipelautert** [comment]
Hello @jacokok ! Does it solve your problems if you try any of the steps above? Just trying to understand what would be the correct pr for it.

**Comment by jacokok** [comment]
It fixes it until I run `liquibase update-testing-rollback` then it gives me the old md5sum again.

Currently we need to follow the steps above every time we run `liquibase update` after `liquibase update-testing-rollback` was executed.

**Comment by jacokok** [comment]
This happens on change types where we are using properties like `${databaseName}` in this example.
After rollback it will have new md5sum. When you clear md5sum it runs fine until the next rollback. 

```yaml
  - changeSet:
      id: memoryFile
      author: Redacted
      comment: Add File To Use In Memory Types
      runInTransaction: false
      changes:
        - sql:
            sql: |
              IF NOT EXISTS(SELECT TOP 1 1 FROM sys.database_files WHERE name = '${databaseName}_Memory')
              BEGIN
                ALTER DATABASE CURRENT ADD FILE (name='${databaseName}_Memory', filename='${memoryFile}') TO FILEGROUP FirstMap_Memory                 
              END
      rollback: empty
```

```properties
parameter.databaseName=DatabaseName
```

For now I added the below to solve issue.

```yaml
    validCheckSum:
      - "1:any"
```
