### ISSUE TITLE
Liquibase does not use "WITH VALUES" for addColumn with default value in Microsoft SQL Server

### ISSUE THREAD

**Issue by fweyerowski** [liquibase/liquibase#4644]
### Search first

- [X] I searched and no similar issues were found

### Description

I searched for similar issues and found one, but it was closed: #3417 

I have the problem described in this closed issue, that Liquibase does not set the correct default value for addColumn in Microsoft SQL Server.

The steps to reproduce described in #3417 worked for me.

Liquibase has to use "WITH VALUES" at the end of the SQL statement for addColumn with a default value, so the SQL Server will set the correct value in the table.

The Liquibase CLI log shows the following:
`[2023-08-07 11:23:45] FEIN [liquibase.executor] ALTER TABLE test.TEST ADD new_column1 nvarchar(1) CONSTRAINT DF_TEST_new_column1 DEFAULT 'T';`

### Steps To Reproduce

See #3417 for examples.

Additionaly my test changelog:
```
databaseChangeLog:
- changeSet:
    id: 1
    author: fweyerowski
    changes:
    - addColumn:
        schemaName: test
        tableName: TEST
        columns:
        - column:
            defaultValue: 'T'
            name: new_column1
            type: NVARCHAR(1)
```

You must have data in your test table to see the problem. If you only add a column to an empty table, it is not possible to see. If you have data in you table where you add the new column with a default value, you will see the new column with null values.

### Expected/Desired Behavior

Liquibase should use "WITH VALUES", so the new column gets created with the correct default value in the table.

### Liquibase Version

4.23.0

### Database Vendor & Version

Microsoft SQL Server 2019

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
