### ISSUE TITLE
feature request: generateChangelog option "addPreconditions"

### ISSUE THREAD

**Issue by hel1e** [liquibase/liquibase#4950]
### Search first

- [X] I searched and no similar issues were found

### Description

We have a situation where we wish to replace a large set of old scripts with liquibase. The old scripts may or may not have been executed, and we want it to be possible to run only liquibase in both situations.

While the generateChangelog command makes it quite easy to get the new changelogs in place, the work of adding preconditions to all changesets in order to handle both situations is a cumbersome manual process. And it should not really be necessary. I think it would be a good idea to add an option addPreconditions to this method. If the option is used, every createTable changeset should have a not tableExists precondition for the table, with onFail: MARK_RAN. And so on, for the other object types.

I hope such a feature could be added!

### Steps To Reproduce

Not relevant - this is a feature request and not a bug report.

### Expected/Desired Behavior

Say I have a database with schema `MYSCHEMA `and table `MYTABLE`, and I execute liquibase `generateChangelog`

`liquibase generateChangelog --username=xxx --password=xxx--url="xxx" --include-schema=true --diff-types="tables,columns, indexes, foreignkeys, primarykeys, uniqueconstraints" --schemas=MYSCHEMA --changelog-file=myChangelog.yaml --addPreconditions`

this should generate a changelog where the create table changeset comes with a precondition included, something like the following: 

```
- changeSet:
    id: "CREATE table MYSCHEMA.MYTABLE"
    author: author-generated
    preConditions:
      - onFail: MARK_RAN
      - not:
        - tableExists:            
            schemaName: MYSCHEMA
            tableName: MYTABLE
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
              primaryKey: true
              primaryKeyName: MYTABLE_PK
            name: ID
            remarks: Unique id
            type: RAW(16)
        remarks: Exampel table
        schemaName: MYSCHEMA
        tableName: MYTABLE
```

Similar preconditions should be added for indexes, constraints etc, for all changeset types where this is possible.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
