### ISSUE TITLE
diff: unique constraint is added before the adding the column 

### ISSUE THREAD

**Issue by asashour** [liquibase/liquibase#5030]
### Search first

- [X] I searched and no similar issues were found

### Description

On adding a new unique column, and running `diffChangelog`, `addUniqueConstraint` is added before `addColumn` which causes the changeSet to fail.

### Steps To Reproduce

1. Have a base table
2. Add a new unique column (added by Hibernate with):
```
@Column(unique = true)
private String name2;
```

4. run the diffChangelog (run programatically by):
```
new CommandScope(DiffChangelogCommandStep.COMMAND_NAME)
  .addArgumentValue(UpdateCommandStep.CHANGELOG_FILE_ARG, CHANGELOG)
  .addArgumentValue(DiffChangelogCommandStep.CHANGELOG_FILE_ARG, path.toString())
  .addArgumentValue(ReferenceDbUrlConnectionCommandStep.REFERENCE_DATABASE_ARG, referenceDatabase)
  .addArgumentValue(DbUrlConnectionCommandStep.DATABASE_ARG, targetDatabase)
  .execute();
```

### Expected/Desired Behavior

`addColumn` should be generated before the `addUniqueConstraint`

Actual output:
```
databaseChangeLog:
- changeSet:
    id: 1696581129267-1
    author: author
    changes:
    - addUniqueConstraint:
        columnNames: name2
        constraintName: something_name2_key
        tableName: something
- changeSet:
    id: 1696581129267-2
    author: author
    changes:
    - addColumn:
        columns:
        - column:
            name: name2
            type: varchar(255 BYTE)
        tableName: something
```

### Liquibase Version

4.24.0

### Database Vendor & Version

PostgreSQL 15.4

### Liquibase Integration

Programmatic

### OS and/or Infrastructure Type/Provider

Windows 10

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
