### ISSUE TITLE
changelog with SqlFiles updateSql command on yaml changelogs

### ISSUE THREAD

**Issue by bashar-alasmar** [liquibase/liquibase#5044]
### Search first

- [X] I searched and no similar issues were found

### Description

Im using liquibase for migrating and updating my Databse using Azure DevOps Pipelines. 
The way i'm using it, i have the following structure 
Scripts/
   Ticket_#/*.sql 
   Ticket_#/*.sql
 
So in my case im using the changelog like the following 

```
- changeSet:
    author: bashar.alasmar@equiti.com
    changes:
    - sqlFile:
        endDelimiter: GO
        path: Scripts/Ticket_13/01.accountservice.schema.sql
    id: Ticket_13_01.accountservice.schema.sql
    rollback:
    - sqlFile:
        endDelimiter: GO
        path: Scripts/Ticket_13/rollBackScripts/01.accountservice.schema.rollback.sql
```
        
        

What im trying to make **liquibase update-sql** , the expected behavior to show me if there's an error with my sql scripts before i apply to the database, however i only get whats going to be executed. 

But when i do **liquibase update**  it does show that the accountServiceSchema already exisits. 

So my question does **liquibase update-sql** supports taking the changes from my sql scripts? 

If not is there a different way to be able to do a dry-run for the way im using liquibase? 

Thank you in advance.

### Steps To Reproduce

When i run **liquibase update**-sql the below changeset, it should through an error that the accountservice schema already exists, instead it just shows whats going to be executed 

```
- changeSet:
    author: AuthorName
    changes:
    - sqlFile:
        endDelimiter: GO
        path: Scripts/Ticket_13/01.accountservice.schema.sql
    id: Ticket_13_01.accountservice.schema.sql
    rollback:
    - sqlFile:
        endDelimiter: GO
        path: Scripts/Ticket_13/rollBackScripts/01.accountservice.schema.rollback.sql
```
        
  

### Expected/Desired Behavior

I want the following  behavior with doing the **liquibase update-sql** , not just on **liquibase update**
```
- changeSet:
    author: authorName
    changes:
    - sqlFile:
        endDelimiter: GO
        path: Scripts/Ticket_13/01.accountservice.schema.sql
    id: Ticket_13_01.accountservice.schema.sql
    rollback:
    - sqlFile:
        endDelimiter: GO
        path: Scripts/Ticket_13/rollBackScripts/01.accountservice.schema.rollback.sql
```

Unexpected error running Liquibase: Migration failed for changeset changeLogs/Products-CICD-DEV-changlog.yaml::Ticket_13_01.accountservice.schema.sql::authorName:
     Reason: liquibase.exception.DatabaseException: There is already an object named 'accountservice' in the database. [Failed SQL: (2714) CREATE SCHEMA [accountservice];]

### Liquibase Version

'4.23.0'

### Database Vendor & Version

SQL server 12..2000.8

### Liquibase Integration

CLI

### Liquibase Extensions

no extensions

### OS and/or Infrastructure Type/Provider

Ubuntu-latest

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
