### ISSUE TITLE
Preconditions onErrorMessage does not work

### ISSUE THREAD

**Issue by hel1e** [liquibase/liquibase#5067]
### Search first

- [X] I searched and no similar issues were found

### Description

I need to check that a database link (oracle dbms) exists and works, and if it is missing or not working I want to give a proper error message to the user. Instead of the message written in onErrorMessage and onFailMessage, I only get the oracle error.

We are using Version 4.24.0

Unexpected error running Liquibase: Validation Failed:
     1 preconditions generated an error
     changelog.yaml : liquibase.precondition.core.SqlPrecondition@4120dc7d : ORA-12545: Tilkoblingen mislyktes fordi målvert eller målobjekt ikke finnes

### Steps To Reproduce

```yaml
databaseChangeLog:
- preConditions:
    - onError: HALT
    - onFail: HALT
    - onErrorMessage: The database link MY_DB_LINK must be defined correctly, currently it is failing or missing
    - onFailMessage: The database link MY_DB_LINK must be defined correctly, currently it is failing or missing
    - sqlCheck:
       expectedResult: 1
       sql: SELECT 1 from dual@MY_DB_LINK
```

I have also tried the same using xml changelog format, with the same result. 

In the database you are testing against, run two tests
a) MY_DB_LINK does not exist. 
this causes error message :
```
Unexpected error running Liquibase: Validation Failed:
     1 preconditions generated an error
     changelog.yaml : liquibase.precondition.core.SqlPrecondition@4120dc7d : ORA-12545: Connect failed because target host or object does not exist
```
     
b) Create database link MY_DB_LINK with "wrong" setup: 
   create public database link MY_DB_LINK connect to no_such_user identified by "wrong-password" using 'no_such_db';
   
this causes error message: 
```
Unexpected error running Liquibase: Validation Failed:
     1 preconditions generated an error
     changelog.yaml : liquibase.precondition.core.SqlPrecondition@4120dc7d : ORA-12154: TNS: could not resolve service name  
``` 
  

### Expected/Desired Behavior

I expect to get the errormessage defined in the precondition when it fails.

### Liquibase Version

4.24.0

### Database Vendor & Version

Oracle 19c

### Additional Context

We run this using a docker image based on liquibase:4.24.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
