### ISSUE TITLE
Liquibase loadData fails to insert UUID in mysql

### ISSUE THREAD

**Issue by gnu-lorien** [liquibase/liquibase#5145]
### Search first

- [X] I searched and no similar issues were found

### Description

When using loadData to load a UUID into a column in MySQL setting the type of the column in loadData causes the following failure when inserting the data:

`Caused by: liquibase.exception.DatabaseException: java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'policy_id' at row 1`

If you change the type of the column in loadData to `STRING` this data is able to load, but that can cause issues for other dbms that need different special handling for uuids. In particular, the documentation here https://docs.liquibase.com/workflows/liquibase-community/working-with-uuids.html implies that using uuid as the conversion type is the correct one.

### Steps To Reproduce

I created a table with initial data on a MySQL database using the following files:

```
databaseChangeLog:
- changeSet:
    author: asayman
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
              primaryKey: true
              unique: false
            name: policy_id
            type: UUID
        tableName: ProductPolicy
    - modifySql:
        dbms: mysql
        replace:
          replace: NVARCHAR(100)
          with: VARCHAR(100) CHARACTER SET UTF8MB4
    - loadData:
        columns:
        - column:
            header: policy_id
            name: policy_id
            type: uuid
        encoding: UTF-8
        file: ../changelog-initial-data/001-product-policy.csv
        quotechar: ''''
        relativeToChangelogFile: true
        separator: ','
        tableName: ProductPolicy
    id: 000-table-productpolicy
```

```
policy_id
1872003c-2b7c-4678-994a-0ff3c24f4797
e231b4aa-3d37-4736-9459-1d6f1e469e33
825bf43d-45fd-4a49-8820-1164bde70830
0fef3af7-efbd-4ef1-91b6-10ea32e02c9f
e1c07c47-59ec-4f14-b6a2-a1879c764d97
f0d1243b-0d3b-4b14-8336-9cd1c4de3176
651e2feb-46b9-4983-b463-dad8e2ff6816
5fdb4863-0872-4b69-9213-9938cd9c138f
```

which results in the following error:

```
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ## 
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ## 
##                                                ##
####################################################
Starting Liquibase at 14:46:31 (version 4.24.0 #14062 built at 2023-09-28 12:18+0000)
Liquibase Version: 4.24.0
Liquibase Open Source 4.24.0 by Liquibase
Running Changeset: changelog-tables/050-052-table-productpolicy.yaml::050-052-000-table-productpolicy::asayman

Unexpected error running Liquibase: Migration failed for changeset changelog-tables/050-052-table-productpolicy.yaml::050-052-000-table-productpolicy::asayman:
     Reason: liquibase.exception.DatabaseException: java.sql.SQLException: Incorrect string value: '\xAC\xED\x00\x05sr...' for column 'policy_id' at row 1
```

If you change the above yaml file to the following, there is no error:

```
databaseChangeLog:
- changeSet:
    author: asayman
    changes:
    - createTable:
        columns:
        - column:
            constraints:
              nullable: false
              primaryKey: true
              unique: false
            name: policy_id
            type: UUID
        tableName: ProductPolicy
    - modifySql:
        dbms: mysql
        replace:
          replace: NVARCHAR(100)
          with: VARCHAR(100) CHARACTER SET UTF8MB4
    - loadData:
        columns:
        - column:
            header: policy_id
            name: policy_id
            type: STRING
        encoding: UTF-8
        file: ../changelog-initial-data/001-product-policy.csv
        quotechar: ''''
        relativeToChangelogFile: true
        separator: ','
        tableName: ProductPolicy
    id: 050-052-000-table-productpolicy
```

### Expected/Desired Behavior

There are no errors and the rows correctly have the UUID specified in the csv file.

### Liquibase Version

4.24.0

### Database Vendor & Version

MySQL Server 8.1.0-1.el8

### OS and/or Infrastructure Type/Provider

Ubuntu 22.04.3 LTS

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
