### ISSUE TITLE
Liquibase's UUID type with mariadb doesn't use mariadb's UUID type

### ISSUE THREAD

**Issue by Aikain** [liquibase/liquibase#5263]
### Search first

- [X] I searched and no similar issues were found

### Description

When I use liquibase with spring-boot and MariaDB and I try to use UUID-type, I get error:

> Caused by: org.hibernate.tool.schema.spi.SchemaManagementException: Schema-validation: wrong column type encountered in column [id] in table [item]; found [char (Types#CHAR)], but expecting [binary(16) (Types#BINARY)]

I have hibernate's validate enabled because want to be sure that didn't miss anything.

```yaml
spring:
  jpa:
    hibernate:
      ddl-auto: validate
```

### Steps To Reproduce

Item.java:
```java
@Entity
public class Item extends AbstractPersistable<UUID> {}
```

changelog-root.yml:
```yaml
databaseChangeLog:
  - changeSet:
      id: example
      author: Aikain
      changes:
        - createTable:
            tableName: item
            columns:
              - column:
                  name: id
                  type: UUID
```

application.yml:
```yaml
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/example
    username: root
    password: CHANGEME
  liquibase:
    change-log: db/changelog-root.yml
  jpa:
    hibernate:
      ddl-auto: validate
```

Full example: https://github.com/Aikain/SpringBootLiquibase

### Expected/Desired Behavior

When specify `type: UUID` and database is MariaDB, use MariaDB's UUID type.

Available since 10.7: https://mariadb.com/kb/en/uuid-data-type/

### Liquibase Version

4.25.0

### Database Vendor & Version

MariaDB 1:11.1.2+maria~ubu2204

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

Windows 11 + WSL2 + Docker

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)
