### ISSUE TITLE
Liquibase is failing when a file doesn't exist even if the changeset is filtered and should not be executed

### ISSUE THREAD

**Issue by pkernevez** [liquibase/liquibase#5430]
### Search first

- [X] I searched and no similar issues were found

### Description

I have different contexts in my project.
Only some of them should insert data in the DB (like dev or test env), and I create csv data files only for them.
When running liquibase with other contexts it fails because the data files doesn't exist.

It works as expected with release before Before 4.19.1. I test it with docker images (cf bellow), and it's ok with 4.19.0 and it's broken with 4.19.1.

### Steps To Reproduce

My liquibase conf folder:
|-> change-log.yml
|-> liquibase.properties
|---> data
   |-> data-context1.csv

With the content:
* change-log.yml
```yaml
databaseChangeLog:
  -  property:
       name:  data_file
       context: test1
       value:  data-context1
  -  property:
       name:  data_file
       context: test2
       value:  data-context2

  - changeSet:
      id: 0 - Bug with file missing for non active context
      author: Me
      changes:
        - createTable:
            tableName: TEST
            columns:
              - column:
                  name: ID
                  type: int
                  constraints:
                    primaryKey: true
                    nullable: false
  - changeSet:
      id: 1 - Bug, without this context file should not have to exist
      author: Me
      context: "invalidcontext"
      changes:
        - loadData:
            encoding: UTF-8
            file: "data/${data_file}.csv"
            separator: ","
            tableName: TEST
```
* data-context1.csv
```csv
ID
1
2
```

When running with context filter 'test1', it runs and filter the data as expected:
```log
Starting Liquibase at 17:26:24 (version 4.24.0 #14062 built at 2023-09-28 12:18+0000)
Liquibase Version: 4.24.0
Liquibase Open Source 4.24.0 by Liquibase
Running Changeset: change-log.yml::0 - Bug with file missing for non active context::Me

UPDATE SUMMARY
Run:                          1
Previously run:               0
Filtered out:                 1
-------------------------------
Total change sets:            2


FILTERED CHANGE SETS SUMMARY
Context mismatch:             1
```

But when running with context2:
```log
Starting Liquibase at 17:25:15 (version 4.24.0 #14062 built at 2023-09-28 12:18+0000)
Liquibase Version: 4.24.0
Liquibase Open Source 4.24.0 by Liquibase

Unexpected error running Liquibase: The file data/data-context2.csv was not found in the configured search path:
    - /liquibase/changelog
More locations can be added with the 'searchPath' parameter.

For more information, please use the --log-level flag
```
And of course if I create a file `data/data-context2.csv`, it succeeds without using it. 

As I explained, this is a regression introduce by the release 4.19.1:
```log
> docker run --rm -v (PWD):/liquibase/changelog  liquibase/liquibase:4.19.0 --defaultsFile=/liquibase/changelog/liquibase.properties update                                                                             (base)
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 17:49:47 (version 4.19.0 #6648 built at 2023-01-17 15:02+0000)
Liquibase Version: 4.19.0
Liquibase Open Source 4.19.0 by Liquibase
Running Changeset: change-log.yml::0 - Bug with file missing for non active context::Me
Liquibase command 'update' was executed successfully.


# Retarts a brand new db...

> docker run --rm -v (PWD):/liquibase/changelog  liquibase/liquibase:4.19.1 --defaultsFile=/liquibase/changelog/liquibase.properties update                                                                               (base)
####################################################
##   _     _             _ _                      ##
##  | |   (_)           (_) |                     ##
##  | |    _  __ _ _   _ _| |__   __ _ ___  ___   ##
##  | |   | |/ _` | | | | | '_ \ / _` / __|/ _ \  ##
##  | |___| | (_| | |_| | | |_) | (_| \__ \  __/  ##
##  \_____/_|\__, |\__,_|_|_.__/ \__,_|___/\___|  ##
##              | |                               ##
##              |_|                               ##
##                                                ##
##  Get documentation at docs.liquibase.com       ##
##  Get certified courses at learn.liquibase.com  ##
##  Free schema change activity reports at        ##
##      https://hub.liquibase.com                 ##
##                                                ##
####################################################
Starting Liquibase at 17:50:37 (version 4.19.1 #7641 built at 2023-02-28 18:08+0000)
Liquibase Version: 4.19.1
Liquibase Open Source 4.19.1 by Liquibase

Unexpected error running Liquibase: The file data/data-context2.csv was not found in the configured search path:
    - /liquibase/changelog
More locations can be added with the 'searchPath' parameter.

For more information, please use the --log-level flag
```

### Expected/Desired Behavior

I expect to not fail when a changeset is filtered.

### Liquibase Version

Since 4.19.1 and still true with 4.25.0

### Database Vendor & Version

Potgresql 16

### Liquibase Integration

docker & maven

### OS and/or Infrastructure Type/Provider

maven on mac os and cli with docker container.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
