### ISSUE TITLE
Backward compatibility of createProcedure is broken

### ISSUE THREAD

**Issue by sbklahr** [liquibase/liquibase#5475]
### Search first

- [X] I searched and no similar issues were found

### Description

I have a couple of changesets that where executed with older Liquibase versions such as 4.9.1. I migrated to Liquibase 4.25.1 and encountered checksum errors (#4156). After running `clear-checksums` everything works again for existing db schemas created by Liquibase. When I run my changesets with 4.25.1 on an empty database however, I get the following `ValidationFailedException`:

`Must specify either 'path' or a nested procedure text in createProcedure, [...]`

The problem is, that my procedure changesets still contain `procedureBody` instead of `procedureText`.

### Steps To Reproduce

Execute the following new changeset with Liquibase 4.25.1
```yaml
databaseChangeLog:
    - changeSet:
      id: 1
      author: user
      dbms: mssql
      changes:
        - createProcedure:
            procedureBody: |-
              CREATE PROCEDURE dbo.MyProc
              AS
              BEGIN
              SET NOCOUNT ON;
              SELECT * FROM dbo.mytable
              END
            procedureName: MyProc
            replaceIfExists: true
```

### Expected/Desired Behavior

The old `procedureBody` property should be recognized by newer Liquibase versions.

### Liquibase Version

4.25.1

### Liquibase Integration

spring boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
