### ISSUE TITLE
Allow custom checksum calculations for CustomChange

### ISSUE THREAD

**Issue by robinjhector** [liquibase/liquibase#5478]
### Search first

- [X] I searched and no similar issues were found

### Description

Hello!

We're utilising `CustomSqlChange` in order to handle trickier SQL migrations. Some snippets of the SQL is generated from code, and the intent was to have a changeset to be re-ran when the corresponding code changes.

However, when drilling down and examining how to get `runOnChange` to work for us, we found that the checksum calculations for CustomSqlChange is pretty bare-bones.

My changelog file looks as follows:

```yaml
databaseChangeLog:
  - includeAll:
      path: db/changesets/
  - changeSet:
      id: MyCustomView
      author: robin
      runOnChange: true
      changes:
        - customChange:
            class: com.example.code.MyCustomViewChange
```

The default checksum calculations for CustomChange seems to be based off of the class name, (and potential parameters you can set via the xml/yaml).

### Alternative 1

I think it would be super nice to have an additional interface (kind of like the optional `CustomSqlRollback` interface), in order to generate a custom checksum. (In our use case we would probably MD5 the resulting SQL statements. Meaning if the code changes, so does our own calculation of checksum)

### Alternative 2
Another approach would be to change the checksum calculations for `CustomSqlChange`, to actually hash the generated statements. (And not just the classname and params). But this would be considered breaking, so perhaps not desired.

### Steps To Reproduce

N/A; Feature request

### Expected/Desired Behavior

A smarter checksum calculation for custom sql changes.

### Liquibase Version

4.24.0

### Database Vendor & Version

PostgreSQL 15

### Liquibase Integration

Spring Boot

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)
