### ISSUE TITLE
System timezone changes generated checksums for YAML change logs that doesn't specify timezone for TIMESTAMP columns 

### ISSUE THREAD

**Issue by muhammednursoy** [liquibase/liquibase#5499]
### Search first

- [X] I searched and no similar issues were found

### Description

If a YAML change log  contains an insert for a TIMESTAMP column but doesn't specify the timezone, Liquibase generates different checksums when  system timezone changes.

### Steps To Reproduce

1. Create a change log which contains an TIMESTAMP column insert but doesn't specify timezone
2. Run change log 
3. Change system timezone to something other than current value
4. Run change log once more
5. Change log fails due to different checksums

### Expected/Desired Behavior

System timezone have no effect on Liquibase checksums when timezone is not specified in YAML change logs

### Liquibase Version

4.23.0

### Database Vendor & Version

PostgresSQL 9.6.17

### Liquibase Integration

spring boot

### OS and/or Infrastructure Type/Provider

VM

### Additional Context
under the hoods snakeyaml uses system timezone as default when timezone is missing. 

Example change log 
```yaml
databaseChangeLog:
  - changeSet:
      id: 0.0.1
      author: johndoe
      changes:
      - createTable:
          tableName: example
          columns:
            - column:
                name: id
                type: VARCHAR(255)
                constraints:
                  primarykey: true
                  unique: true
                  nullable: false
            - column:
                name: created_at
                type: TIMESTAMP(3)
                constraints:
                  nullable: false

      - insert:
          tableName: example
          columns:
            - column:
                name: id
                value: example1
            - column:
                name: created_at
                value: 2018-03-09 08:41:31.000
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
