### ISSUE TITLE
Schema name is capitalized when using H2 and `objectQuotingStrategy="QUOTE_ALL_OBJECTS"`

### ISSUE THREAD

**Issue by annedirkdejong** [liquibase/liquibase#5505]
### Search first

- [X] I searched and no similar issues were found

### Description

Starting from version 4.24.0, change sets can not be executed on H2 when all of the following are true:
1. `objectQuotingStrategy="QUOTE_ALL_OBJECTS"` is used (either on a changeSet or on databaseChangeLog)
2. `DATABASE_TO_LOWER=TRUE` is configured in connection string

The `DATABASECHANGELOGLOCK` table will be created on the `public` schema, as it is supposed to.
When Liquibase executes a changeset, it tries to use the `PUBLIC` schema, which does not exist. Resulting in the following error:
`Caused by: liquibase.exception.DatabaseException: Error executing SQL SELECT COUNT(*) FROM "PUBLIC"."DATABASECHANGELOGLOCK": Schema "PUBLIC" not found; SQL statement:`

### Steps To Reproduce

1. Create a new project with H2 and Liquibase
   * I used Spring Initializr with spring boot version 3.1.8
   * spring-boot-starter-data-jpa
   * om.h2database:h2
   * org.liquibase:liquibase-core:4.24.0
   * Java 17
2. Be sure to use `org.liquibase:liquibase-core:4.24.0`
3. Create a change log file with at least one change set
4. Apply  `objectQuotingStrategy="QUOTE_ALL_OBJECTS"` to the change log or change set
5. Add `DATABASE_TO_LOWER=TRUE` to the connection url
6. Start the application

My `db.changelog-master.yaml` file:
```
databaseChangeLog:
  - objectQuotingStrategy: QUOTE_ALL_OBJECTS
  - changeSet:
      id: 001
      author: You
      changes:
        - createTable:
            tableName: Book
            columns:
              - column:
                  name: id
                  type: bigint
                  autoIncrement: true
```
My `application.properties` file:
```
spring.datasource.url=jdbc:h2:mem:test;DATABASE_TO_LOWER=TRUE
```

### Expected/Desired Behavior

Schema name should not be capitalized and respect the `DATABASE_TO_LOWER=TRUE` setting

### Liquibase Version

4.24.0

### Database Vendor & Version

H2 2.1.214

### Liquibase Integration

Spring boot

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
