### ISSUE TITLE
validation don't report an invalid yml

### ISSUE THREAD

**Issue by ramarro123** [liquibase/liquibase#5542]
### Search first

- [X] I searched and no similar issues were found

### Description

if i run validate agains a wrong yml file i got success, and so executing the update.
basically the creation of a index with empty column (due to wrong yml) result in a confusing output, as the script got exitcode = 0 but no index is created

### Steps To Reproduce

use this changeset 

```yaml
databaseChangeLog:
  - changeSet:
      runAlways: true
      id: fabrickspid-001
      author: gbs05304
      changes:
        - createIndex:
            indexName: SPID_WORKFLOWS_IDX_CREATED_DATETIME
            tableName: SPID_WORKFLOWS
            columns:
              - CREATED_DATETIME
        - createIndex:
            indexName: SPID_WORKFLOWS_IDX_COMPLETED_DATETIME
            tableName: SPID_WORKFLOWS
            columns:
              - COMPLETED_DATE_TIME
        - createIndex:
            indexName: SPID_WORKFLOWS_IDX_STATUS
            tableName: SPID_WORKFLOWS
            columns:
              - STATUS
```

### Expected/Desired Behavior

fail during validation

### Liquibase Version

Liquibase Open Source 4.25.1 by Liquibase

### Database Vendor & Version

oracle 19c

### Liquibase Integration

cli

### Liquibase Extensions

none

### OS and/or Infrastructure Type/Provider

ubuntu

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @ramarro123 
I ran `liquibase validate` with the changelog file you've provided, and this was the output:
```
Starting Liquibase at 12:06:52 (version 4.25.1 #690 built at 2023-12-18 16:29+0000)
Liquibase Version: 4.25.1
Liquibase Open Source 4.25.1 by Liquibase
ERROR: Exception Details
ERROR: Exception Primary Class:  ValidationFailedException
ERROR: Exception Primary Reason: Validation Failed:
     3 changes have validation failures
          column 'name' is required for all columns in an index, changelog.yml::fabrickspid-001::gbs05304
          column 'name' is required for all columns in an index, changelog.yml::fabrickspid-001::gbs05304
          column 'name' is required for all columns in an index, changelog.yml::fabrickspid-001::gbs05304

ERROR: Exception Primary Source: 4.25.1

Unexpected error running Liquibase: Validation Failed:
     3 changes have validation failures
          column 'name' is required for all columns in an index, changelog.yml::fabrickspid-001::gbs05304
          column 'name' is required for all columns in an index, changelog.yml::fabrickspid-001::gbs05304
          column 'name' is required for all columns in an index, changelog.yml::fabrickspid-001::gbs05304

For more information, please use the --log-level flag
```

Running `liquibase update` gets the same results.

Could you check if you're using `onValidationFail: MARK_RAN`? [This would explain the behaviour](https://docs.liquibase.com/concepts/changelogs/attributes/on-validation-fail.html).

Otherwise, could you send the error output?

Thank you,
Tatiana

**Comment by vtheuer** [comment]
Hello @tati-qalified,

Here is an example of an invalid yaml (`addForeignKeyConstraint` inside `columns`) passing `validate`: 

```yaml
databaseChangeLog:
  - changeSet:
      id: 1
      author: me
      changes:
        - createTable:
            tableName: table
            columns:
              - column:
                  name: id
                  type: BIGINT
              - addForeignKeyConstraint:
                  constraintName: fk
                  baseTableName: table
                  baseColumnNames: other_id
                  referencedTableName: other_table
                  referencedColumnNames: id

```

Note that the same invalid changelog in json format also passes `validate`: 

```json
{
  "databaseChangeLog": [
    {
      "changeSet": {
        "id": "1",
        "author": "me",
        "changes": [
          {
            "createTable": {
              "tableName": "some_table",
              "columns": [
                {
                  "column": {
                    "name": "id",
                    "type": "BIGINT"
                  }
                },
                {
                  "addForeignKeyConstraint": {
                    "constraintName": "FK",
                    "baseTableName": "some_table",
                    "baseColumnNames": "other_id",
                    "referencedTableName": "some_other_table",
                    "referencedColumnNames": "id"
                  }
                }
              ]
            }
          }
        ]
      }
    }
  ]
}
```

But this variant (different column declaration) fails with the error below: 

```json
{
  "databaseChangeLog": [
    {
      "changeSet": {
        "id": "1",
        "author": "me",
        "changes": [
          {
            "createTable": {
              "tableName": "some_table",
              "columns": [
                {
                  "name": "id",
                  "type": "BIGINT"
                },
                {
                  "addForeignKeyConstraint": {
                    "constraintName": "FK",
                    "baseTableName": "some_table",
                    "baseColumnNames": "other_id",
                    "referencedTableName": "some_other_table",
                    "referencedColumnNames": "id"
                  }
                }
              ]
            }
          }
        ]
      }
    }
  ]
}
```

```
liquibase.exception.ChangeLogParseException: Error parsing db.changelog-master.json : Unexpected node: addForeignKeyConstraint
```

Should I open another issue for this ?
