### ISSUE TITLE
SQLite :: Error "requires access to up to date database metadata..." displays on 'update-sql' command for an AddColumn change

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#5544]
### Search first

- [X] I searched and no similar issues were found

### Description

 `update-sql ` displays an error in the command for an addColumn change the below error is displayed:
```
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset changelog/yaml/createTable.yaml::add_column::mallod:
     Reason: liquibase.exception.DatabaseException: AddColumnStatement requires access to up to date database metadata which is not available in SQL output mode
```

### Steps To Reproduce

Having a change like the one below:
```
  - changeSet:
      id: add_column
      author: mallod
      changes:
        - addColumn:
            tableName: team
            columns:
              - column:
                  constraints:
                    nullable: false
                  name: blub
                  type: text
```
- Execute `update-sql` command.

### Expected/Desired Behavior

`update-sql` should displayed the generated sql code without any error

### Liquibase Version

4.25.1

### Database Vendor & Version

SQLite

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

MacOS (Sonoma 14.0)

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
