### ISSUE TITLE
Validate does not fail when "columns" list contains tags that are not "column"

### ISSUE THREAD

**Issue by vtheuer** [liquibase/liquibase#5623]
### Search first

- [X] I searched and no similar issues were found

### Description

Consider the following changelog: 
```yaml
databaseChangeLog:
- changeSet:
    id: '1'
    author: me
    changes:
    - createTable:
        tableName: some_table
        columns:
        - column:
            name: id
            type: BIGINT
        - createIndex: {}
```
When ran, a table named `some_table` is created with and `id` column, but no index is created, as the `createIndex` is nested inside the `columns` array and not the `changes` array.

The problem is that this changelog passes the `validate` command without error.

The `columns` array should only contain `column` objects, but no error is thrown if it contains something else.

The issue happens in yaml and json formats.

### Steps To Reproduce

Run the validate command on the changelog above.

### Expected/Desired Behavior

An error indicating that an unexpected `createIndex` (or any tag) was found in a `columns` list.

### Liquibase Version

4.26.0

### Database Vendor & Version

Mysql 8.0.31

### Liquibase Integration

maven

### Additional Context

Citing @tati-qalified in #5542 : 

> It's a good catch - the validator doesn't detect new changes if they're wrongly placed inside a columns list.
This is true for yml and json formats.
"Columns" is the only nested tag currently, so it can only be reproduced in a list of columns.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)
