### ISSUE TITLE
Exception Primary Reason: Unexpected node found under databaseChangeLog: changes

### ISSUE THREAD

**Issue by DishenWang2023** [liquibase/liquibase#5684]
### Search first

- [X] I searched and no similar issues were found

### Description

I have newly installed the open source liquibase 4.26.0 and added required the mongodb drivers to the `liquibase/lib` directory,
then I added a sample changelog and tried to validate it but got the following error:
```
ERROR: Exception Details
ERROR: Exception Primary Class:  ParsedNodeException
ERROR: Exception Primary Reason: Unexpected node found under databaseChangeLog: changes
ERROR: Exception Primary Source: MongoDB 0
```

### Steps To Reproduce

install liquibase 4.26.0, added: `mongodb-driver-sync-5.0.0.jar, mongodb-driver-core-5.0.0.jar, liquibase-mongodb-4.24.0.jar, bson-5.0.0.jar` into `liquibase/lib`, validate changelog.yaml:
```
databaseChangeLog:
  - changeSet:
    id: 1
    author: dishen_wang
    labels: createCollectionLabel
    context: createCollectionContext
    comment: create_collection_comment
    changes:
      - createCollection:
        collectionName: towns_yaml

```

### Expected/Desired Behavior

It should validate the sample changelog without any errors 

### Liquibase Version

4.26.0

### Database Vendor & Version

MongoDB

### Liquibase Integration

CLI

### Liquibase Extensions

liquibase-mongodb

### OS and/or Infrastructure Type/Provider

macOS

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)
