### ISSUE TITLE
Liquibase and SQLite doesn't work with NoClassDefFoundError: org/slf4j/LoggerFactory error

### ISSUE THREAD

**Issue by mossad-zika** [liquibase/liquibase#5706]
### Search first

- [X] I searched and no similar issues were found

### Description

`liquibase --version`

```
Starting Liquibase at 08:26:33 (version 4.26.0 #1141 built at 2024-02-06 21:31+0000)
Liquibase Home: /opt/homebrew/Cellar/liquibase/4.26.0/libexec
Java Home /opt/homebrew/Cellar/openjdk/21.0.2/libexec/openjdk.jdk/Contents/Home (Version 21.0.2)
Libraries:
- internal/lib/commons-collections4.jar: Apache Commons Collections 4.4.0 By The Apache Software Foundation
- internal/lib/commons-lang3.jar: Apache Commons Lang 3.13.0 By The Apache Software Foundation
- internal/lib/commons-text.jar: Apache Commons Text 1.11.0 By The Apache Software Foundation
- internal/lib/h2.jar: H2 Database Engine 2.2.224 By H2 Group
- internal/lib/hsqldb.jar: HSQLDB 2.7.2 By The HSQL Development Group
- internal/lib/jaxb-api.jar: jaxb-api 2.3.1 By Oracle Corporation
- internal/lib/jaxb-core.jar: JAXB Core 4.0.4 By Eclipse Foundation
- internal/lib/jaxb-runtime.jar: JAXB Runtime 4.0.4 By Eclipse Foundation
- internal/lib/jaybird.jar: Jaybird 5.0.3.java8 (build: variant=jaybird tag=v5.0.3 date=202311241106) By Firebird project
- internal/lib/jcc.jar: IBM JCC JDBC 4 Driver 1.4.0 By IBM
- internal/lib/liquibase-commercial.jar: Commercial Liquibase Functionality 4.26.0 By Liquibase
- internal/lib/mariadb-java-client.jar: mariadb-java-client 3.3.2 By mariadb.com
- internal/lib/mssql-jdbc.jar: Microsoft JDBC Driver for SQL Server 12.4.1 By Microsoft Corporation
- internal/lib/ojdbc8.jar: JDBC 19.21.0.0.0 By Oracle Corporation
- internal/lib/opencsv.jar: opencsv 5.9.0
- internal/lib/picocli.jar: picocli 4.7.5 By Remko Popma
- internal/lib/postgresql.jar: PostgreSQL JDBC Driver 42.7.1 By PostgreSQL Global Development Group
- internal/lib/snakeyaml.jar: SnakeYAML 2.2.0
- internal/lib/snowflake-jdbc.jar: snowflake-jdbc 3.14.4
- internal/lib/sqlite-jdbc.jar: SQLite JDBC 3.44.1.0


Liquibase Version: 4.26.0
Liquibase Open Source 4.26.0 by Liquibase
```

### Steps To Reproduce

I am trying to do

`liquibase --changeLogFile=initial.sqlite.yaml --url=jdbc:sqlite:/liquibase/bot.db`

And getting such an error

```
Starting Liquibase at 08:28:23 (version 4.26.0 #1141 built at 2024-02-06 21:31+0000)
Liquibase Version: 4.26.0
Liquibase Open Source 4.26.0 by Liquibase

Unexpected error running Liquibase: Could not initialize class org.sqlite.JDBC
  - Caused by: Exception java.lang.NoClassDefFoundError: org/slf4j/LoggerFactory [in thread "main"]

For more information, please use the --log-level flag
```

### Expected/Desired Behavior

Expected behavior is to apply my files

```
databaseChangeLog:
    - include:
        file: changelog/base.yaml
```

and

```
databaseChangeLog:
  - changeSet:
      id: 1
      author: mossad
      changes:
        - createTable:
            tableName: allowed_users
            columns:
              - column:
                  name: user_id
                  type: int
                  constraints:
                    primaryKey: true
                    nullable: false
```

### Liquibase Version

4.26.0

### Database Vendor & Version

SQLite

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

macOS

### Additional Context

**Please help**
