### ISSUE TITLE
changeset with relative path deployed with liquibase 4.6.0 to 4.23.1 are replayed with liquibase > 4.23.1

### ISSUE THREAD

**Issue by jgarec** [liquibase/liquibase#5724]
### Search first

- [X] I searched and no similar issues were found

### Description

We have changeset with relativePath. They were deployed with liquibase 4.8.0 (but all versions between 4.6.0 and 4.23.0 are concerned).
When we tried to upgrade to liquibase 4.24.0 (same result with 4.25 & 4.26), these changesets were replayed.

### Steps To Reproduce

I use docker for this : 
```bash
# Start a postgres database
docker run -d --rm -it --name postgres -e POSTGRES_USER=myusername -e POSTGRES_PASSWORD=mypassword -p 5412:5432 postgres:12
```

```bash
# execute liquibase with any version from to 4.23.0
docker run --rm -it -v ${PWD}:/liquibase/changelog liquibase/liquibase:4.8.0 --changelogFile=changelog-master.yaml --classpath=/liquibase/changelog --url=jdbc:postgresql://host.docker.internal:5412/postgres\?user=myusername\&password=mypassword update
```

```bash
# check the databasechangelog table
postgres=# select id,filename from databasechangelog;
            id             |          filename
---------------------------+----------------------------
 model-create-table-person | model/changelog-table.yaml
(1 row)
```

```bash
# execute liquibase with any version from 4.23.1 to 4.26.0
docker run --rm -it -v ${PWD}:/liquibase/changelog liquibase/liquibase:4.26.0 --changelogFile=changelog-master.yaml --classpath=/liquibase/changelog --url=jdbc:postgresql://host.docker.internal:5412/postgres\?user=myusername\&password=mypassword update

...
Running Changeset: model/foo/../bar/../changelog-table.yaml::model-create-table-person::12345

UPDATE SUMMARY
Run:                          1
Previously run:               0
Filtered out:                 0
-------------------------------
Total change sets:            1

ERROR: Exception Details
ERROR: Exception Primary Class:  PSQLException
ERROR: Exception Primary Reason: ERROR: relation "tb_person" already exists
ERROR: Exception Primary Source: PostgreSQL 12.18 (Debian 12.18-1.pgdg120+2)
```

### Expected/Desired Behavior

we expect : 
```
UPDATE SUMMARY
Run:                          0
Previously run:               1
Filtered out:                 0
-------------------------------
Total change sets:            1
```

### Liquibase Version

>= 4.23.2

### Database Vendor & Version

offline, postgresql

### Liquibase Integration

cli, docker, build with source code

### OS and/or Infrastructure Type/Provider

linux

### Additional Context

create changelog-master.yaml file
```yaml
databaseChangeLog:
- include:
    file: model/foo/../bar/../changelog-table.yaml
    relativeToChangelogFile: true
```

create a model directory and add changelog-table.yaml file
```yaml
databaseChangeLog:
- changeSet:
    id: model-create-table-person
    author: "12345"
    changes:
    - createTable:
        tableName: TB_PERSON
        remarks: Person Table.
        columns:
        - column:
            constraints:
              primaryKey: true
              primaryKeyName: PK_PERSON
            name: PERSON_ID
            type: BIGINT
            remarks: PK
```

### Are you willing to submit a PR?

- [X] I'm willing to submit a PR (Thank you!)
