### ISSUE TITLE
Prevent duplicate databasechangelog properties without breaking when having duplicated sql ones

### ISSUE THREAD

**Issue by MalloD12** [liquibase/liquibase#5963]
### Search first

- [X] I searched and no similar issues were found

### Description

We have recently merged #1826 PR which is preventing duplicated `databasechangelog` properties in a YAML changelog, but this change made the case of having duplicated sql properties like the case displayed below:

```yaml
databaseChangeLog:
- changeSet:
    id: 4-addPartyParrotsTableRunWithSQLPlus
    author: Liquibase Pro User
    labels: external,sqlChange,rollback
    runWith: sqlplus
    changes:
    - sql:
      splitStatements: false
      runWith: sqlplus
      sql: >
       CREATE TABLE partyparrots(
           partyparrot_id NUMBER,
           first_name VARCHAR2(50) NOT NULL,
           last_name VARCHAR2(50) NOT NULL,
           PRIMARY KEY(partyparrot_id)
        );
    - rollback:
        - sql:
            sql: DROP TABLE PARTYPARROTS;
```

I think it would be good (if this not a BREAKING change) to rename the inner `sql:` property to something like `sql_statement`, `sql_body`, or something like that. That way the fix provided in #1826 would be still valid and wouldn't be breaking this other case.  

### Steps To Reproduce

Deploying a changeset like the one provided in the description.

### Expected/Desired Behavior

Do not allow duplicate properties, but without breaking other object's structures like the SQL object.

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
