### ISSUE TITLE
loadData fails for LONGTEXT columns when seeding MySQL

### ISSUE THREAD

**Issue by balczer-dominik** [liquibase/liquibase#6068]
### Search first

- [X] I searched and no similar issues were found

### Description

When using `loadData` with a `.csv` file on a MySQL DB if one of the columns is of type `LONGTEXT` liquibase throws an error like so: 

```
Caused by: liquibase.exception.DatabaseException: The file changelog/this is a longtext was not found in the configured search path:
```

### Step 1:

Create the schema

```sql
CREATE TABLE
    demo_table (
        id INT NOT NULL KEY AUTO_INCREMENT,
        longtext_column LONGTEXT
    );
```

### Step 2:

Create the `data.csv` file

```csv
longtext_column
this is a longtext
```

### Step 3:

Create the following changelog

```yaml
databaseChangeLog:
  - changeSet:
      id: 1
      author: root
      changes:
        - sqlFile:
            path: schema.sql
            relativeToChangelogFile: true
  - changeSet:
      id: 2
      author: root
      runAlways: true
      changes:
        - loadData:
            file: data.csv
            tableName: demo_table
            relativeToChangelogFile: true
```

### Step 4:

Run liquibase

Here's a docker-compose for spinning up a MySQL DB and running liquibase on it.

```yaml
services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_DATABASE: liquibase-longtext
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - liquibase_longtext_mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost"]
      interval: 10s
      retries: 5

  liquibase:
    image: liquibase/liquibase:latest
    container_name: liquibase-longtext
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      LIQUIBASE_COMMAND_URL: jdbc:mysql://mysql:3306/liquibase-longtext?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=UTC
      LIQUIBASE_COMMAND_USERNAME: root
      LIQUIBASE_COMMAND_PASSWORD: root
      LIQUIBASE_COMMAND_CHANGELOG_FILE: /changelog/changelog.yml
    volumes:
     - ./liquibase:/liquibase/changelog
    entrypoint: ["/bin/sh", "-c"]
    command:
      - |
        lpm add mysql --global
        liquibase update --log-level debug

volumes:
  liquibase_longtext_mysql_data:
```

### Expected/Desired Behavior

Liquibase successfully inserts all rows from the csv file including the values for the `LONGTEXT` columns.

### Liquibase Version

4.28

### Database Vendor & Version

MySQL 8.4

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Ubuntu

### Additional Context

There is a way to make liquibase correctly handle these columns and it's by specifying the column as a `string` type like so:

```yaml
  - changeSet:
      id: 3
      author: root
      runAlways: true
      changes:
        - loadData:
            file: data.csv
            tableName: demo_table
            relativeToChangelogFile: true
            columns:
              - column:
                  name: longtext_column
                  type: string
```

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
