### ISSUE TITLE
Yaml changelog parser changed from version 4.28.0 til 4.29.2

### ISSUE THREAD

**Issue by hel1e** [liquibase/liquibase#6404]
### Search first

- [x] I searched and no similar issues were found

### Description

In changetype `createTable`  and `column` attribute we have used Node name `Remarks` instead of `remarks`.  

Until liquibase version 4.29.2 that has not been a problem, but with this new version the node name is now case sensitive and existing changelog files fail.  This is a breaking change, which was not obvious from the Release notes documentation.

### Steps To Reproduce

Add the following to a yaml changelog and test with version 4.28.0. It runs without problems.

Then run it using version 4.29.2, and it fails with an error message like this:

> Unexpected error running Liquibase: Error parsing changelog.yaml : Error parsing myschema.yaml : Unexpected node: Remarks

```
- changeSet:
    id: createTable  MYSCHEMA, tableName MYTABLE
    author: test
    changes:
    - createTable:
        columns:
        - column:
            name: MYCOLUMN
            type: VARCHAR2(130 CHAR)
            Remarks: "test"
        schemaName: MYSCHEMA
        tableName: MYTABLE
        Remarks: "test"

```

### Expected/Desired Behavior

The desired behaviour is that changelogs which are parsed correctly in version 4.28.0 also work with a newer liquibase version.

### Liquibase Version

4.29.2

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by tati-qalified** [comment]
Hi @hel1e, thank you for reaching out to us.
I've looked into this, and was unable to find a change in our code that would cause this. However, `Remarks` is still accepted for the change-type node, but not for the column node. So, this changeset will work:
```
  - changeSet:
      id: createTable  MYSCHEMA, tableName MYTABLE
      author: test
      changes:
      - createTable:
          columns:
          - column:
              name: MYCOLUMN
              type: VARCHAR2(130 CHAR)
              remarks: "test"
          schemaName: MYSCHEMA
          tableName: MYTABLE
          Remarks: "test"
```

According to YAML best practices, all nodes should begin with lowercase letters. Our recommendation is to follow that.
Thank you,
Tatiana
