### ISSUE TITLE
dbms values in changesets

### ISSUE THREAD

**Issue by morfozoid** [liquibase/liquibase#6484]
### Search first

- [x] I searched and no similar issues were found

### Description

Hello.
I’m using liquibase 4.20 and got strange behaviour when using changetype sqlFile:
I mistakenly typed dbms: ‘postgres’ instead of dbms: ‘postgresql’ in my changesets.
And liquibase update ran without errors and even wrote records in databasechangelog about successful execution. But there were no objects created(obviously).
I don’t think this is good behaviour.

Here is example of changeset with wrong dbms type:
```
databaseChangeLog:
-  changeSet:
    id: sqlFile-example
    author: liquibase-docs
    changes:
    - sqlFile:
        dbms:  'postgres'
        path:  my/path/file.sql
```

### Steps To Reproduce

Create changset with dbms type 'postgres' instead of 'postgresql'
Here is example of changeset with wrong dbms type:
```
databaseChangeLog:
-  changeSet:
    id: sqlFile-example
    author: liquibase-docs
    changes:
    - sqlFile:
        dbms:  'postgres'
        path:  my/path/file.sql
```

### Expected/Desired Behavior

Expected behavior is not to write any data in databasechangelog table, because nothing was executed.

### Liquibase Version

4.20

### Liquibase Integration

CLI

### OS and/or Infrastructure Type/Provider

Linux

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
