### ISSUE TITLE
Snowflake: Add Support for Creating Secure Views (SECURE keyword)

### ISSUE THREAD

**Issue by vmatt** [liquibase/liquibase#6647]
### Search first

- [x] I searched and no similar issues were found

### Description

We request adding native support for creating secure views in Liquibase, particularly for databases like Snowflake that support the SECURE keyword in view definitions.

## Current Situation:
- Currently, Liquibase only supports creating regular views through the `createView` change type
- While it's possible to use `fullDefinition: true` and include the SECURE keyword manually in the SQL, this is not optimal as:
  1. It bypasses Liquibase's built-in change type validation
  2. Reduces maintainability and clarity of change logs
  3. Makes it harder to track secure vs non-secure views systematically
  4. Doesn't allow for easy automation and standardization across teams

### Steps To Reproduce

Secure view type cannot defined via yaml configuration.

### Expected/Desired Behavior

Add a secure parameter to `createView`:

```yaml
changeSet:
  id: create-secure-view-example
  author: liquibase
  changes:
    - createView:
        schemaName: myschema
        viewName: my_secure_view
        selectQuery: SELECT * FROM mytable
        secure: true  # New attribute to control SECURE keyword
```

## Benefits
1. Better security governance - explicit tracking of secure views
2. Improved maintainability - standardized way to create secure views
3. Better validation - Liquibase can verify secure view syntax per database
4. Enhanced documentation - built-in support makes secure view creation more discoverable

## Target Databases
- Primary focus: Snowflake
- Future expansion possible for other databases with similar secure view concepts

## Related Documentation
- Snowflake documentation on secure views: https://docs.snowflake.com/en/user-guide/views-secure
- Current Liquibase createView documentation

Priority: Medium
Impact: Security & Maintainability Enhancement

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)
