### ISSUE TITLE
Bug in version 4.30.0 and 4.31.0 : foreignKeyConstraintExists precondition does not work

### ISSUE THREAD

**Issue by hel1e** [liquibase/liquibase#6648]
### Search first

- [x] I searched and no similar issues were found

### Description

We have tested an existing changelog with version 4.30.0. A changeset which uses a foreignKeyConstraintExists precondition is executed even if the foreign key actually does exist in the database, which causes it to fail.

The database is an oracle 19c database.

### Steps To Reproduce

Create a schema with two tables, and one foreign key:

```
create user myschema no authentication;
grant unlimited tablespace to myschema;
create table myschema.my_other_table (my_fk_column number);
alter table MYSCHEMA.MY_OTHER_TABLE
  add constraint MY_OTHER_TABLE_PK primary key (MY_FK_COLUMN);

create table myschema.my_table (my_fk_column number);
alter table MYSCHEMA.MY_TABLE
  add constraint MY_FOREIGN_KEY foreign key (MY_FK_COLUMN)
  references MYSCHEMA.my_other_table (MY_FK_COLUMN);

```

Then run the following changeset with liquibase 4.30.0. This fails. It does not fail with previous versions of liquibase.

```
- changeSet:
    id: addForeignKeyConstraint  MYSCHEMA, foreignKeyName MY_FOREIGN_KEY, foreignKeyTableName MY_TABLE
    author: ${MODULE_NAME}
    preConditions:
      - onFail: MARK_RAN
      - not:
        - foreignKeyConstraintExists:
            schemaName: MYSCHEMA
            foreignKeyName: MY_FOREIGN_KEY
            foreignKeyTableName: MY_TABLE
    changes:
    - addForeignKeyConstraint:
        baseColumnNames: MY_FK_COLUMN
        baseTableName: MY_TABLE
        baseTableSchemaName: MYSCHEMA
        constraintName: MY_FOREIGN_KEY
        deferrable: false
        initiallyDeferred: false
        onDelete: RESTRICT
        onUpdate: RESTRICT
        referencedColumnNames: MY_FK_COLUMN
        referencedTableCatalogName: MYSCHEMA
        referencedTableName: MY_OTHER_TABLE
        validate: true
```

### Expected/Desired Behavior

The precondition check must discover the existing foreign key, so that the changeset is marked as ran instead of failing

### Liquibase Version

4.30.0

### Database Vendor & Version

Oracle 19c

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
