### ISSUE TITLE
Not able to detect objects under a database in Microsoft SQL Server

### ISSUE THREAD

**Issue by maazh10** [liquibase/liquibase#6700]
### Search first

- [x] I searched and no similar issues were found

### Description

Hello, I am trying to compare two databases under SQL Server using `diff-changelog`. Below is my `liquibase.properties`:

```yaml
url: jdbc:sqlserver://{DB_HOST}:1433;databaseName={DB_NAME};encrypt=true;authentication=ActiveDirectoryInteractive

referenceUrl: jdbc:sqlserver://{REF_DB_HOST}:1433;databaseName={REF_DB_NAME};encrypt=true;authentication=ActiveDirectoryInteractive

diffTypes: catalogs,checkconstraints,columns,data,databasepackage,databasepackagebody,foreignkeys,functions,indexes,primarykeys,sequences,storedprocedures,tables,triggers,uniqueconstraints,views

classpath: liquibase-azure-deps-4.31.0.jar
```

The DB host and names are correctly substituted above, and i have the azure dependencies jar in my current working dir.

Running `liquibase diff-changelog --changelog-file="diff-changelog.mssql.sql` successfully executes and both database connections are correctly established after redirecting me to the Entra login screen however no changelog file is generated even though there are many differences between the 2 databases. To investigate further I tried generating a snapshot of just my target database and noticed that Liquibase is not correctly detecting the objects underneath my target db, like no tables, columns, etc are shown:

```json
{
  "snapshot": {
    "created": "2025-02-04T14:27:07.82",
    "database": {
      "productVersion": "12.00.5688",
      "shortName": "mssql",
      "majorVersion": "12",
      "minorVersion": "0",
      "user": "[REDACTED]",
      "productName": "Microsoft SQL Server",
      "url": "jdbc:sqlserver://...[REDACTED]"
    },
    "objects": {
      "liquibase.structure.core.Catalog": [
        {
          "catalog": {
            "default": true,
            "name": "[REDACTED]",
            "snapshotId": "2abb100"
          }
        }
      ]
      
    },
    "snapshotControl": {
      "snapshotControl": {
        "includedType": [
          "liquibase.structure.core.Catalog",
          "liquibase.structure.core.Column",
          "liquibase.structure.core.ForeignKey",
          "liquibase.structure.core.Index",
          "liquibase.structure.core.PrimaryKey",
          "liquibase.structure.core.Schema",
          "liquibase.structure.core.Sequence",
          "liquibase.structure.core.Table",
          "liquibase.structure.core.UniqueConstraint",
          "liquibase.structure.core.View"
        ]
        
      }
    }
  }
}
```

I'm not sure why this is the case because the diff-changelog does work as expected when I tried comparing 2 Databricks schemas. Please let me know if I'm missing anything or misconfiguring something.

### Steps To Reproduce

- Install the liquibase azure dependencies JAR
- Set up liquibase properties using Azure AAD auth:
```yaml
url: jdbc:sqlserver://{DB_HOST}:1433;databaseName={DB_NAME};encrypt=true;authentication=ActiveDirectoryInteractive

referenceUrl: jdbc:sqlserver://{REF_DB_HOST}:1433;databaseName={REF_DB_NAME};encrypt=true;authentication=ActiveDirectoryInteractive

diffTypes: catalogs,checkconstraints,columns,data,databasepackage,databasepackagebody,foreignkeys,functions,indexes,primarykeys,sequences,storedprocedures,tables,triggers,uniqueconstraints,views

classpath: liquibase-azure-deps-4.31.0.jar
```
- Run `liquibase diff-changelog --changelog-file=changelog.mssql.sql`
- Login using the Microsoft Entra account for both databases with sufficient privileges 
- Wait for execution

### Expected/Desired Behavior

After execution of diff-changelog, a changelog.mssql.sql file should be generated in the current working directory containing changesets for all the differences between the target and reference database.

### Liquibase Version

4.31.0

### Database Vendor & Version

SQL Server 12.0.2000.8

### Liquibase Integration

CLI

### Liquibase Extensions

liquibase-azure-deps-4.31.0

### OS and/or Infrastructure Type/Provider

Windows 11

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
