### ISSUE TITLE
MySQL and BOOLEAN column types - needs a bit more work.

### ISSUE THREAD

**Issue by rpsandiford** [liquibase/liquibase#6763]
### Search first

- [x] I searched and no similar issues were found

### Description

A previous issue was created for "Fixes MySQL BIT / TINYINT(1) Boolean Behaviours":  https://github.com/liquibase/liquibase/pull/4090#issuecomment-1764858220.  This references some MySQL documentation about how BOOL and BOOLEAN from other vendors is mapped to TINYINT.   However, MySQL engineers themselves, in Connector/J, further refine this (see below).

The resolution at that time was to change the MySQL BOOLEAN handling to be simply a "TINYINT".  We're running MySQL 5.7 and MySQL Connector/J 8.3.0 and see that a MySQL "TINYINT" column type results in a tinyint(4) column. MySQL Connector/J treats this as an integer rather than a boolean value.  It will treat bit(1) or (by default) tinyint(1) as boolean, and any other tinyint type as integer.

Here's a link to MySQL Connector/J on how it handles bit(1) and tinyint(1) for booleans, and any other tinyint type as integer: https://dev.mysql.com/doc/connector-j/en/connector-j-reference-type-conversions.html

IMHO Liquibase should treat a Liquibase BOOLEAN column type as either a bit(1) (recommended) or a tinyint(1) (would work - unless the tinyInt1isBit property is set to false.  bit(1) should ALWAYS be treated as boolean.)

I think the fix is in BooleanType, in the case for MySQLDatabase, where the original liquibase type does not start with 'bit', and where it isn't also a MariaDBDatabase type.  Change the TINYINT to be (recommended) BIT(1) as it was before the change from the referenced issue.

### Steps To Reproduce

Either:
Create a <createTable> refactoring where one of the columns is defined with type "BOOLEAN", or an <addColumn> refactoring where the column type is "BOOLEAN".
Execute the change set against a MySQL DB.

Or:
In a MySQL DB, create a table with a column of type "tinyint" (as Liquibase does).

Using a MySQL tool (e.g. MySQL Workbench), query the table and look at the column type. It is showing as "tinyint(4)".
Add a row to that table.
Using MySQL Connector/J, run a query against that table, and see that the result set, the underlying column type for the tinyint(4) column is 'Integer'.

Do the same, but create the column as type tinyint(1) or as bit(1).  Now MySQL Connector/J should show the column type as 'Boolean'.

Note that one can directly use tinyint(1) as a column type in a MySQL alter table / create table, and it will create the column with type tinyint(1).  As will using 'bool' as the MySQL column type.   At least with MySQL 5.7 - I don't have an 8.x or higher available to me.

### Expected/Desired Behavior

In MySQL, creating a column with Liquibase type BOOLEAN results in a column that MySQL Connector/J recognizes as a boolean rather than an integer type.

### Liquibase Version

4.27

### Database Vendor & Version

MySQL 5.7.43

### Liquibase Integration

Spring Boot / Java

### OS and/or Infrastructure Type/Provider

N/A.

### Additional Context

I'm only available until the end of March, so while I'm willing to submit a PR for this, there isn't much time left.

### Are you willing to submit a PR?

- [x] I'm willing to submit a PR (Thank you!)

**Comment by rpsandiford** [comment]
Found a bit more explicit MySQL documentation on the 'bool' data type for creating columns:

MySQL 8.x: https://dev.mysql.com/doc/refman/8.4/en/numeric-type-syntax.html
MySQL 7.x: https://dev.mysql.com/doc/refman/5.7/en/numeric-type-syntax.html
In each doc, look for 'bool' - it shows that 'bool' (and 'boolean') are for 'boolean' type columns - will generate a tinyint(1) column, and 0 is treated as false and 1 as true (they are aliases)

Also - sort of 'hidden' in the "Using Data Types from Other Database Engines" page: https://dev.mysql.com/doc/refman/8.4/en/other-vendor-data-types.html
Way down at the bottom is a sample create table where they use 'BOOL' for the column 'a', and in the describe of the table it shows as a 'tinyint(1)'.

**Comment by tati-qalified** [comment]
Hi @rpsandiford, thank you for reaching out. Would you be willing to submit a PR? Our development team is available to guide you through the process and answer any questions you may have.

Thank you,
Tatiana

**Comment by rpsandiford** [comment]
Hi - I'm pretty much out of time on the contract I've had - so, no, I can't submit a PR (well, I could, but I wouldn't be around to address any issues, so someone else would have to take responsibility anyways). What I can do is mention the change I made to a local copy of Liquibase that we're using to get around this problem:

This was against Liquibase 4.27.0:

**Class BooleanType**
Line 43, replace this code:
            return database instanceof MariaDBDatabase ? new DatabaseDataType("TINYINT(1)") : new DatabaseDataType("TINYINT");
with this code:
            return database instanceof MariaDBDatabase ? new DatabaseDataType("TINYINT(1)") : new DatabaseDataType("BOOL");

**Class AddColumnGeneratorTest:**
Line 173, replace this code:
        assertEquals("ALTER TABLE schema_name.table_name ADD column1 BIGINT NULL, ADD column2 TINYINT NULL", sql[0].toSql());
with this code:
        assertEquals("ALTER TABLE schema_name.table_name ADD column1 BIGINT NULL, ADD column2 BOOL NULL", sql[0].toSql());

Line 177, replace this code:
        assertEquals("ALTER TABLE schema_name.table_name MODIFY column2 TINYINT NOT NULL", sql[4].toSql());
with this code:
        assertEquals("ALTER TABLE schema_name.table_name MODIFY column2 BOOL NOT NULL", sql[4].toSql());

**Comment by quangdutran** [comment]
I may help with this too @tati-qalified

**Comment by tati-qalified** [comment]
@quangdutran thank you! @rpsandiford's comment is very thorough, so feel free to submit a PR with those changes and any other you think are necessary. Our devs will be in touch to guide you if necessary.

Thanks again!

**Comment by quangdutran** [comment]
@rpsandiford Hi Robert, I am quite confused about how to reproduce the issue:

This is the changeset to create a table using liquibase `boolean` type:

```
databaseChangeLog:
  - changeSet:
      id: create-table-users
      author: Du
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: INT
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: dob
                  type: timestamp
              - column:
                  name: married
                  type: boolean
```

Then I use DBeaver with default MySQL driver, it shows `tinyint` for the column, not `tinyint(4)`.
And then I download MySQL Connector/J jar driver and get the metadata of the column, it is `tinyint`, not integer.

Am I missing something?

![Image](https://github.com/user-attachments/assets/de19bc1b-bd18-4297-9847-4c4697e60bfd)

**Comment by rpsandiford** [comment]
1. What version of Liquibase are you using?
2. What version of MySQL are you using?
3. Note that there are multiple options for tinyint. e.g. as I reported, I was seeing a tinyint(4) column type. But tinyint(1) is also a valid column type declaration, and is the one the Connector/J will treat as boolean (by default).  So, just seeing 'TINYINT' as the column type isn't quite enough to tell what tinyint(M) it is (i.e. what the value is of 'M')
4. MySQL Workbench would likely be able to tell you the precision value on a tinyint column - that's what I was using.
5. You might also run a jdbc query against a table and see whether the resulting column tpye for 'married' is a boolean type or an integer type.

**Comment by quangdutran** [comment]
Test with MySQL 5, MySQL 8, MySQL Connector/J 8.3.0, 9.3.0

Changeset:
```
databaseChangeLog:
  - changeSet:
      id: create-table-users
      author: YourName
      changes:
        - createTable:
            tableName: users
            columns:
              - column:
                  name: id
                  type: INT
                  constraints:
                    primaryKey: true
                    nullable: false
              - column:
                  name: name
                  type: VARCHAR(255)
              - column:
                  name: dob
                  type: timestamp
              - column:
                  name: married
                  type: boolean
```
Through Connector/J, `married` column has `name=married, type=BIT (-7), precision=1`
