### ISSUE TITLE
RenameColumn silently drops default value in MySQL

### ISSUE THREAD

**Issue by Janosch** [liquibase/liquibase#6876]
### Search first

- [x] I searched and no similar issues were found

### Description

If a column with a default value is renamed via the change type `renameColumn`, the default value is silently dropped when using MySQL. I assume this is also happening for MariaDB but I have not tested it.

The problem is that a changeset like this:
```  
- changeSet:
    id: mychangeset-001
    author: dilbert
    changes:
      - renameColumn:
          tableName: mytable
          columnDataType: tinyint
          oldColumnName: old_name
          newColumnName: new_name
```
is translated to this for MySQL, thereby dropping the default value:
```
ALTER TABLE mytable CHANGE old_name new_name TINYINT;
```

**Solution**

Since MySQL 8.X and MariaDB 10.5.2 there is a new command ALTER TABLE ... RENAME which should be used when the database target is one of those version (or newer).

Here are the docs for RENAME COLUMN: [MariaDB](https://mariadb.com/kb/en/alter-table/#rename-column), [MySQL](https://dev.mysql.com/doc/refman/8.0/en/alter-table.html)

### Steps To Reproduce

Create table with a column that has a default value

```
create table mytable
(
    old_name tinyint default 0 null,
);
```

Run this changeset
```  
- changeSet:
    id: mychangeset-001
    author: dilbert
    changes:
      - renameColumn:
          tableName: mytable
          columnDataType: tinyint
          oldColumnName: old_name
          newColumnName: new_name
```

After running the changeset, the table defintion looks like this:
```
create table mytable
(
    new_name tinyint null,
);
```

### Expected/Desired Behavior

The default value should not be changed when using the change type `renameColumn`

### Liquibase Version

4.31.1 #6739

### Database Vendor & Version

MySQL 8.0.36

### Liquibase Integration

maven

### OS and/or Infrastructure Type/Provider

AWS RDS

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
