### ISSUE TITLE
PostgreSQL Set role for changeSets

### ISSUE THREAD

**Issue by staffanhedstrom** [liquibase/liquibase#6961]
### Search first

- [x] I searched and no similar issues were found

### Description

**FEATURE REQUEST**

Our setup.
We have a PostgreSQL database with a owner role called **our_db_owner**. 
We have a migration runner container which connects to the db with its own user, **db_migrator**.
For permissions to be correctly inherited and such, all objects needs to have the **our_db_owner** as the owner of the object.

**db_migrator** has been granted the **our_db_owner** role, to be allowed to create/delete/alter all objects.

When the migrator runner runs liquibase, all objects will have the **db_migrator** as the owner. Unless we start each changeSet/sqlFile with "SET ROLE our_db_owner". This leads to clunky changeSets like this

```
  - changeSet:
      id: MyFirstChangeSet
      author: Me
      changes:
        - sqlFile:
            path: scripts/SetOwnerRole.sql
            relativeToChangelogFile: true
        - sqlFile:
            path: scripts/user/MyFirstMigration.sql
            relativeToChangelogFile: true
        - sqlFile:
            path: scripts/ResetRole.sql
            relativeToChangelogFile: true
```

Where I need to wrap each changeSet changes with either sqlFiles or straight sql.

It would be incredibly handy if I could instead enter it as a paramter
```
  - changeSet:
      id: MyFirstChangeSet
      author: Me
      role: our_db_owner
      changes:
        - sqlFile:
            path: scripts/user/MyFirstMigration.sql
            relativeToChangelogFile: true
```

Or when running the liquibase update command.

`liquibase update --changelog-file=example-changelog.xml --role=our_db_owner`

### Steps To Reproduce

N/A

### Expected/Desired Behavior

N/A

### Database Vendor & Version

PostgreSQL 15

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)
