### ISSUE TITLE
SpringResourceAccessor::getResourcePath() can't handle the FileSystemResource

### ISSUE THREAD

**Issue by dreamershl** [liquibase/liquibase#6978]
### Search first

- [x] I searched and no similar issues were found

### Description

the issue is caused by class path resource convert again for non-class path resource

```
try{
   String url = resource.getURL().toExternalForm();
   while(!getResource("classpath:" + url).exists())
}
```

### Steps To Reproduce

```yaml
spring:
  liquibase: 
    change-log: file:../liquibase/change-master.yaml
```

### Expected/Desired Behavior

path is resolved properly. no exception UnexpectedLiquibaseException("Could not determine path for ....") thrown 

### Liquibase Version

4.32.0

### Are you willing to submit a PR?

- [ ] I'm willing to submit a PR (Thank you!)

**Comment by filipelautert** [comment]
Did it work with 4.31.1 ?

**Comment by tati-qalified** [comment]
Hi @dreamershl, I have a few questions so that I can try and replicate this issue.

> the issue is caused by class path resource convert again for non-class path resource

> try{
>    String url = resource.getURL().toExternalForm();
>    while(!getResource("classpath:" + url).exists())
> }

Where is this code? Are you using Liquibase embedded in a Java project?

Did this project work with prior versions? If so, which is the last one that worked for you?

Could you provide more information about the steps to reproduce? For example the platform you're using to run Liquibase, the file structure and the command you're running where you encounter the error message.

Thank you,
Tatiana

**Comment by dreamershl** [comment]
this is my first time to use liquibase from springboot. 

**where is the code?**
my project is spring boot. the code is from maven as the following. I have tried both version, 4.29.2. 4.31.1. they are same
```yaml
<artifactId>liquibase-core></artifactId>
<groupId>org.liquibase</groupId>
<version>4.29.2</version>
```

**Embedded liquibase**
yes. 

***liquibase master.yaml***

```yaml
databaseChangeLog:
  - includeAll:
       path: "file: ../liquibase"
       relativeToChangeLogFile: false
       endsWithFilter: ".sql"    
```

***application-liquibase.yaml spring boot config file***
```yaml
spring:
   liquibase:
      change-log: classpath:/liquibase master.yaml
      enabled: true
```   

***maven project structure***
```
---project root      
      --- submodule         
           ---- (standard maven java project folders)
                       --- resources                                   
                             ** application-liquibase.yaml 
                             ** liquibase master.yaml
      --- liquibase
           * changelog1.sql
```
